import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'tr' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    home: 'Home',
    services: 'Services',
    countries: 'Countries',
    about: 'About',
    blog: 'Blog',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    dashboard: 'Dashboard',
    viewAllServices: 'View All Services',
    viewAllCountries: 'View All Countries',

    // Hero Section (HomePage)
    heroTitle: 'AI-Enhanced Global Intelligence',
    heroSubtitle: 'at Your Service',
    heroDescription: 'Next-level regulatory guidance with intelligent automation. Our AI-powered platform connects you with expert consultants across the world\'s most business-friendly jurisdictions.',
    getStarted: 'Get Started Today',
    exploreServices: 'Explore Services',

    // Company Formation CTA (HomePage)
    companyTitle: 'Company Formation',
    companySubtitle: 'Fast & reliable business setup worldwide',
    companyFeature1: 'Expert guidance',
    companyFeature2: 'Global network',
    companyFeature3: 'Compliance assured',
    companyFeature4: 'Professional support',
    companyCta: 'Start Company Formation',

    // Wealth Management CTA (HomePage)
    wealthTitle: 'Wealth Management',
    wealthSubtitle: 'AI-powered investment strategies for global wealth optimization',
    wealthFeature1: 'AI-driven analysis',
    wealthFeature2: 'Global opportunities',
    wealthFeature3: 'Unlimited potential',
    wealthStat1: '$2.5B+ Managed',
    wealthStat2: '98% Success Rate',
    wealthCta: 'Explore Wealth Solutions',

    // Footer
    copyright: '© 2025 Consulting19. All rights reserved',
    powered: 'Powered by AI Oracle',

    // Services Page
    servicesHeroTitle: 'Comprehensive International Business Services',
    servicesHeroDescription: 'From company formation to ongoing compliance, we provide end-to-end support delivered by expert consultants in over 19 countries worldwide.',
    
    // Service Categories
    companyFormation: 'Company Formation',
    companyFormationDesc: 'Complete assistance in company registration and incorporation across business-friendly jurisdictions.',
    companyFormationService1: 'Company registration and incorporation',
    companyFormationService2: 'Business license applications',
    companyFormationService3: 'Corporate structure optimization',
    companyFormationService4: 'Registered agent services',
    companyFormationService5: 'Virtual office solutions',

    taxOptimization: 'Tax Optimization',
    taxOptimizationDesc: 'Strategic tax planning and optimization to minimize your international tax burden legally.',
    taxOptimizationService1: 'International tax planning',
    taxOptimizationService2: 'Double taxation treaty optimization',
    taxOptimizationService3: 'Tax residence strategies',
    taxOptimizationService4: 'Transfer pricing guidance',
    taxOptimizationService5: 'Annual tax compliance',

    bankingSolutions: 'Banking Solutions',
    bankingSolutionsDesc: 'Comprehensive banking support for international business operations.',
    bankingSolutionsService1: 'International bank account opening',
    bankingSolutionsService2: 'Multi-currency account setup',
    bankingSolutionsService3: 'Payment gateway integration',
    bankingSolutionsService4: 'Banking relationship management',
    bankingSolutionsService5: 'Trade finance solutions',

    legalCompliance: 'Legal Compliance',
    legalComplianceDesc: 'Ongoing legal and regulatory compliance support to keep your business compliant.',
    legalComplianceService1: 'Regulatory compliance monitoring',
    legalComplianceService2: 'Contract reviews and drafting',
    legalComplianceService3: 'Legal structure optimization',
    legalComplianceService4: 'Intellectual property protection',
    legalComplianceService5: 'Data protection compliance',

    assetProtection: 'Asset Protection',
    assetProtectionDesc: 'Advanced strategies to protect your assets and minimize risks in international operations.',
    assetProtectionService1: 'Asset protection strategies',
    assetProtectionService2: 'Trust and foundation setup',
    assetProtectionService3: 'Risk assessment and mitigation',
    assetProtectionService4: 'Estate planning for international assets',
    assetProtectionService5: 'Insurance optimization',

    investmentAdvisory: 'Investment Advisory',
    investmentAdvisoryDesc: 'Commercial investment consulting and growth strategies for international markets.',
    investmentAdvisoryService1: 'Market entry strategies',
    investmentAdvisoryService2: 'Investment structure optimization',
    investmentAdvisoryService3: 'Due diligence support',
    investmentAdvisoryService4: 'Exit strategy planning',
    investmentAdvisoryService5: 'Cross-border M&A advisory',

    exploreCategory: 'Explore',
    servicesCtaTitle: 'Need a Custom Solution?',
    servicesCtaDescription: 'Our expert advisors can create a tailored strategy for your unique business needs.',
    consultExpertBtn: 'Consult with Expert',
    exploreCountriesBtn: 'Explore Countries',

    // Countries Page
    countriesHeroTitle: 'Global Business Destinations',
    countriesHeroDescription: 'Explore the world\'s most business-friendly jurisdictions. Each location offers unique advantages for international expansion and tax optimization.',
    searchPlaceholder: 'Search countries...',
    allRegions: 'All Regions',
    regionEurope: 'Europe',
    regionAsia: 'Asia',
    regionMiddleEast: 'Middle East',
    regionAmericas: 'Americas',
    availableDestinations: 'Available Destinations',
    noCountriesFoundTitle: 'No countries found',
    noCountriesFoundDesc: 'Try adjusting your search or filter criteria.',
    corporateTax: 'Corporate Tax',
    featuredBadge: 'FEATURED',
    learnMoreBtn: 'Learn More',

    // About Page
    aboutHeroTitle: 'About Consulting19',
    aboutHeroDescription: 'We\'re revolutionizing international business consulting by combining AI-powered intelligence with a global network of expert advisors.',
    missionTitle: 'Our Mission',
    missionDesc1: 'To democratize international business expansion by making expert advice accessible, affordable, and instant through the power of artificial intelligence.',
    missionDesc2: 'We believe that every entrepreneur should have access to world-class international business guidance, regardless of their location or business size.',
    valuesTitle: 'Our Values',
    valuesDescription: 'The principles that guide everything we do at Consulting19.',
    globalExpertise: 'Global Expertise',
    globalExpertiseDesc: 'Deep knowledge of international business landscapes across 19+ countries.',
    aiEfficiency: 'AI-Powered Efficiency',
    aiEfficiencyDesc: 'Cutting-edge AI technology combined with human expertise for optimal results.',
    trustSecurity: 'Trust & Security',
    trustSecurityDesc: 'Enterprise-grade security protecting your sensitive business information.',
    resultsDriven: 'Results-Driven',
    resultsDrivenDesc: 'Focused on delivering measurable outcomes for your international expansion.',
    teamTitle: 'Meet Our Team',
    teamDescription: 'Experienced professionals from leading consulting firms and technology companies.',
    teamMemberRoleErdal: 'SEO & Digital Marketing Specialist',
    teamMemberBioErdal: 'Expert in search engine optimization and digital marketing strategies for international business expansion.',
    linkedinProfile: 'LinkedIn Profile',
    storyTitle: 'Our Story',
    storyDesc1: 'Consulting19 was born from a simple observation: international business expansion is unnecessarily complex and expensive. Traditional consulting firms charge premium rates while entrepreneurs struggle to navigate foreign regulations alone.',
    storyDesc2: 'By combining cutting-edge AI technology with a carefully curated network of expert advisors in business-friendly jurisdictions, we\'ve created a platform that delivers enterprise-level consulting at a fraction of traditional costs.',
    storyDesc3: 'Today, we\'re proud to serve hundreds of entrepreneurs worldwide, helping them save millions in taxes while expanding their businesses across borders with confidence.',
    ctaTitle: 'Ready to Join Our Mission?',
    ctaDescription: 'Whether you\'re an entrepreneur looking to expand globally or an expert advisor wanting to help others, we\'d love to have you on board.',
    startExpansionBtn: 'Start Your Expansion',
    becomeConsultantBtn: 'Become a Consultant',

    // Hero Section
    heroTitle1: 'AI-Enhanced Global Intelligence',
    heroSubtitle1: 'at Your Service',
    heroDescription1: 'Next-level regulatory guidance with intelligent automation. Our AI-powered platform connects you with expert consultants across the world\'s most business-friendly jurisdictions.',
    heroTitle2: 'Global Network of Experts',
    heroSubtitle2: 'in 19+ Countries',
    heroDescription2: 'Connect with certified business advisors and legal experts across strategic jurisdictions. From UAE to Estonia, our network ensures you get local expertise with global reach.',
    heroTitle3: 'Instant AI-Powered Matching',
    heroSubtitle3: 'Smart Consultant Selection',
    heroDescription3: 'Our advanced AI Oracle analyzes your business needs and instantly matches you with the perfect consultant and jurisdiction for maximum tax efficiency and compliance.',
    heroTitle4: '98% Success Rate',
    heroSubtitle4: 'Proven Track Record',
    heroDescription4: 'Over 1,000 successful business formations with industry-leading completion rates. Our systematic approach and expert guidance ensure your international expansion succeeds.',
    heroTitle5: 'Enterprise-Grade Security',
    heroSubtitle5: 'Bank-Level Protection',
    heroDescription5: 'Your sensitive business data is protected with military-grade encryption, row-level security, and compliance with international data protection standards.',
    heroPrimaryCTA1: 'Get Started Today',
    heroSecondaryCTA1: 'Explore Services',
    heroPrimaryCTA2: 'Find Your Expert',
    heroSecondaryCTA2: 'View Countries',
    heroPrimaryCTA3: 'Try AI Oracle',
    heroSecondaryCTA3: 'Learn More',
    heroPrimaryCTA4: 'View Success Stories',
    heroSecondaryCTA4: 'Our Process',
    heroPrimaryCTA5: 'Security Details',
    heroSecondaryCTA5: 'Compliance Info',
    aiPoweredIntelligence: 'AI-Powered Intelligence',

    // How It Works Section
    howItWorksTitle: 'How Our AI Oracle Works',
    howItWorksDescription: 'Experience the future of international business consulting with our revolutionary AI-powered platform that combines artificial intelligence with human expertise.',
    aiPoweredProcess: 'AI-Powered Process',
    step1Title: 'AI-Powered Business Analysis',
    step1Description: 'Our advanced AI Oracle analyzes your business model, target markets, and growth objectives to create a personalized expansion roadmap tailored to your unique needs.',
    step2Title: 'Instant Smart Recommendations',
    step2Description: 'Within minutes, receive AI-generated recommendations for optimal jurisdictions, tax structures, and business strategies based on real-time data and regulatory intelligence.',
    step3Title: 'Expert Human Connection',
    step3Description: 'Get matched with certified specialists in your chosen countries who combine local expertise with our AI insights to deliver personalized, compliant solutions.',
    step4Title: 'Seamless Global Expansion',
    step4Description: 'Launch your international operations with confidence, backed by continuous AI monitoring, compliance updates, and expert support throughout your growth journey.',
    experienceAiConsulting: 'Experience AI-Powered Consulting Today',

    // Services Overview Section
    servicesOverviewTitle: 'Comprehensive International Business Services',
    servicesOverviewDescription: 'From company formation to ongoing compliance, we provide end-to-end support delivered by expert consultants worldwide.',
    endToEndSolutions: 'End-to-End Business Solutions',
    viewAllServicesBtn: 'View All Services',

    // Featured Countries Section
    featuredCountriesTitle: 'Global Business Destinations',
    featuredCountriesDescription: 'Choose from the world\'s most business-friendly jurisdictions for your international expansion with expert local guidance.',
    businessFriendlyJurisdictions: '19+ Business-Friendly Jurisdictions',
    exploreAllCountriesBtn: 'Explore All Countries',

    // AI Promotion Section
    aiPromotionTitle: 'Meet Your AI Oracle',
    aiPromotionDescription: 'Get instant, personalized recommendations for your international business expansion. Our AI analyzes your needs and connects you with the perfect jurisdiction and expert advisor.',
    instantJurisdictionRecommendations: 'Instant jurisdiction recommendations',
    aiPoweredExpertMatching: 'AI-powered expert matching',
    personalizedBusinessStrategies: 'Personalized business strategies',
    tryAiAssistantFree: 'Try AI Assistant Free',
    aiOracleAssistant: 'AI Oracle Assistant',
    online: 'Online',
    aiAssistantGreeting: 'Hello! I\'m your AI Oracle assistant. I can help you find the best jurisdiction and services for your international business expansion. What type of business are you looking to establish?',
    aiAssistantPlaceholder: 'Ask me about jurisdictions, tax rates, or business setup...',
    aiAssistantQuickStart: 'Quick start:',
    aiAssistantQuick1: 'I want to start a tech company',
    aiAssistantQuick2: 'Looking for tax optimization',
    aiAssistantQuick3: 'Need EU market access',
    aiAssistantQuick4: 'Interested in crypto business',
    aiAssistantPageTitle: 'AI Oracle Assistant',
    aiAssistantPageSubtitle: 'Get instant, personalized recommendations for your international business expansion. Our AI analyzes your needs and suggests the perfect jurisdiction and services.',
    aiAssistantReadyTitle: 'Ready to Get Started?',
    aiAssistantReadyDesc: 'Create your free account to connect with expert advisors and begin your international expansion.',
    createFreeAccount: 'Create Free Account',

    // Service Detail Pages
    whichCountryTitle: 'Which Country Would You Like This Service From?',
    whichCountrySubtitle: 'Choose from our network of business-friendly jurisdictions, each offering unique advantages for your specific needs.',
    availableIn: 'Available in',
    countries: 'countries',
    getStartedIn: 'Get Started in',
    send: 'Send',
    startConsultation: 'Start Consultation',

    // Real Time Analytics Section
    realTimeAnalyticsTitle: 'Real-Time Platform Analytics',
    realTimeAnalyticsDescription: 'Live insights from our worldwide network of expert consultants and AI-powered analytics driving successful business formations.',
    globalIntelligenceNetwork: 'Global Intelligence Network',
    activeConsultations: 'Active Consultations',
    strategicJurisdictions: 'Strategic Jurisdictions',
    successRate: 'Success Rate',
    avgResponseTime: 'Avg Response Time',
    aiPoweredMatching: 'AI-Powered Matching',
    aiMatchingDescription: 'Intelligent consultant-client pairing based on expertise and requirements',
    legalCompliance: 'Legal Compliance',
    legalComplianceDescription: 'All recommendations reviewed by legal experts for full compliance',
    successOptimization: 'Success Optimization',
    successOptimizationDescription: 'Continuous optimization based on successful case patterns',
    joinThousandsTitle: 'Join Thousands of Successful Businesses',
    joinThousandsDescription: 'Experience the power of AI-enhanced consulting with expert guidance across 8 strategic jurisdictions worldwide.',
    startYourJourney: 'Start Your Journey',

    // Blog Section
    blogNewsTitle: 'Blog/News',
    viewAllPosts: 'View All Posts',

    // Service names for sections
    companyFormationTitle: 'Company Formation',
    companyFormationDesc: 'Complete assistance in company registration and incorporation across business-friendly jurisdictions.',
    taxOptimizationTitle: 'Tax Optimization', 
    taxOptimizationDesc: 'Strategic tax planning and optimization to minimize your international tax burden legally.',
    bankingSolutionsTitle: 'Banking Solutions',
    bankingSolutionsDesc: 'Comprehensive banking support for opening international accounts and establishing global financial relationships.',
    legalComplianceTitle: 'Legal Compliance',
    legalComplianceDesc: 'Ongoing legal and regulatory compliance support to keep your business compliant.',
    assetProtectionTitle: 'Asset Protection',
    assetProtectionDesc: 'Advanced strategies to protect your assets and minimize risks in international operations.',
    investmentAdvisoryTitle: 'Investment Advisory',
    investmentAdvisoryDesc: 'Commercial investment consulting and growth strategies for international markets.',
    visaResidencyTitle: 'Visa & Residency',
    visaResidencyDesc: 'Complete visa and residency solutions for international business owners, investors, and their families.',
    marketResearchTitle: 'Market Research',
    marketResearchDesc: 'In-depth market analysis and research for successful international business expansion.',
    learnMore: 'Learn More',

    // Country names and details
    unitedArabEmirates: 'United Arab Emirates',
    estonia: 'Estonia',
    georgia: 'Georgia',
    malta: 'Malta',
    panama: 'Panama',
    portugal: 'Portugal',
    unitedStates: 'United States',
    montenegro: 'Montenegro',
    switzerland: 'Switzerland',

    // Country highlights
    uaeHighlight: '0% corporate tax for 50 years in free zones',
    estoniaHighlight: '100% online e-Residency program',
    georgiaHighlight: 'Small Business Status - 1% tax',
    maltaHighlight: 'EU membership with 5% effective tax rate',
    panamaHighlight: 'Territorial tax system',
    portugalHighlight: 'Golden Visa program with EU residency',
    usaHighlight: 'World\'s largest economy and market',
    montenegroHighlight: 'EU candidate with citizenship by investment',
    switzerlandHighlight: 'Political stability and banking excellence',

    // Country advantages
    noPersonalIncomeTax: 'No personal income tax',
    strategicLocation: 'Strategic location',
    modernInfrastructure: 'Modern infrastructure',
    businessFriendlyRegulations: 'Business-friendly regulations',
    digitalFirstApproach: 'Digital-first approach',
    euMarketAccess: 'EU market access',
    lowBureaucracy: 'Low bureaucracy',
    innovationFriendly: 'Innovation-friendly',
    simpleIncorporation: 'Simple incorporation',
    veryLowTaxes: 'Very low taxes',
    fastSetup: 'Fast setup',
    blockchainFriendly: 'Blockchain-friendly',
    englishSpeaking: 'English-speaking',
    strategicMediterraneanLocation: 'Strategic Mediterranean location',
    territorialTaxation: 'Territorial taxation',
    strongBankingPrivacy: 'Strong banking privacy',
    usDollarEconomy: 'US dollar economy',
    internationalBusinessHub: 'International business hub',
    nhrTaxProgram: 'NHR tax program',
    investmentImmigration: 'Investment immigration',
    strategicAtlanticLocation: 'Strategic Atlantic location',
    largestConsumerMarket: 'Largest consumer market',
    advancedInfrastructure: 'Advanced infrastructure',
    innovationHub: 'Innovation hub',
    strongLegalSystem: 'Strong legal system',
    euCandidateStatus: 'EU candidate status',
    citizenshipByInvestment: 'Citizenship by investment',
    lowCorporateTax: 'Low corporate tax',
    beautifulLocation: 'Beautiful location',
    politicalStability: 'Political stability',
    worldClassBanking: 'World-class banking',
    strategicEuLocation: 'Strategic EU location',

    // Company Formation Page
    companyFormationHeroTitle: 'Seamless Global Company Formation – From Idea to Incorporation',
    companyFormationHeroDesc: 'Establish your business in 19+ countries with expert legal guidance and AI-powered process automation. Fast and compliant incorporation with full banking support.',
    
    // Company Formation Process Steps
    companyFormationProcessStep1Title: 'Choose Your Jurisdiction',
    companyFormationProcessStep1Desc: 'Select the country that best fits your goals with expert recommendations and AI-powered jurisdiction analysis',
    companyFormationProcessStep2Title: 'Free Expert Consultation',
    companyFormationProcessStep2Desc: 'Discuss your needs with our advisors for personalized guidance and strategic business planning',
    companyFormationProcessStep3Title: 'Fast Company Setup',
    companyFormationProcessStep3Desc: 'Complete incorporation in as little as 14 days with AI-supported compliance and legal documentation',
    companyFormationProcessStep4Title: 'Banking & Operations',
    companyFormationProcessStep4Desc: 'Open bank accounts and enable operations with integrated financial solutions and payment processing',
    
    // Company Formation FAQ
    companyFormationFAQ1Question: 'Is offshore company formation legal?',
    companyFormationFAQ1Answer: 'Yes, offshore incorporation is fully legal when structured within international compliance standards. Consulting19 ensures your setup follows jurisdiction-specific laws while offering global banking access. Many multinational corporations use offshore structures for tax optimization, asset protection, and international expansion through legitimate business purposes and proper regulatory compliance.',
    companyFormationFAQ2Question: 'What are the annual reporting requirements?',
    companyFormationFAQ2Answer: 'Annual reporting requirements vary significantly by jurisdiction and business structure. Most countries require annual financial statements, tax returns, and corporate registry updates to maintain good standing. Our automated compliance monitoring service tracks all regulatory deadlines and ensures timely submissions. We provide ongoing support for all compliance services including filing requirements, regulatory updates, and deadline management.',
    companyFormationFAQ3Question: 'What banking options are available?',
    companyFormationFAQ3Answer: 'We provide access to corporate banking in major financial centers including UAE, Estonia, Switzerland, and other business-friendly jurisdictions. Banking options include traditional banks, digital banking solutions, and multi-currency accounts with international payment processing. Our banking specialists facilitate account opening procedures and ensure your company formation includes complete financial infrastructure setup.',
    companyFormationFAQ4Question: 'What are the total costs for company formation?',
    companyFormationFAQ4Answer: 'Company formation costs vary by jurisdiction and services required for complete business setup. Basic offshore incorporation starts from $1,500 (Georgia) to $5,000+ (UAE/Switzerland) including government fees, legal documentation, and our comprehensive service fees. We provide transparent pricing with no hidden costs, and our AI-powered process automation helps reduce overall formation expenses while maintaining premium service quality.',
    companyFormationFAQ5Question: 'How long does the entire process take?',
    companyFormationFAQ5Answer: 'Fast company registration timelines depend on jurisdiction complexity and documentation completeness. Quick jurisdictions like Estonia (1-2 weeks) and Georgia (3-5 days) offer the fastest incorporation processes. More comprehensive setups in UAE or Switzerland typically take 2-6 weeks including banking and compliance services. Our AI-powered automation and real-time progress tracking ensure efficient processing throughout the entire company formation journey.',
    companyFormationWhatWeOffer: 'Comprehensive Company Formation Services',
    companyFormationWhatWeOfferDesc: 'End-to-end business setup solutions with AI-powered jurisdiction analysis and local expert support',
    companyFormationWhyChoose: 'Why Choose Consulting19 for Company Formation?',
    companyFormationWhyChooseDesc: 'Combining global expertise with local knowledge and AI automation for seamless business setup',
    companyFormationHowItWorks: 'How Our Global Company Formation Works',
    companyFormationHowItWorksDesc: 'Simple 4-step process from jurisdiction selection to operational business setup',
    companyFormationBestJurisdictions: 'Best Jurisdictions for Fast Company Registration',
    companyFormationBestJurisdictionsDesc: 'Fast company registration in business-friendly jurisdictions',
    companyFormationFAQ: 'Frequently Asked Questions',
    companyFormationFAQDesc: 'Common questions about offshore incorporation and global business setup',
    companyFormationCTA: 'Ready to Form Your Global Company?',
    companyFormationCTADesc: 'Start your business formation journey with our 3-step simple process',

    // Tax Optimization Page
    taxOptimizationHeroTitle: 'Tax Optimization Services – Maximize Efficiency, Minimize Liability',
    taxOptimizationHeroDesc: 'Leverage 19+ jurisdictions and AI-powered analysis to reduce tax burdens legally and transparently. We design compliant, audit-ready structures tailored to your operations.',
    taxOptimizationWhatWeOffer: 'What We Offer',
    taxOptimizationWhatWeOfferDesc: 'Comprehensive tax optimization strategies for international businesses and individuals',
    taxOptimizationHowItWorks: 'How It Works',
    taxOptimizationHowItWorksDesc: 'Systematic approach to international tax planning and cross-border compliance',
    taxOptimizationJurisdictions: 'Premier Tax-Efficient Jurisdictions',
    taxOptimizationJurisdictionsDesc: 'Leading jurisdictions offering the most attractive tax optimization opportunities',
    taxOptimizationFAQ: 'Frequently Asked Questions',
    taxOptimizationFAQDesc: 'Common questions about international tax planning and optimization strategies',
    taxOptimizationCTA: 'Ready to Optimize Your Taxes?',
    taxOptimizationCTADesc: 'Design a compliant, efficient structure tailored to your global operations',

    // Banking Solutions Page
    bankingSolutionsHeroTitle: 'Global Banking Solutions – Secure, Compliant, and Efficient',
    bankingSolutionsHeroDesc: 'Access premium corporate and personal banking worldwide. Consulting19 helps you connect with leading financial centers, ensuring compliance, multi-currency solutions, and advanced digital banking services.',
    companyFormationWhatWeOffer: 'Comprehensive Company Formation Services',
    companyFormationWhatWeOfferDesc: 'End-to-end business setup solutions with AI-powered jurisdiction analysis and local expert support',
    companyFormationWhyChoose: 'Why Choose Consulting19 for Company Formation?',
    companyFormationWhyChooseDesc: 'Combining global expertise with local knowledge and AI automation for seamless business setup',
    companyFormationHowItWorks: 'How Our Global Company Formation Works',
    companyFormationHowItWorksDesc: 'Simple 4-step process from jurisdiction selection to operational business setup',
    companyFormationBestJurisdictions: 'Best Jurisdictions for Fast Company Registration',
    companyFormationBestJurisdictionsDesc: 'Fast company registration in business-friendly jurisdictions',
    companyFormationFAQ: 'Frequently Asked Questions',
    companyFormationFAQDesc: 'Common questions about offshore incorporation and global business setup',
    companyFormationCTA: 'Ready to Form Your Global Company?',
    companyFormationCTADesc: 'Start your business formation journey with our 3-step simple process',
    bankingSolutionsWhatWeOffer: 'What We Offer',
    bankingSolutionsWhatWeOfferDesc: 'Complete banking solutions for international businesses and individuals',
    bankingSolutionsProcess: 'Our Banking Process',
    bankingSolutionsProcessDesc: 'Streamlined process to open accounts in the world\'s leading banks',
    taxOptimizationWhatWeOffer: 'What We Offer',
    taxOptimizationWhatWeOfferDesc: 'Comprehensive tax optimization strategies for international businesses and individuals',
    taxOptimizationHowItWorks: 'How It Works',
    taxOptimizationHowItWorksDesc: 'Systematic approach to international tax planning and cross-border compliance',
    taxOptimizationJurisdictions: 'Premier Tax-Efficient Jurisdictions',
    taxOptimizationJurisdictionsDesc: 'Leading jurisdictions offering the most attractive tax optimization opportunities',
    taxOptimizationFAQ: 'Frequently Asked Questions',
    taxOptimizationFAQDesc: 'Common questions about international tax planning and optimization strategies',
    taxOptimizationCTA: 'Ready to Optimize Your Taxes?',
    taxOptimizationCTADesc: 'Design a compliant, efficient structure tailored to your global operations',
    bankingSolutionsJurisdictions: 'Premier Banking Jurisdictions',
    bankingSolutionsJurisdictionsDesc: 'Access world-class banking services in leading financial centers',
    bankingSolutionsCTA: 'Ready to Access Global Banking?',
    bankingSolutionsCTADesc: 'Connect with premier banking solutions through our expert guidance',
    bankingSolutionsWhatWeOffer: 'What We Offer',
    bankingSolutionsWhatWeOfferDesc: 'Complete banking solutions for international businesses and individuals',
    bankingSolutionsProcess: 'Our Banking Process',
    bankingSolutionsProcessDesc: 'Streamlined process to open accounts in the world\'s leading banks',
    bankingSolutionsJurisdictions: 'Premier Banking Jurisdictions',
    bankingSolutionsJurisdictionsDesc: 'Access world-class banking services in leading financial centers',
    bankingSolutionsCTA: 'Ready to Access Global Banking?',
    bankingSolutionsCTADesc: 'Connect with premier banking solutions through our expert guidance',

    // Legal Compliance Page
    legalComplianceHeroTitle: 'Legal Compliance Services',
    legalComplianceHeroDesc: 'Ensure full legal compliance across all jurisdictions. Our experts help you navigate complex regulations, maintain good standing, and stay audit-ready in every country you operate.',
    legalComplianceWhatWeOffer: 'What We Offer',
    legalComplianceWhatWeOfferDesc: 'Comprehensive legal compliance services for international businesses',
    legalComplianceProcess: 'Our Legal Compliance Process',
    legalComplianceProcessDesc: 'Systematic approach to ensuring comprehensive legal compliance across all jurisdictions',
    legalComplianceJurisdictions: 'Leading Legal Jurisdictions',
    legalComplianceJurisdictionsDesc: 'Countries offering the most robust and business-friendly legal frameworks for international business compliance',
    legalComplianceCTA: 'Ready to Ensure Compliance?',
    legalComplianceCTADesc: 'Protect your business with comprehensive legal compliance services',
    legalComplianceWhatWeOffer: 'What We Offer',
    legalComplianceWhatWeOfferDesc: 'Comprehensive legal compliance services for international businesses',
    legalComplianceProcess: 'Our Legal Compliance Process',
    legalComplianceProcessDesc: 'Systematic approach to ensuring comprehensive legal compliance across all jurisdictions',
    legalComplianceJurisdictions: 'Leading Legal Jurisdictions',
    legalComplianceJurisdictionsDesc: 'Countries offering the most robust and business-friendly legal frameworks for international business compliance',
    legalComplianceCTA: 'Ready to Ensure Compliance?',
    legalComplianceCTADesc: 'Protect your business with comprehensive legal compliance services',

    // Asset Protection Page
    assetProtectionHeroTitle: 'Asset Protection Services',
    assetProtectionHeroDesc: 'Protect your wealth from legal risks, creditors, and political instability. We design compliant trust, foundation, and holding structures that safeguard assets while maintaining access and control.',
    assetProtectionService1Title: 'Offshore Trusts',
    assetProtectionService1Desc: 'Establish sophisticated offshore trust structures in premier jurisdictions for maximum asset protection and privacy.',
    assetProtectionService2Title: 'Private Foundations',
    assetProtectionService2Desc: 'Create private foundation structures for wealth preservation, succession planning, and philanthropic objectives.',
    assetProtectionService3Title: 'Holding Companies',
    assetProtectionService3Desc: 'Design multi-layered holding company structures for asset isolation, creditor protection, and operational efficiency.',
    assetProtectionService4Title: 'Family Offices',
    assetProtectionService4Desc: 'Establish comprehensive family office structures for ultra-high-net-worth families seeking centralized wealth management.',
    assetProtectionService5Title: 'Succession Planning',
    assetProtectionService5Desc: 'Develop comprehensive succession planning strategies and wealth transfer structures that minimize tax liability.',
    assetProtectionService6Title: 'Privacy Solutions',
    assetProtectionService6Desc: 'Implement advanced privacy solutions and confidentiality structures for high-profile individuals.',
    assetProtectionStep1Title: 'Asset Assessment',
    assetProtectionStep1Desc: 'Map your asset portfolio, legal risks, and exposure points across jurisdictions',
    assetProtectionStep2Title: 'Protection Strategy',
    assetProtectionStep2Desc: 'Design trust, foundation, and holding structures tailored to control, access, and succession needs',
    assetProtectionStep3Title: 'Structure Implementation',
    assetProtectionStep3Desc: 'Establish entities, draft deeds and bylaws, implement governance frameworks, and set up banking',
    assetProtectionStep4Title: 'Ongoing Management',
    assetProtectionStep4Desc: 'Handle filings, renewals, monitoring, and maintain audit-ready records for compliance',
    assetProtectionWhatWeOffer: 'What We Offer',
    assetProtectionWhatWeOfferDesc: 'Sophisticated asset protection strategies for high-net-worth individuals and businesses',
    assetProtectionProcess: 'Our Asset Protection Process',
    assetProtectionProcessDesc: 'Comprehensive approach to protecting your wealth and assets',
    assetProtectionJurisdictions: 'Premier Asset Protection Jurisdictions',
    assetProtectionJurisdictionsDesc: 'Countries offering the strongest asset protection laws and privacy frameworks',
    assetProtectionFAQ: 'Frequently Asked Questions',
    assetProtectionFAQDesc: 'Common questions about asset protection strategies and offshore structures',
    assetProtectionCTA: 'Ready to Protect Your Assets?',
    assetProtectionCTADesc: 'Design a compliant, efficient structure tailored to your global operations',
    assetProtectionWhatWeOffer: 'What We Offer',
    assetProtectionWhatWeOfferDesc: 'Sophisticated asset protection strategies for high-net-worth individuals and businesses',
    assetProtectionProcess: 'Our Asset Protection Process',
    assetProtectionProcessDesc: 'Comprehensive approach to protecting your wealth and assets',
    assetProtectionJurisdictions: 'Premier Asset Protection Jurisdictions',
    assetProtectionJurisdictionsDesc: 'Countries offering the strongest asset protection laws and privacy frameworks',
    assetProtectionFAQ: 'Frequently Asked Questions',
    assetProtectionFAQDesc: 'Common questions about asset protection strategies and offshore structures',
    assetProtectionCTA: 'Ready to Protect Your Assets?',
    assetProtectionCTADesc: 'Design a compliant, efficient structure tailored to your global operations',

    // Investment Advisory Page
    investmentAdvisoryHeroTitle: 'Investment Advisory Services',
    investmentAdvisoryHeroDesc: 'Maximize long-term returns with disciplined, globally diversified strategies. Our advisors deliver tailored asset allocation, risk management, and access to qualified opportunities across public and private markets.',
    investmentAdvisoryService1Title: 'Portfolio Management',
    investmentAdvisoryService1Desc: 'Professional portfolio management services with disciplined asset allocation and global diversification strategies.',
    investmentAdvisoryService2Title: 'Alternative Investments',
    investmentAdvisoryService2Desc: 'Exclusive access to alternative investments including private equity, hedge funds, real estate funds, and other institutional-quality opportunities.',
    investmentAdvisoryService3Title: 'Real Estate Investment',
    investmentAdvisoryService3Desc: 'International real estate investment opportunities across premier global markets with comprehensive property management.',
    investmentAdvisoryService4Title: 'Cryptocurrency Advisory',
    investmentAdvisoryService4Desc: 'Professional cryptocurrency advisory services with comprehensive regulatory compliance and risk management frameworks.',
    investmentAdvisoryService5Title: 'ESG Investing',
    investmentAdvisoryService5Desc: 'Environmental, social, and governance focused investment strategies that align financial returns with sustainable impact.',
    investmentAdvisoryService6Title: 'Wealth Planning',
    investmentAdvisoryService6Desc: 'Comprehensive wealth planning services including estate planning, tax optimization, and intergenerational wealth transfer.',
    investmentAdvisoryStep1Title: 'Portfolio Analysis',
    investmentAdvisoryStep1Desc: 'Assess objectives, constraints, liquidity needs, and current exposures across asset classes and currencies',
    investmentAdvisoryStep2Title: 'Strategy Development',
    investmentAdvisoryStep2Desc: 'Design a policy portfolio with risk budgets, benchmarks, and rebalancing rules tailored to goals',
    investmentAdvisoryStep3Title: 'Implementation',
    investmentAdvisoryStep3Desc: 'Execute across vetted managers and platforms; optimize fees, execution, and tax efficiency',
    investmentAdvisoryStep4Title: 'Performance Monitoring',
    investmentAdvisoryStep4Desc: 'Ongoing reporting, variance analysis, and quarterly reviews to adjust the strategy',
    investmentAdvisoryWhatWeOffer: 'What We Offer',
    investmentAdvisoryWhatWeOfferDesc: 'Professional investment advisory services for sophisticated investors',
    investmentAdvisoryProcess: 'Our Investment Advisory Process',
    investmentAdvisoryProcessDesc: 'Systematic approach to building and managing your investment portfolio',
    investmentAdvisoryJurisdictions: 'Premier Investment Jurisdictions',
    investmentAdvisoryJurisdictionsDesc: 'Leading financial centers for investment management and wealth preservation',
    investmentAdvisoryFAQ: 'Frequently Asked Questions',
    investmentAdvisoryFAQDesc: 'Common questions about investment advisory services and wealth management strategies',
    investmentAdvisoryCTA: 'Ready to Grow Your Wealth?',
    investmentAdvisoryCTADesc: 'Start building a diversified global investment portfolio today',
    investmentAdvisoryWhatWeOffer: 'What We Offer',
    investmentAdvisoryWhatWeOfferDesc: 'Professional investment advisory services for sophisticated investors',
    investmentAdvisoryProcess: 'Our Investment Advisory Process',
    investmentAdvisoryProcessDesc: 'Systematic approach to building and managing your investment portfolio',
    investmentAdvisoryJurisdictions: 'Premier Investment Jurisdictions',
    investmentAdvisoryJurisdictionsDesc: 'Leading financial centers for investment management and wealth preservation',
    investmentAdvisoryFAQ: 'Frequently Asked Questions',
    investmentAdvisoryFAQDesc: 'Common questions about investment advisory services and wealth management strategies',
    investmentAdvisoryCTA: 'Ready to Grow Your Wealth?',
    investmentAdvisoryCTADesc: 'Start building a diversified global investment portfolio today',

    // Visa & Residency Page
    visaResidencyHeroTitle: 'Visa & Residency Services',
    visaResidencyHeroDesc: 'Secure residency or citizenship in your preferred country. Our immigration experts guide you through eligibility, program selection, compliant documentation, and end-to-end application support.',
    visaResidencyService1Title: 'Golden Visa Programs',
    visaResidencyService1Desc: 'Investment-based residency programs offering pathways to EU and global mobility through real estate, fund investments, or business creation.',
    visaResidencyService2Title: 'Investor Visas',
    visaResidencyService2Desc: 'Entrepreneur and business investor visa routes designed for founders creating jobs and driving innovation in target countries.',
    visaResidencyService3Title: 'Citizenship by Investment',
    visaResidencyService3Desc: 'Fast-track citizenship programs through approved government investment routes with comprehensive background screening.',
    visaResidencyService4Title: 'Skilled Worker Visas',
    visaResidencyService4Desc: 'Employment-based visa programs for professionals seeking international career opportunities through employer sponsorship.',
    visaResidencyService5Title: 'Family Reunification',
    visaResidencyService5Desc: 'Comprehensive family visa services for spouses, children, and dependent relatives seeking to join family members.',
    visaResidencyService6Title: 'Permanent Residency',
    visaResidencyService6Desc: 'Long-term settlement pathways leading to permanent residency status with comprehensive integration support.',
    visaResidencyStep1Title: 'Eligibility Assessment',
    visaResidencyStep1Desc: 'Assess your profile against program criteria, timelines, and total costs',
    visaResidencyStep2Title: 'Program Selection',
    visaResidencyStep2Desc: 'Compare countries and routes; choose the option that fits your goals and risk tolerance',
    visaResidencyStep3Title: 'Application Preparation',
    visaResidencyStep3Desc: 'Gather documents, translations, legalizations, and compliant investment proofs',
    visaResidencyStep4Title: 'Approval & Settlement',
    visaResidencyStep4Desc: 'Liaise with authorities, track approvals, and assist with landing, PR, and renewals',
    visaResidencyWhatWeOffer: 'What We Offer',
    visaResidencyWhatWeOfferDesc: 'Comprehensive visa and residency services for global mobility',
    visaResidencyProcess: 'Our Visa & Residency Process',
    visaResidencyProcessDesc: 'Step-by-step guidance through visa applications and residency programs',
    visaResidencyDestinations: 'Popular Residency Destinations',
    visaResidencyDestinationsDesc: 'Countries offering attractive visa and residency programs for investors',
    visaResidencyFAQ: 'Frequently Asked Questions',
    visaResidencyFAQDesc: 'Common questions about visa services and residency programs',
    visaResidencyCTA: 'Ready to Secure Your Residency?',
    visaResidencyCTADesc: 'Start your journey to global mobility with expert, end-to-end guidance',

    // Market Research Page
    marketResearchHeroTitle: 'Market Research Services',
    marketResearchHeroDesc: 'Make informed decisions with data-driven market intelligence. Our researchers deliver deep insights on customers, competitors, regulations, and go-to-market opportunities across global markets.',
    marketResearchService1Title: 'Market Entry Analysis',
    marketResearchService1Desc: 'Comprehensive market entry strategies that include demand sizing, route-to-market evaluation, pricing corridors analysis.',
    marketResearchService2Title: 'Competitor Intelligence',
    marketResearchService2Desc: 'Strategic competitor analysis covering competitive strategy and positioning, share-of-voice and share-of-shelf metrics.',
    marketResearchService3Title: 'Consumer Research',
    marketResearchService3Desc: 'Advanced consumer insights using quantitative and qualitative research methods including surveys, interviews, and consumer panels.',
    marketResearchService4Title: 'Industry Reports',
    marketResearchService4Desc: 'Comprehensive industry analysis including Total Addressable Market (TAM), Serviceable Addressable Market (SAM) calculations.',
    marketResearchService5Title: 'Regulatory Research',
    marketResearchService5Desc: 'Detailed regulatory landscape analysis covering compliance requirements, licensing and permit procedures.',
    marketResearchService6Title: 'Partnership Opportunities',
    marketResearchService6Desc: 'Strategic partnership identification services including comprehensive long-list and short-list development.',
    marketResearchStep1Title: 'Market Analysis',
    marketResearchStep1Desc: 'Define objectives and scope; collect primary/secondary data to quantify demand and dynamics',
    marketResearchStep2Title: 'Competitive Research',
    marketResearchStep2Desc: 'Map players, offerings, pricing, and positioning to reveal white-space and threats',
    marketResearchStep3Title: 'Strategy Development',
    marketResearchStep3Desc: 'Translate findings into entry strategy, messaging, and commercial model with KPIs',
    marketResearchStep4Title: 'Implementation Support',
    marketResearchStep4Desc: 'Assist with partner outreach, pilots, and first-90-days tracking to validate results',
    marketResearchWhatWeOffer: 'What We Offer',
    marketResearchWhatWeOfferDesc: 'Data-driven market research and business intelligence services for informed expansion decisions',
    marketResearchProcess: 'Our Market Research Process',
    marketResearchProcessDesc: 'Systematic approach to understanding markets and identifying opportunities',
    marketResearchDestinations: 'Key Market Research Destinations',
    marketResearchDestinationsDesc: 'Leading markets with comprehensive research capabilities and business opportunities',
    marketResearchFAQ: 'Frequently Asked Questions',
    marketResearchFAQDesc: 'Common questions about market research services and business intelligence solutions',
    marketResearchCTA: 'Ready to Research Your Market?',
    marketResearchCTADesc: 'Get comprehensive market intelligence to drive confident expansion decisions',

    // Common buttons and actions
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    scheduleConsultation: 'Schedule Consultation',
    chooseCountry: 'Choose Country',
    viewServices: 'View Services',
    startConsultation: 'Start Consultation',
    backToServices: 'Back to Services',
    visaResidencyWhatWeOffer: 'What We Offer',
    visaResidencyWhatWeOfferDesc: 'Comprehensive visa and residency services for global mobility',
    visaResidencyProcess: 'Our Visa & Residency Process',
    visaResidencyProcessDesc: 'Step-by-step guidance through visa applications and residency programs',
    visaResidencyDestinations: 'Popular Residency Destinations',
    visaResidencyDestinationsDesc: 'Countries offering attractive visa and residency programs for investors',
    visaResidencyFAQ: 'Frequently Asked Questions',
    visaResidencyFAQDesc: 'Common questions about visa services and residency programs',
    visaResidencyCTA: 'Ready to Secure Your Residency?',
    visaResidencyCTADesc: 'Start your journey to global mobility with expert, end-to-end guidance',

    // Market Research Page
    companyFormationService1Title: 'LLC & Corporation Formation',
    companyFormationService1Desc: 'Professional LLC and corporation formation services across multiple jurisdictions with complete liability protection.',
    companyFormationService2Title: 'Offshore Company Registration',
    companyFormationService2Desc: 'Strategic offshore incorporation in business-friendly jurisdictions with favorable tax structures.',
    companyFormationService3Title: 'Jurisdiction Analysis',
    companyFormationService3Desc: 'Advanced AI-powered jurisdiction analysis that evaluates tax implications, regulatory requirements, and business advantages.',
    companyFormationService4Title: 'Digital Identity & e-Residency',
    companyFormationService4Desc: 'Complete digital identity solutions including Estonia e-Residency program for 100% online business management.',
    companyFormationService5Title: 'Banking & Payment Solutions',
    companyFormationService5Desc: 'Comprehensive corporate banking solutions including business account opening, multi-currency accounts.',
    companyFormationService6Title: 'Holding Company Structures',
    companyFormationService6Desc: 'Sophisticated holding company structures designed for asset protection, tax optimization, and international business expansion.',
    companyFormationService7Title: 'Compliance Monitoring',
    companyFormationService7Desc: 'Automated compliance monitoring services that track regulatory deadlines, filing requirements, and ongoing obligations.',
    companyFormationService8Title: 'AI-Assistant Integration',
    companyFormationService8Desc: 'Intelligent AI assistant integration for automated document management, compliance deadline tracking.',
    companyFormationStep1Title: 'Choose Your Jurisdiction',
    companyFormationStep1Desc: 'Select the country that best fits your goals with expert recommendations and AI-powered jurisdiction analysis',
    companyFormationStep2Title: 'Free Expert Consultation',
    companyFormationStep2Desc: 'Discuss your needs with our advisors for personalized guidance and strategic business planning',
    companyFormationStep3Title: 'Fast Company Setup',
    companyFormationStep3Desc: 'Complete incorporation in as little as 14 days with AI-supported compliance and legal documentation',
    companyFormationStep4Title: 'Banking & Operations',
    companyFormationStep4Desc: 'Open bank accounts and enable operations with integrated financial solutions and payment processing',
    companyFormationWhyChoose1Title: 'Global + Local Expertise',
    companyFormationWhyChoose1Desc: 'Local specialists in 19+ countries combined with AI-powered global insights.',
    companyFormationWhyChoose2Title: '500+ Successful Setups',
    companyFormationWhyChoose2Desc: '98% success rate with over 500 companies formed across multiple jurisdictions.',
    companyFormationWhyChoose3Title: 'AI-Powered Automation',
    companyFormationWhyChoose3Desc: 'Smart document tracking, compliance deadlines, and automated progress updates.',
    companyFormationWhyChoose4Title: 'Transparent & Cost-Effective',
    companyFormationWhyChoose4Desc: 'Clear pricing with no hidden fees and competitive rates for premium services.',
    marketResearchHeroTitle: 'Market Research Services',
    marketResearchHeroDesc: 'Make informed decisions with data-driven market intelligence.',
    marketResearchWhatWeOffer: 'What We Offer',
    marketResearchWhatWeOfferDesc: 'Data-driven market research and business intelligence services for informed expansion decisions',
    taxOptimizationService1Title: 'International Tax Planning',
    taxOptimizationService1Desc: 'Strategic international tax planning that leverages global jurisdictions to minimize corporate and personal tax obligations.',
    taxOptimizationService2Title: 'Transfer Pricing Strategies',
    taxOptimizationService2Desc: 'Advanced transfer pricing strategies for multinational enterprises operating across multiple jurisdictions.',
    taxOptimizationService3Title: 'Cross-Border Compliance',
    taxOptimizationService3Desc: 'Comprehensive cross-border taxation compliance services that navigate complex international tax obligations.',
    taxOptimizationService4Title: 'Holding & Group Structuring',
    taxOptimizationService4Desc: 'Sophisticated holding company structures designed for tax optimization, asset protection, and international business expansion.',
    taxOptimizationService5Title: 'IP & Royalty Planning',
    taxOptimizationService5Desc: 'Intellectual property and royalty planning strategies that align value creation with tax outcomes.',
    taxOptimizationService6Title: 'VAT/GST & Indirect Tax',
    taxOptimizationService6Desc: 'Comprehensive VAT/GST and indirect tax compliance services for businesses operating across multiple jurisdictions.',
    taxOptimizationService7Title: 'Permanent Establishment (PE) Review',
    taxOptimizationService7Desc: 'Professional permanent establishment risk assessment and mitigation strategies for businesses operating across international borders.',
    taxOptimizationService8Title: 'Residency & Treaty Benefits',
    taxOptimizationService8Desc: 'Strategic tax residency planning and double tax treaty optimization to maximize international tax efficiency.',
    taxOptimizationStep1Title: 'Discovery & Risk Assessment',
    taxOptimizationStep1Desc: 'Map your business model, revenue flows, and exposure points across jurisdictions',
    taxOptimizationStep2Title: 'Jurisdiction & Treaty Analysis',
    taxOptimizationStep2Desc: 'Evaluate double tax treaties, withholding taxes, and substance requirements to select optimal routes',
    taxOptimizationStep3Title: 'Implementation & Documentation',
    taxOptimizationStep3Desc: 'Set up compliant structures, transfer pricing policies, and statutory documentation',
    taxOptimizationStep4Title: 'Monitoring & Reporting',
    taxOptimizationStep4Desc: 'Track rule changes, perform annual reviews, and prepare audit-ready reports',
    marketResearchProcess: 'Our Market Research Process',
    marketResearchProcessDesc: 'Systematic approach to understanding markets and identifying opportunities',
    marketResearchDestinations: 'Key Market Research Destinations',
    marketResearchDestinationsDesc: 'Leading markets with comprehensive research capabilities and business opportunities',
    bankingSolutionsService1Title: 'Corporate Account Opening',
    bankingSolutionsService1Desc: 'Professional corporate account opening services in premier financial centers worldwide.',
    bankingSolutionsService2Title: 'Multi-Currency Accounts',
    bankingSolutionsService2Desc: 'Advanced multi-currency banking solutions that enable your business to hold, manage, and transact in multiple currencies.',
    bankingSolutionsService3Title: 'Private Banking',
    bankingSolutionsService3Desc: 'Exclusive private banking services tailored for high-net-worth individuals and successful entrepreneurs.',
    bankingSolutionsService4Title: 'Trade Finance',
    bankingSolutionsService4Desc: 'Comprehensive trade finance solutions including letters of credit, bank guarantees, and international trade financing.',
    bankingSolutionsService5Title: 'Digital Banking Solutions',
    bankingSolutionsService5Desc: 'Cutting-edge digital banking solutions designed for modern businesses and digital entrepreneurs.',
    bankingSolutionsService6Title: 'Investment Banking',
    bankingSolutionsService6Desc: 'Professional investment banking services including capital raising, mergers and acquisitions advisory.',
    bankingSolutionsStep1Title: 'Banking Requirements Analysis',
    bankingSolutionsStep1Desc: 'Identify your business needs, compliance obligations, and preferred banking jurisdictions',
    bankingSolutionsStep2Title: 'Bank Selection',
    bankingSolutionsStep2Desc: 'Choose the optimal bank based on jurisdiction, product features, and your operational model',
    bankingSolutionsStep3Title: 'Account Opening',
    bankingSolutionsStep3Desc: 'Streamline documentation and due diligence processes for smooth onboarding',
    bankingSolutionsStep4Title: 'Banking Setup',
    bankingSolutionsStep4Desc: 'Enable online banking, payment systems, and ongoing support for global operations',
    marketResearchFAQ: 'Frequently Asked Questions',
    marketResearchFAQDesc: 'Common questions about market research services and business intelligence solutions',
    marketResearchCTA: 'Ready to Research Your Market?',
    marketResearchCTADesc: 'Get comprehensive market intelligence to drive confident expansion decisions',
    legalComplianceService1Title: 'Corporate Governance',
    legalComplianceService1Desc: 'Establish robust corporate governance frameworks including board resolutions, shareholder agreements, and compliance policies.',
    legalComplianceService2Title: 'Regulatory Compliance',
    legalComplianceService2Desc: 'Navigate industry-specific regulatory requirements across finance, healthcare, technology, and other sectors.',
    legalComplianceService3Title: 'Data Protection Compliance',
    legalComplianceService3Desc: 'Achieve full GDPR compliance, CCPA adherence, and comprehensive data privacy regulation compliance.',
    legalComplianceService4Title: 'Anti-Money Laundering (AML/KYC)',
    legalComplianceService4Desc: 'Implement comprehensive AML KYC procedures and compliance programs that meet international standards.',
    legalComplianceService5Title: 'Contract Management',
    legalComplianceService5Desc: 'Professional legal contract drafting, review, and management systems for international business operations.',
    legalComplianceService6Title: 'Intellectual Property Protection',
    legalComplianceService6Desc: 'Comprehensive intellectual property protection strategies including patent filing, trademark registration.',
    legalComplianceStep1Title: 'Compliance Assessment',
    legalComplianceStep1Desc: 'Evaluate your current status, risks, and gaps across jurisdictions with a documented baseline',
    legalComplianceStep2Title: 'Regulatory Mapping',
    legalComplianceStep2Desc: 'Identify all applicable laws and obligations, including sector-specific rules and filing deadlines',
    legalComplianceStep3Title: 'Implementation',
    legalComplianceStep3Desc: 'Deploy policies, procedures, and documentation systems; align teams with clear workflows',
    legalComplianceStep4Title: 'Ongoing Monitoring',
    legalComplianceStep4Desc: 'Track regulatory changes, renewals, and audits with scheduled reviews and automated reminders',

    // Blog
    blogNewsTitle: 'Latest Insights & News',
    viewAllPosts: 'View All Posts',

    // About Page
    businessFriendlyJurisdictions: 'Business-Friendly Jurisdictions',
    featuredCountriesTitle: 'Discover Business-Friendly Countries',
    featuredCountriesDescription: 'Explore our curated selection of the world\'s most attractive business destinations',
    companyTitle: 'Company Formation Services',
    companySubtitle: 'Fast, compliant business setup in 19+ countries',
    companyFeature1: 'AI-powered jurisdiction analysis',
    companyFeature2: 'Expert local advisors',
    companyFeature3: 'Complete banking support',
    companyFeature4: 'Ongoing compliance monitoring',
    companyCta: 'Start Company Formation',
    wealthTitle: 'Matrix — Private Wealth Platform',
    wealthSubtitle: 'Ultra-high-net-worth solutions with AI-driven analysis',
    wealthFeature1: 'AI-driven global allocation',
    wealthFeature2: 'Multi-jurisdiction banking',
    wealthFeature3: 'Strict confidentiality protocols',
    wealthStat1: '$5M+ Min',
    wealthStat2: '98% Success',
    wealthCta: 'Explore Matrix Wealth',
  },
  tr: {
    // Navigation
    home: 'Ana Sayfa',
    services: 'Hizmetler',
    countries: 'Ülkeler',
    about: 'Hakkımızda',
    blog: 'Blog',
    contact: 'İletişim',
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    logout: 'Çıkış Yap',
    dashboard: 'Panel',
    viewAllServices: 'Tüm Hizmetleri Görüntüle',
    viewAllCountries: 'Tüm Ülkeleri Görüntüle',

    // Hero Section (HomePage)
    heroTitle: 'Yapay Zeka Destekli Küresel Zeka',
    heroSubtitle: 'Hizmetinizde',
    heroDescription: 'Akıllı otomasyon ile yeni nesil düzenleyici rehberlik. Yapay zeka destekli platformumuz, sizi dünyanın en iş dostu yargı bölgelerindeki uzman danışmanlarla buluşturur.',
    getStarted: 'Bugün Başlayın',
    exploreServices: 'Hizmetleri Keşfedin',

    // Company Formation CTA (HomePage)
    companyTitle: 'Şirket Kuruluşu',
    companySubtitle: 'Dünya çapında hızlı ve güvenilir iş kurulumu',
    companyFeature1: 'Uzman rehberliği',
    companyFeature2: 'Küresel ağ',
    companyFeature3: 'Uyumluluk garantisi',
    companyFeature4: 'Profesyonel destek',
    companyCta: 'Şirket Kuruluşunu Başlat',

    // Wealth Management CTA (HomePage)
    wealthTitle: 'Varlık Yönetimi',
    wealthSubtitle: 'Küresel servet optimizasyonu için yapay zeka destekli yatırım stratejileri',
    wealthFeature1: 'Yapay zeka odaklı analiz',
    wealthFeature2: 'Küresel fırsatlar',
    wealthFeature3: 'Sınırsız potansiyel',
    wealthStat1: '2.5 Milyar$+ Yönetilen',
    wealthStat2: '%98 Başarı Oranı',
    wealthCta: 'Varlık Çözümlerini Keşfet',

    // Footer
    copyright: '© 2025 Consulting19. Tüm hakları saklıdır',
    powered: 'AI Oracle tarafından desteklenmektedir',

    // Services Page
    servicesHeroTitle: 'Kapsamlı Uluslararası İş Hizmetleri',
    servicesHeroDescription: 'Şirket kuruluşundan sürekli uyumluluğa kadar, 19\'dan fazla ülkedeki uzman danışmanlar tarafından sunulan uçtan uca destek sağlıyoruz.',
    
    // Service Categories
    companyFormation: 'Şirket Kuruluşu',
    companyFormationDesc: 'İş dostu yargı bölgelerinde şirket tescili ve kuruluşu konusunda eksiksiz yardım.',
    companyFormationService1: 'Şirket tescili ve kuruluşu',
    companyFormationService2: 'İşletme lisansı başvuruları',
    companyFormationService3: 'Kurumsal yapı optimizasyonu',
    companyFormationService4: 'Tescilli acente hizmetleri',
    companyFormationService5: 'Sanal ofis çözümleri',

    taxOptimization: 'Vergi Optimizasyonu',
    taxOptimizationDesc: 'Uluslararası vergi yükünüzü yasal olarak en aza indirmek için stratejik vergi planlaması ve optimizasyonu.',
    taxOptimizationService1: 'Uluslararası vergi planlaması',
    taxOptimizationService2: 'Çifte vergilendirme anlaşması optimizasyonu',
    taxOptimizationService3: 'Vergi ikametgahı stratejileri',
    taxOptimizationService4: 'Transfer fiyatlandırması rehberliği',
    taxOptimizationService5: 'Yıllık vergi uyumluluğu',

    bankingSolutions: 'Bankacılık Çözümleri',
    bankingSolutionsDesc: 'Uluslararası iş operasyonları için kapsamlı bankacılık desteği.',
    bankingSolutionsService1: 'Uluslararası banka hesabı açılışı',
    bankingSolutionsService2: 'Çoklu para birimi hesabı kurulumu',
    bankingSolutionsService3: 'Ödeme ağ geçidi entegrasyonu',
    bankingSolutionsService4: 'Bankacılık ilişkileri yönetimi',
    bankingSolutionsService5: 'Ticaret finansmanı çözümleri',

    legalCompliance: 'Yasal Uyumluluk',
    legalComplianceDesc: 'İşletmenizin uyumlu kalması için sürekli yasal ve düzenleyici uyumluluk desteği.',
    legalComplianceService1: 'Düzenleyici uyumluluk izleme',
    legalComplianceService2: 'Sözleşme incelemeleri ve taslağı',
    legalComplianceService3: 'Yasal yapı optimizasyonu',
    legalComplianceService4: 'Fikri mülkiyet koruması',
    legalComplianceService5: 'Veri koruma uyumluluğu',

    assetProtection: 'Varlık Korunması',
    assetProtectionDesc: 'Uluslararası operasyonlarda varlıklarınızı korumak ve riskleri en aza indirmek için gelişmiş stratejiler.',
    assetProtectionService1: 'Varlık koruma stratejileri',
    assetProtectionService2: 'Vakıf ve fon kurulumu',
    assetProtectionService3: 'Risk değerlendirmesi ve azaltma',
    assetProtectionService4: 'Uluslararası varlıklar için miras planlaması',
    assetProtectionService5: 'Sigorta optimizasyonu',

    investmentAdvisory: 'Yatırım Danışmanlığı',
    investmentAdvisoryDesc: 'Uluslararası pazarlar için ticari yatırım danışmanlığı ve büyüme stratejileri.',
    investmentAdvisoryService1: 'Pazara giriş stratejileri',
    investmentAdvisoryService2: 'Yatırım yapısı optimizasyonu',
    investmentAdvisoryService3: 'Durum tespiti desteği',
    investmentAdvisoryService4: 'Çıkış stratejisi planlaması',
    investmentAdvisoryService5: 'Sınır ötesi birleşme ve satın alma danışmanlığı',

    exploreCategory: 'Keşfet',
    servicesCtaTitle: 'Özel Bir Çözüme mi İhtiyacınız Var?',
    servicesCtaDescription: 'Uzman danışmanlarımız, benzersiz iş ihtiyaçlarınız için özel bir strateji oluşturabilir.',
    consultExpertBtn: 'Uzmanla Danışın',
    exploreCountriesBtn: 'Ülkeleri Keşfedin',

    // Countries Page
    countriesHeroTitle: 'Küresel İş Destinasyonları',
    countriesHeroDescription: 'Dünyanın en iş dostu yargı bölgelerini keşfedin. Her konum, uluslararası genişleme ve vergi optimizasyonu için benzersiz avantajlar sunar.',
    searchPlaceholder: 'Ülkeleri ara...',
    allRegions: 'Tüm Bölgeler',
    regionEurope: 'Avrupa',
    regionAsia: 'Asya',
    regionMiddleEast: 'Orta Doğu',
    regionAmericas: 'Amerika',
    availableDestinations: 'Mevcut Destinasyonlar',
    noCountriesFoundTitle: 'Ülke bulunamadı',
    noCountriesFoundDesc: 'Arama veya filtreleme kriterlerinizi ayarlamayı deneyin.',
    corporateTax: 'Kurumlar Vergisi',
    featuredBadge: 'ÖNE ÇIKAN',
    learnMoreBtn: 'Daha Fazla Bilgi',

    // About Page
    aboutHeroTitle: 'Consulting19 Hakkında',
    aboutHeroDescription: 'Yapay zeka destekli zekayı küresel uzman danışman ağıyla birleştirerek uluslararası iş danışmanlığını devrim niteliğinde değiştiriyoruz.',
    missionTitle: 'Misyonumuz',
    missionDesc1: 'Yapay zekanın gücüyle uzman tavsiyesini erişilebilir, uygun fiyatlı ve anında hale getirerek uluslararası iş genişlemesini demokratikleştirmek.',
    missionDesc2: 'Her girişimcinin, konumu veya işletme büyüklüğü ne olursa olsun, dünya standartlarında uluslararası iş rehberliğine erişmesi gerektiğine inanıyoruz.',
    valuesTitle: 'Değerlerimiz',
    valuesDescription: 'Consulting19\'da yaptığımız her şeye rehberlik eden ilkeler.',
    globalExpertise: 'Küresel Uzmanlık',
    globalExpertiseDesc: '19\'dan fazla ülkedeki uluslararası iş ortamları hakkında derin bilgi.',
    aiEfficiency: 'Yapay Zeka Destekli Verimlilik',
    aiEfficiencyDesc: 'Optimal sonuçlar için insan uzmanlığıyla birleştirilmiş son teknoloji yapay zeka teknolojisi.',
    trustSecurity: 'Güven & Güvenlik',
    trustSecurityDesc: 'Hassas iş bilgilerinizi koruyan kurumsal düzeyde güvenlik.',
    resultsDriven: 'Sonuç Odaklı',
    resultsDrivenDesc: 'Uluslararası genişlemeniz için ölçülebilir sonuçlar sunmaya odaklanmıştır.',
    teamTitle: 'Ekibimizle Tanışın',
    teamDescription: 'Önde gelen danışmanlık firmalarından ve teknoloji şirketlerinden deneyimli profesyoneller.',
    teamMemberRoleErdal: 'SEO & Dijital Pazarlama Uzmanı',
    teamMemberBioErdal: 'Uluslararası iş genişlemesi için arama motoru optimizasyonu ve dijital pazarlama stratejileri konusunda uzman.',
    linkedinProfile: 'LinkedIn Profili',
    storyTitle: 'Hikayemiz',
    storyDesc1: 'Consulting19, basit bir gözlemden doğdu: uluslararası iş genişlemesi gereksiz yere karmaşık ve pahalı. Geleneksel danışmanlık firmaları yüksek ücretler talep ederken, girişimciler yabancı düzenlemelerde tek başına gezinmekte zorlanıyor.',
    storyDesc2: 'Son teknoloji yapay zeka teknolojisini, iş dostu yargı bölgelerindeki özenle seçilmiş uzman danışman ağıyla birleştirerek, geleneksel maliyetlerin çok altında kurumsal düzeyde danışmanlık sunan bir platform oluşturduk.',
    storyDesc3: 'Bugün, dünya çapında yüzlerce girişimciye hizmet vermekten gurur duyuyoruz, işlerini güvenle sınırlar ötesine genişletirken milyonlarca vergi tasarrufu yapmalarına yardımcı oluyoruz.',
    ctaTitle: 'Misyonumuza Katılmaya Hazır mısınız?',
    ctaDescription: 'İster küresel olarak genişlemek isteyen bir girişimci olun, ister başkalarına yardım etmek isteyen bir uzman danışman olun, sizi aramızda görmekten mutluluk duyarız.',
    startExpansionBtn: 'Genişlemenizi Başlatın',
    becomeConsultantBtn: 'Danışman Olun',

    // Hero Section
    heroTitle1: 'Yapay Zeka Destekli Küresel Zeka',
    heroSubtitle1: 'Hizmetinizde',
    heroDescription1: 'Akıllı otomasyon ile yeni nesil düzenleyici rehberlik. Yapay zeka destekli platformumuz, sizi dünyanın en iş dostu yargı bölgelerindeki uzman danışmanlarla buluşturur.',
    heroTitle2: 'Küresel Uzman Ağı',
    heroSubtitle2: '19+ Ülkede',
    heroDescription2: 'Stratejik yargı bölgelerindeki sertifikalı iş danışmanları ve hukuk uzmanlarıyla bağlantı kurun. BAE\'den Estonya\'ya, ağımız küresel erişimle yerel uzmanlık sağlar.',
    heroTitle3: 'Anında Yapay Zeka Destekli Eşleştirme',
    heroSubtitle3: 'Akıllı Danışman Seçimi',
    heroDescription3: 'Gelişmiş AI Oracle\'ımız iş ihtiyaçlarınızı analiz eder ve maksimum vergi verimliliği ve uyumluluk için mükemmel danışman ve yargı bölgesiyle anında eşleştirir.',
    heroTitle4: '%98 Başarı Oranı',
    heroSubtitle4: 'Kanıtlanmış Sicil',
    heroDescription4: 'Sektör lideri tamamlanma oranlarıyla 1.000\'den fazla başarılı şirket kuruluşu. Sistematik yaklaşımımız ve uzman rehberliğimiz uluslararası genişlemenizin başarılı olmasını sağlar.',
    heroTitle5: 'Kurumsal Düzeyde Güvenlik',
    heroSubtitle5: 'Banka Düzeyinde Koruma',
    heroDescription5: 'Hassas iş verileriniz askeri düzeyde şifreleme, satır düzeyinde güvenlik ve uluslararası veri koruma standartlarına uygunlukla korunur.',
    heroPrimaryCTA1: 'Bugün Başlayın',
    heroSecondaryCTA1: 'Hizmetleri Keşfedin',
    heroPrimaryCTA2: 'Uzmanınızı Bulun',
    heroSecondaryCTA2: 'Ülkeleri Görüntüleyin',
    heroPrimaryCTA3: 'AI Oracle\'ı Deneyin',
    heroSecondaryCTA3: 'Daha Fazla Bilgi',
    heroPrimaryCTA4: 'Başarı Hikayelerini Görüntüleyin',
    heroSecondaryCTA4: 'Sürecimiz',
    heroPrimaryCTA5: 'Güvenlik Detayları',
    heroSecondaryCTA5: 'Uyumluluk Bilgisi',
    aiPoweredIntelligence: 'Yapay Zeka Destekli Zeka',

    // How It Works Section
    howItWorksTitle: 'AI Oracle\'ımız Nasıl Çalışır',
    howItWorksDescription: 'Yapay zeka ile insan uzmanlığını birleştiren devrimci yapay zeka destekli platformumuzla uluslararası iş danışmanlığının geleceğini deneyimleyin.',
    aiPoweredProcess: 'Yapay Zeka Destekli Süreç',
    step1Title: 'Yapay Zeka Destekli İş Analizi',
    step1Description: 'Gelişmiş AI Oracle\'ımız iş modelinizi, hedef pazarlarınızı ve büyüme hedeflerinizi analiz ederek benzersiz ihtiyaçlarınıza göre kişiselleştirilmiş bir genişleme yol haritası oluşturur.',
    step2Title: 'Anında Akıllı Öneriler',
    step2Description: 'Dakikalar içinde, gerçek zamanlı veriler ve düzenleyici zekaya dayalı optimal yargı bölgeleri, vergi yapıları ve iş stratejileri için yapay zeka tarafından üretilen öneriler alın.',
    step3Title: 'Uzman İnsan Bağlantısı',
    step3Description: 'Kişiselleştirilmiş, uyumlu çözümler sunmak için yerel uzmanlığı AI içgörülerimizle birleştiren seçtiğiniz ülkelerdeki sertifikalı uzmanlarla eşleşin.',
    step4Title: 'Sorunsuz Küresel Genişleme',
    step4Description: 'Sürekli AI izleme, uyumluluk güncellemeleri ve büyüme yolculuğunuz boyunca uzman desteğiyle desteklenen güvenle uluslararası operasyonlarınızı başlatın.',
    experienceAiConsulting: 'Bugün Yapay Zeka Destekli Danışmanlığı Deneyimleyin',

    // Services Overview Section
    servicesOverviewTitle: 'Kapsamlı Uluslararası İş Hizmetleri',
    servicesOverviewDescription: 'Şirket kuruluşundan sürekli uyumluluğa kadar, dünya çapındaki uzman danışmanlar tarafından sunulan uçtan uca destek sağlıyoruz.',
    endToEndSolutions: 'Uçtan Uca İş Çözümleri',
    viewAllServicesBtn: 'Tüm Hizmetleri Görüntüle',

    // Featured Countries Section
    featuredCountriesTitle: 'Küresel İş Destinasyonları',
    featuredCountriesDescription: 'Uzman yerel rehberlikle uluslararası genişlemeniz için dünyanın en iş dostu yargı bölgelerinden seçim yapın.',
    businessFriendlyJurisdictions: '19+ İş Dostu Yargı Bölgesi',
    exploreAllCountriesBtn: 'Tüm Ülkeleri Keşfedin',

    // AI Promotion Section
    aiPromotionTitle: 'AI Oracle\'ınızla Tanışın',
    aiPromotionDescription: 'Uluslararası iş genişlemeniz için anında, kişiselleştirilmiş öneriler alın. AI\'mız ihtiyaçlarınızı analiz eder ve sizi mükemmel yargı bölgesi ve uzman danışmanla buluşturur.',
    instantJurisdictionRecommendations: 'Anında yargı bölgesi önerileri',
    aiPoweredExpertMatching: 'Yapay zeka destekli uzman eşleştirme',
    personalizedBusinessStrategies: 'Kişiselleştirilmiş iş stratejileri',
    tryAiAssistantFree: 'AI Asistanı Ücretsiz Deneyin',
    aiOracleAssistant: 'AI Oracle Asistanı',
    online: 'Çevrimiçi',

    // Service Detail Pages
    whichCountryTitle: 'Bu Hizmeti Hangi Ülkeden Almak İstiyorsunuz?',
    whichCountrySubtitle: 'İhtiyaçlarınıza özel avantajlar sunan, iş dostu yargı yetkilerimiz arasından seçim yapın.',
    availableIn: 'Mevcut',
    countries: 'ülkede',
    getStartedIn: 'Başlayın',
    aiAssistantGreeting: 'Merhaba! Ben AI Oracle asistanınızım. Uluslararası iş genişlemeniz için en iyi yargı yetkisi ve hizmetleri bulmanıza yardımcı olabilirim. Hangi tür bir iş kurmak istiyorsunuz?',
    aiAssistantPlaceholder: 'Yargı yetkileri, vergi oranları veya iş kurulumu hakkında sorun...',
    aiAssistantQuickStart: 'Hızlı başlangıç:',
    aiAssistantQuick1: 'Teknoloji şirketi kurmak istiyorum',
    aiAssistantQuick2: 'Vergi optimizasyonu arıyorum',
    aiAssistantQuick3: 'AB pazarına erişim istiyorum',
    aiAssistantQuick4: 'Kripto işi yapmak istiyorum',
    aiAssistantPageTitle: 'AI Oracle Asistanı',
    aiAssistantPageSubtitle: 'Uluslararası iş genişlemeniz için anında, kişiselleştirilmiş öneriler alın. AI\'mız ihtiyaçlarınızı analiz eder ve mükemmel yargı yetkisi ile hizmetleri önerir.',
    aiAssistantReadyTitle: 'Başlamaya Hazır mısınız?',
    aiAssistantReadyDesc: 'Uzman danışmanlarla bağlantı kurmak ve uluslararası genişlemenizi başlatmak için ücretsiz hesabınızı oluşturun.',
    createFreeAccount: 'Ücretsiz Hesap Oluştur',
    send: 'Gönder',
    startConsultation: 'Danışmanlığı Başlatın',

    // Real Time Analytics Section
    realTimeAnalyticsTitle: 'Gerçek Zamanlı Platform Analitikleri',
    realTimeAnalyticsDescription: 'Başarılı iş kuruluşlarını yönlendiren dünya çapındaki uzman danışman ağımızdan ve yapay zeka destekli analitiğimizden canlı içgörüler.',
    globalIntelligenceNetwork: 'Küresel Zeka Ağı',
    activeConsultations: 'Aktif Danışmanlıklar',
    strategicJurisdictions: 'Stratejik Yargı Bölgeleri',
    successRate: 'Başarı Oranı',
    avgResponseTime: 'Ort. Yanıt Süresi',
    aiPoweredMatching: 'Yapay Zeka Destekli Eşleştirme',
    aiMatchingDescription: 'Uzmanlık ve gereksinimlere dayalı akıllı danışman-müşteri eşleştirmesi',
    legalCompliance: 'Yasal Uyumluluk',
    legalComplianceDescription: 'Tüm öneriler tam uyumluluk için hukuk uzmanları tarafından gözden geçirilir',
    successOptimization: 'Başarı Optimizasyonu',
    successOptimizationDescription: 'Başarılı vaka kalıplarına dayalı sürekli optimizasyon',
    joinThousandsTitle: 'Binlerce Başarılı İşletmeye Katılın',
    joinThousandsDescription: '8 stratejik yargı bölgesinde uzman rehberlikle yapay zeka destekli danışmanlığın gücünü deneyimleyin.',
    startYourJourney: 'Yolculuğunuzu Başlatın',

    // Blog Section
    blogNewsTitle: 'Blog/Haberler',
    viewAllPosts: 'Tüm Yazıları Görüntüle',

    // Service names for sections
    companyFormationTitle: 'Şirket Kuruluşu',
    companyFormationDesc: 'İş dostu yargı bölgelerinde şirket tescili ve kuruluşu konusunda eksiksiz yardım.',
    taxOptimizationTitle: 'Vergi Optimizasyonu',
    taxOptimizationDesc: 'Uluslararası vergi yükünüzü yasal olarak en aza indirmek için stratejik vergi planlaması ve optimizasyonu.',
    bankingSolutionsTitle: 'Bankacılık Çözümleri',
    bankingSolutionsDesc: 'Uluslararası hesap açma ve küresel finansal ilişkiler kurma için kapsamlı bankacılık desteği.',
    legalComplianceTitle: 'Yasal Uyumluluk',
    legalComplianceDesc: 'İşletmenizin uyumlu kalması için sürekli yasal ve düzenleyici uyumluluk desteği.',
    assetProtectionTitle: 'Varlık Korunması',
    assetProtectionDesc: 'Uluslararası operasyonlarda varlıklarınızı korumak ve riskleri en aza indirmek için gelişmiş stratejiler.',
    investmentAdvisoryTitle: 'Yatırım Danışmanlığı',
    investmentAdvisoryDesc: 'Uluslararası pazarlar için ticari yatırım danışmanlığı ve büyüme stratejileri.',
    visaResidencyTitle: 'Vize ve İkamet',
    visaResidencyDesc: 'Uluslararası iş sahipleri, yatırımcılar ve aileleri için eksiksiz vize ve ikamet çözümleri.',
    marketResearchTitle: 'Pazar Araştırması',
    marketResearchDesc: 'Başarılı uluslararası iş genişlemesi için derinlemesine pazar analizi ve araştırması.',
    learnMore: 'Daha Fazla Bilgi',

    // Country names and details
    unitedArabEmirates: 'Birleşik Arap Emirlikleri',
    estonia: 'Estonya',
    georgia: 'Gürcistan',
    malta: 'Malta',
    panama: 'Panama',
    portugal: 'Portekiz',
    unitedStates: 'Amerika Birleşik Devletleri',
    montenegro: 'Karadağ',
    switzerland: 'İsviçre',

    // Country highlights
    uaeHighlight: 'Serbest bölgelerde 50 yıl boyunca %0 kurumlar vergisi',
    estoniaHighlight: '%100 online e-Residency programı',
    georgiaHighlight: 'Küçük İşletme Statüsü - %1 vergi',
    maltaHighlight: '%5 efektif vergi oranıyla AB üyeliği',
    panamaHighlight: 'Bölgesel vergi sistemi',
    portugalHighlight: 'AB ikametiyle Altın Vize programı',
    usaHighlight: 'Dünyanın en büyük ekonomisi ve pazarı',
    montenegroHighlight: 'Yatırımla vatandaşlık sunan AB adayı',
    switzerlandHighlight: 'Siyasi istikrar ve bankacılık mükemmelliği',

    // Country advantages
    noPersonalIncomeTax: 'Kişisel gelir vergisi yok',
    strategicLocation: 'Stratejik konum',
    modernInfrastructure: 'Modern altyapı',
    businessFriendlyRegulations: 'İş dostu düzenlemeler',
    digitalFirstApproach: 'Dijital öncelikli yaklaşım',
    euMarketAccess: 'AB pazarına erişim',
    lowBureaucracy: 'Düşük bürokrasi',
    innovationFriendly: 'İnovasyona dost',
    simpleIncorporation: 'Basit kuruluş',
    veryLowTaxes: 'Çok düşük vergiler',
    fastSetup: 'Hızlı kurulum',
    blockchainFriendly: 'Blockchain dostu',
    englishSpeaking: 'İngilizce konuşulan',
    strategicMediterraneanLocation: 'Stratejik Akdeniz konumu',
    territorialTaxation: 'Bölgesel vergilendirme',
    strongBankingPrivacy: 'Güçlü bankacılık gizliliği',
    usDollarEconomy: 'ABD doları ekonomisi',
    internationalBusinessHub: 'Uluslararası iş merkezi',
    nhrTaxProgram: 'NHR vergi programı',
    investmentImmigration: 'Yatırım göçü',
    strategicAtlanticLocation: 'Stratejik Atlantik konumu',
    largestConsumerMarket: 'En büyük tüketici pazarı',
    advancedInfrastructure: 'Gelişmiş altyapı',
    innovationHub: 'İnovasyon merkezi',
    strongLegalSystem: 'Güçlü hukuk sistemi',
    euCandidateStatus: 'AB aday statüsü',
    citizenshipByInvestment: 'Yatırımla vatandaşlık',
    lowCorporateTax: 'Düşük kurumlar vergisi',
    beautifulLocation: 'Güzel konum',
    politicalStability: 'Siyasi istikrar',
    worldClassBanking: 'Dünya standartlarında bankacılık',
    strategicEuLocation: 'Stratejik AB konumu',

    // Company Formation Page
    companyFormationHeroTitle: 'Küresel Şirket Kuruluşu – Fikirden Kuruluşa Kadar',
    companyFormationHeroDesc: '19+ ülkede uzman hukuki rehberlik ve AI destekli süreç otomasyonu ile işinizi kurun. Tam bankacılık desteği ile hızlı ve uyumlu kuruluş.',
    
    // Company Formation Process Steps
    companyFormationProcessStep1Title: 'Yargı Yetkisini Seçin',
    companyFormationProcessStep1Desc: 'Uzman önerileri ve AI destekli yargı analizi ile hedeflerinize en uygun ülkeyi seçin',
    companyFormationProcessStep2Title: 'Ücretsiz Uzman Danışmanlığı',
    companyFormationProcessStep2Desc: 'Kişiselleştirilmiş rehberlik ve stratejik iş planlaması için danışmanlarımızla ihtiyaçlarınızı görüşün',
    companyFormationProcessStep3Title: 'Hızlı Şirket Kurulumu',
    companyFormationProcessStep3Desc: 'AI destekli uyumluluk ve yasal dokümantasyon ile 14 gün gibi kısa sürede kuruluşu tamamlayın',
    companyFormationProcessStep4Title: 'Bankacılık ve Operasyonlar',
    companyFormationProcessStep4Desc: 'Entegre finansal çözümler ve ödeme işlemleri ile banka hesapları açın ve operasyonları etkinleştirin',
    
    // Company Formation FAQ
    companyFormationFAQ1Question: 'Offshore şirket kuruluşu yasal mı?',
    companyFormationFAQ1Answer: 'Evet, uluslararası uyumluluk standartları çerçevesinde yapılandırıldığında offshore kuruluş tamamen yasaldır. Consulting19, küresel bankacılık erişimi sunarken kurulumunuzun yargı yetkisine özgü yasalara uymasını sağlar. Birçok çok uluslu şirket, meşru iş amaçları ve uygun düzenleyici uyumluluk yoluyla vergi optimizasyonu, varlık korunması ve uluslararası genişleme için offshore yapılar kullanır.',
    companyFormationFAQ2Question: 'Yıllık raporlama gereklilikleri nelerdir?',
    companyFormationFAQ2Answer: 'Yıllık raporlama gereklilikleri yargı yetkisi ve iş yapısına göre önemli ölçüde değişir. Çoğu ülke iyi durumda kalmak için yıllık mali tablolar, vergi beyannameleri ve kurumsal kayıt güncellemeleri gerektirir. Otomatik uyumluluk izleme hizmetimiz tüm düzenleyici son tarihleri takip eder ve zamanında gönderim sağlar. Dosyalama gereklilikleri, düzenleyici güncellemeler ve son tarih yönetimi dahil tüm uyumluluk hizmetleri için sürekli destek sağlarız.',
    companyFormationFAQ3Question: 'Hangi bankacılık seçenekleri mevcut?',
    companyFormationFAQ3Answer: 'BAE, Estonya, İsviçre ve diğer iş dostu yargı yetkileri dahil olmak üzere büyük finansal merkezlerde kurumsal bankacılığa erişim sağlarız. Bankacılık seçenekleri geleneksel bankalar, dijital bankacılık çözümleri ve uluslararası ödeme işlemleri ile çok para birimli hesapları içerir. Bankacılık uzmanlarımız hesap açma prosedürlerini kolaylaştırır ve şirket kuruluşunuzun eksiksiz finansal altyapı kurulumunu içermesini sağlar.',
    companyFormationFAQ4Question: 'Şirket kuruluşu için toplam maliyetler nelerdir?',
    companyFormationFAQ4Answer: 'Şirket kuruluş maliyetleri yargı yetkisi ve eksiksiz iş kurulumu için gerekli hizmetlere göre değişir. Temel offshore kuruluş, devlet ücretleri, yasal dokümantasyon ve kapsamlı hizmet ücretlerimiz dahil olmak üzere 1.500$ (Gürcistan) ile 5.000$+ (BAE/İsviçre) arasında başlar. Gizli maliyet olmadan şeffaf fiyatlandırma sağlarız ve AI destekli süreç otomasyonumuz premium hizmet kalitesini korurken genel kuruluş giderlerini azaltmaya yardımcı olur.',
    companyFormationFAQ5Question: 'Tüm süreç ne kadar sürer?',
    companyFormationFAQ5Answer: 'Hızlı şirket kayıt süreleri yargı karmaşıklığı ve dokümantasyon eksiksizliğine bağlıdır. Estonya (1-2 hafta) ve Gürcistan (3-5 gün) gibi hızlı yargı yetkileri en hızlı kuruluş süreçlerini sunar. BAE veya İsviçre\'deki daha kapsamlı kurulumlar genellikle bankacılık ve uyumluluk hizmetleri dahil 2-6 hafta sürer. AI destekli otomasyonumuz ve gerçek zamanlı ilerleme takibimiz tüm şirket kuruluş yolculuğu boyunca verimli işleme sağlar.',
    companyFormationWhatWeOffer: 'Kapsamlı Şirket Kuruluş Hizmetleri',
    companyFormationWhatWeOfferDesc: 'AI destekli yargı analizi ve yerel uzman desteği ile uçtan uca iş kurulum çözümleri',
    companyFormationWhyChoose: 'Şirket Kuruluşu İçin Neden Consulting19?',
    companyFormationWhyChooseDesc: 'Sorunsuz iş kurulumu için küresel uzmanlığı yerel bilgi ve AI otomasyonu ile birleştiriyoruz',
    companyFormationHowItWorks: 'Küresel Şirket Kuruluşumuz Nasıl Çalışır',
    companyFormationHowItWorksDesc: 'Yargı seçiminden operasyonel iş kurulumuna kadar basit 4 adımlı süreç',
    companyFormationBestJurisdictions: 'Hızlı Şirket Kaydı İçin En İyi Yargı Yetkileri',
    companyFormationBestJurisdictionsDesc: 'İş dostu yargı yetkilerinde hızlı şirket kaydı',
    companyFormationFAQ: 'Sık Sorulan Sorular',
    companyFormationFAQDesc: 'Offshore kuruluş ve küresel iş kurulumu hakkında yaygın sorular',
    companyFormationCTA: 'Küresel Şirketinizi Kurmaya Hazır mısınız?',
    companyFormationCTADesc: 'Basit 3 adımlı sürecimizle iş kuruluş yolculuğunuza başlayın',

    // Tax Optimization Page
    taxOptimizationHeroTitle: 'Vergi Optimizasyon Hizmetleri – Verimliliği Artırın, Yükümlülüğü Azaltın',
    taxOptimizationHeroDesc: '19+ yargı yetkisini ve AI destekli analizi kullanarak vergi yüklerini yasal ve şeffaf şekilde azaltın. Operasyonlarınıza özel uyumlu, denetim hazır yapılar tasarlıyoruz.',
    taxOptimizationWhatWeOffer: 'Sunduklarımız',
    taxOptimizationWhatWeOfferDesc: 'Uluslararası işletmeler ve bireyler için kapsamlı vergi optimizasyon stratejileri',
    taxOptimizationHowItWorks: 'Nasıl Çalışır',
    taxOptimizationHowItWorksDesc: 'Uluslararası vergi planlaması ve sınır ötesi uyumluluk için sistematik yaklaşım',
    taxOptimizationJurisdictions: 'Önde Gelen Vergi Verimli Yargı Yetkileri',
    taxOptimizationJurisdictionsDesc: 'En cazip vergi optimizasyon fırsatları sunan önde gelen yargı yetkileri',
    taxOptimizationFAQ: 'Sık Sorulan Sorular',
    taxOptimizationFAQDesc: 'Uluslararası vergi planlaması ve optimizasyon stratejileri hakkında yaygın sorular',
    taxOptimizationCTA: 'Vergilerinizi Optimize Etmeye Hazır mısınız?',
    taxOptimizationCTADesc: 'Küresel operasyonlarınıza özel uyumlu, verimli yapı tasarlayın',

    // Banking Solutions Page
    bankingSolutionsHeroTitle: 'Küresel Bankacılık Çözümleri – Güvenli, Uyumlu ve Verimli',
    bankingSolutionsHeroDesc: 'Dünya çapında premium kurumsal ve kişisel bankacılığa erişin. Consulting19 önde gelen finansal merkezlerle bağlantı kurmanıza yardımcı olur, uyumluluk, çok para birimli çözümler ve gelişmiş dijital bankacılık hizmetleri sağlar.',
    bankingSolutionsWhatWeOffer: 'Sunduklarımız',
    bankingSolutionsWhatWeOfferDesc: 'Uluslararası işletmeler ve bireyler için eksiksiz bankacılık çözümleri',
    bankingSolutionsProcess: 'Bankacılık Sürecimiz',
    bankingSolutionsProcessDesc: 'Dünyanın önde gelen bankalarında hesap açmak için akıcı süreç',
    bankingSolutionsJurisdictions: 'Önde Gelen Bankacılık Yargı Yetkileri',
    bankingSolutionsJurisdictionsDesc: 'Önde gelen finansal merkezlerde dünya standartlarında bankacılık hizmetlerine erişim',
    bankingSolutionsCTA: 'Küresel Bankacılığa Erişmeye Hazır mısınız?',
    bankingSolutionsCTADesc: 'Uzman rehberliğimiz aracılığıyla premium bankacılık çözümlerine bağlanın',
    companyFormationWhatWeOffer: 'Kapsamlı Şirket Kuruluş Hizmetleri',
    companyFormationWhatWeOfferDesc: 'AI destekli yargı analizi ve yerel uzman desteği ile uçtan uca iş kurulum çözümleri',
    companyFormationWhyChoose: 'Şirket Kuruluşu için Neden Consulting19\'u Seçmelisiniz?',
    companyFormationWhyChooseDesc: 'Küresel uzmanlığı yerel bilgi ve AI otomasyonu ile birleştirerek sorunsuz iş kurulumu',
    companyFormationHowItWorks: 'Küresel Şirket Kuruluşumuz Nasıl Çalışır',
    companyFormationHowItWorksDesc: 'Yargı seçiminden operasyonel iş kurulumuna kadar basit 4 adımlı süreç',
    companyFormationBestJurisdictions: 'Hızlı Şirket Kaydı için En İyi Yargı Yetkileri',
    companyFormationBestJurisdictionsDesc: 'İş dostu yargı yetkilerinde hızlı şirket kaydı',
    companyFormationFAQ: 'Sıkça Sorulan Sorular',
    companyFormationFAQDesc: 'Offshore kuruluş ve küresel iş kurulumu hakkında yaygın sorular',
    companyFormationCTA: 'Küresel Şirketinizi Kurmaya Hazır mısınız?',
    companyFormationCTADesc: 'Basit 3 adımlı sürecimizle iş kuruluş yolculuğunuza başlayın',

    // Legal Compliance Page
    legalComplianceHeroTitle: 'Hukuki Uyumluluk Hizmetleri',
    legalComplianceHeroDesc: 'Tüm yargı yetkilerinde tam hukuki uyumluluk sağlayın. Uzmanlarımız karmaşık düzenlemelerde gezinmenize, iyi durumunuzu korumanıza ve faaliyet gösterdiğiniz her ülkede denetime hazır olmanızı sağlar.',