import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'tr' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

// Comprehensive translations
const translations = {
  en: {
    // Navigation
    home: 'Home',
    services: 'Services',
    countries: 'Countries',
    about: 'About',
    blog: 'Blog',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    dashboard: 'Dashboard',
    
    // Hero Section
    heroTitle1: 'AI-Powered Global Business Consulting',
    heroSubtitle1: 'Expert Guidance Worldwide',
    heroDescription1: 'Connect with expert advisors in 19+ countries for seamless international business expansion, tax optimization, and legal compliance.',
    heroPrimaryCTA1: 'Start Your Expansion',
    heroSecondaryCTA1: 'Explore Services',
    
    heroTitle2: 'Expand Your Business',
    heroSubtitle2: 'Globally with Confidence',
    heroDescription2: 'Our AI Oracle matches you with the perfect jurisdiction and expert advisor for your international business goals.',
    heroPrimaryCTA2: 'Get Started Today',
    heroSecondaryCTA2: 'View Countries',
    
    heroTitle3: 'Smart International',
    heroSubtitle3: 'Business Solutions',
    heroDescription3: 'From company formation to banking solutions, we provide comprehensive support for your global business journey.',
    heroPrimaryCTA3: 'Explore Solutions',
    heroSecondaryCTA3: 'Learn More',
    
    heroTitle4: 'Your Gateway to',
    heroSubtitle4: 'Global Markets',
    heroDescription4: 'Access premium jurisdictions with favorable tax structures and business-friendly regulations worldwide.',
    heroPrimaryCTA4: 'Start Journey',
    heroSecondaryCTA4: 'View Services',
    
    heroTitle5: 'Professional Business',
    heroSubtitle5: 'Formation Services',
    heroDescription5: 'Expert guidance for company formation, tax planning, and international compliance across multiple jurisdictions.',
    heroPrimaryCTA5: 'Get Expert Help',
    heroSecondaryCTA5: 'Explore Options',
    
    // AI Assistant
    aiPoweredIntelligence: 'AI-Powered Intelligence',
    aiOracleAssistant: 'AI Oracle Assistant',
    online: 'Online',
    aiAssistantGreeting: 'Hello! I\'m your AI Oracle assistant. I can help you with international business expansion. What type of business are you looking to establish?',
    aiAssistantQuick1: 'I want to start a tech company',
    aiAssistantQuick2: 'Looking for tax optimization',
    aiAssistantQuick3: 'Need EU market access',
    aiAssistantQuick4: 'Interested in crypto business',
    aiAssistantQuickStart: 'Quick start:',
    aiAssistantPlaceholder: 'Type your message...',
    send: 'Send',
    
    // Services
    companyFormation: 'Company Formation',
    taxOptimization: 'Tax Optimization',
    bankingSolutions: 'Banking Solutions',
    legalCompliance: 'Legal Compliance',
    assetProtection: 'Asset Protection',
    investmentAdvisory: 'Investment Advisory',
    visaResidency: 'Visa & Residency',
    marketResearch: 'Market Research',
    
    // Service Titles and Descriptions
    companyFormationTitle: 'Company Formation',
    companyFormationDesc: 'End-to-end company registration and incorporation services',
    taxOptimizationTitle: 'Tax Optimization',
    taxOptimizationDesc: 'Strategic international tax planning and compliance',
    bankingSolutionsTitle: 'Banking Solutions',
    bankingSolutionsDesc: 'Global banking and payment processing solutions',
    legalComplianceTitle: 'Legal Compliance',
    legalComplianceDesc: 'Ongoing legal and regulatory compliance support',
    assetProtectionTitle: 'Asset Protection',
    assetProtectionDesc: 'Wealth protection and risk mitigation strategies',
    investmentAdvisoryTitle: 'Investment Advisory',
    investmentAdvisoryDesc: 'Professional investment management and advisory',

    // Company Formation Service Page
    companyFormationHeroTitle: 'Global Company Formation Services',
    companyFormationHeroDesc: 'Establish your business in 19+ countries with expert legal guidance and AI-powered process automation.',
    companyFormationWhatWeOffer: 'What We Offer',
    companyFormationWhatWeOfferDesc: 'End-to-end business setup solutions with AI-powered jurisdiction analysis',
    companyFormationService1Title: 'LLC & Corporation Formation',
    companyFormationService1Desc: 'Professional LLC and corporation formation services across multiple jurisdictions.',
    companyFormationService2Title: 'Offshore Company Registration',
    companyFormationService2Desc: 'Strategic offshore incorporation in business-friendly jurisdictions.',
    companyFormationService3Title: 'Jurisdiction Analysis',
    companyFormationService3Desc: 'AI-powered jurisdiction analysis across 19+ countries.',
    companyFormationService4Title: 'Digital Identity & e-Residency',
    companyFormationService4Desc: 'Complete digital identity solutions including Estonia e-Residency.',
    companyFormationService5Title: 'Banking & Payment Solutions',
    companyFormationService5Desc: 'Comprehensive corporate banking solutions worldwide.',
    companyFormationService6Title: 'Holding Company Structures',
    companyFormationService6Desc: 'Sophisticated holding company structures for asset protection.',
    companyFormationService7Title: 'Compliance Monitoring',
    companyFormationService7Desc: 'Automated compliance monitoring across all jurisdictions.',
    companyFormationService8Title: 'AI-Assistant Integration',
    companyFormationService8Desc: 'Intelligent AI assistant for automated document management.',
    companyFormationWhyChoose: 'Why Choose Consulting19?',
    companyFormationWhyChooseDesc: 'Combining global expertise with local knowledge and AI automation',
    companyFormationProcessStep1Title: 'Global + Local Expertise',
    companyFormationProcessStep1Desc: 'Local specialists in 19+ countries combined with AI-powered insights.',
    companyFormationProcessStep2Title: '500+ Successful Setups',
    companyFormationProcessStep2Desc: '98% success rate with over 500 companies formed.',
    companyFormationProcessStep3Title: 'AI-Powered Automation',
    companyFormationProcessStep3Desc: 'Smart document tracking and compliance automation.',
    companyFormationProcessStep4Title: 'Transparent & Cost-Effective',
    companyFormationProcessStep4Desc: 'Clear pricing with no hidden fees.',
    companyFormationHowItWorks: 'How It Works',
    companyFormationHowItWorksDesc: 'Simple 4-step process from jurisdiction selection to operational setup',
    companyFormationBestJurisdictions: 'Best Jurisdictions',
    companyFormationBestJurisdictionsDesc: 'Fast company registration in business-friendly jurisdictions',
    companyFormationFAQ: 'Frequently Asked Questions',
    companyFormationFAQDesc: 'Common questions about offshore incorporation and global business setup',
    companyFormationFAQ1Question: 'Is offshore company formation legal?',
    companyFormationFAQ1Answer: 'Yes, offshore incorporation is fully legal when structured within international compliance standards.',
    companyFormationFAQ2Question: 'What are the annual reporting requirements?',
    companyFormationFAQ2Answer: 'Annual reporting requirements vary significantly by jurisdiction and business structure.',
    companyFormationFAQ3Question: 'What banking options are available?',
    companyFormationFAQ3Answer: 'We provide access to corporate banking in major financial centers worldwide.',
    companyFormationFAQ4Question: 'What are the total costs for company formation?',
    companyFormationFAQ4Answer: 'Company formation costs vary by jurisdiction and services required.',
    companyFormationFAQ5Question: 'How long does the entire process take?',
    companyFormationFAQ5Answer: 'Fast company registration timelines depend on jurisdiction complexity.',
    companyFormationCTA: 'Ready to Start Your Company?',
    companyFormationCTADesc: 'Get started with expert guidance and AI-powered automation.',

    // Tax Optimization Service Page
    taxOptimizationHeroTitle: 'Tax Optimization Services',
    taxOptimizationHeroDesc: 'Leverage 19+ jurisdictions and AI-powered analysis to reduce tax burdens legally.',
    taxOptimizationWhatWeOffer: 'What We Offer',
    taxOptimizationWhatWeOfferDesc: 'Comprehensive tax optimization strategies for international businesses',
    taxOptimizationService1Title: 'International Tax Planning',
    taxOptimizationService1Desc: 'Strategic international tax planning that leverages global jurisdictions.',
    taxOptimizationService2Title: 'Transfer Pricing Strategies',
    taxOptimizationService2Desc: 'Advanced transfer pricing strategies for multinational enterprises.',
    taxOptimizationService3Title: 'Cross-Border Compliance',
    taxOptimizationService3Desc: 'Comprehensive cross-border taxation compliance services.',
    taxOptimizationService4Title: 'Holding & Group Structuring',
    taxOptimizationService4Desc: 'Sophisticated holding company structures for tax optimization.',
    taxOptimizationService5Title: 'IP & Royalty Planning',
    taxOptimizationService5Desc: 'Intellectual property and royalty planning strategies.',
    taxOptimizationService6Title: 'VAT/GST & Indirect Tax',
    taxOptimizationService6Desc: 'Comprehensive VAT/GST and indirect tax compliance services.',
    taxOptimizationService7Title: 'Permanent Establishment Review',
    taxOptimizationService7Desc: 'Professional permanent establishment risk assessment.',
    taxOptimizationService8Title: 'Residency & Treaty Benefits',
    taxOptimizationService8Desc: 'Strategic tax residency planning and treaty optimization.',
    taxOptimizationHowItWorks: 'How It Works',
    taxOptimizationHowItWorksDesc: 'Systematic approach to international tax planning',
    taxOptimizationStep1Title: 'Discovery & Risk Assessment',
    taxOptimizationStep1Desc: 'Map your business model and exposure points across jurisdictions.',
    taxOptimizationStep2Title: 'Jurisdiction & Treaty Analysis',
    taxOptimizationStep2Desc: 'Evaluate double tax treaties and substance requirements.',
    taxOptimizationStep3Title: 'Implementation & Documentation',
    taxOptimizationStep3Desc: 'Set up compliant structures and transfer pricing policies.',
    taxOptimizationStep4Title: 'Monitoring & Reporting',
    taxOptimizationStep4Desc: 'Track rule changes and prepare audit-ready reports.',
    taxOptimizationJurisdictions: 'Premier Tax-Efficient Jurisdictions',
    taxOptimizationJurisdictionsDesc: 'Leading jurisdictions offering attractive tax optimization opportunities',
    taxOptimizationFAQ: 'Frequently Asked Questions',
    taxOptimizationFAQDesc: 'Common questions about international tax planning',
    taxOptimizationCTA: 'Ready to Optimize Your Taxes?',
    taxOptimizationCTADesc: 'Get started with expert tax optimization strategies.',

    // Asset Protection Service Page
    assetProtectionHeroTitle: 'Asset Protection Services',
    assetProtectionHeroDesc: 'Protect your wealth from legal risks, creditors, and political instability.',
    assetProtectionWhatWeOffer: 'What We Offer',
    assetProtectionWhatWeOfferDesc: 'Sophisticated asset protection strategies for high-net-worth individuals',
    assetProtectionService1Title: 'Offshore Trusts',
    assetProtectionService1Desc: 'Establish sophisticated offshore trust structures in premier jurisdictions.',
    assetProtectionService2Title: 'Private Foundations',
    assetProtectionService2Desc: 'Create private foundation structures for wealth preservation.',
    assetProtectionService3Title: 'Holding Companies',
    assetProtectionService3Desc: 'Design multi-layered holding company structures for asset isolation.',
    assetProtectionService4Title: 'Family Offices',
    assetProtectionService4Desc: 'Establish comprehensive family office structures for UHNW families.',
    assetProtectionService5Title: 'Succession Planning',
    assetProtectionService5Desc: 'Develop comprehensive succession planning strategies.',
    assetProtectionService6Title: 'Privacy Solutions',
    assetProtectionService6Desc: 'Implement advanced privacy solutions and confidentiality structures.',
    assetProtectionProcess: 'Our Asset Protection Process',
    assetProtectionProcessDesc: 'Comprehensive approach to protecting your wealth and assets',
    assetProtectionStep1Title: 'Asset Assessment',
    assetProtectionStep1Desc: 'Map your asset portfolio and legal risks across jurisdictions.',
    assetProtectionStep2Title: 'Protection Strategy',
    assetProtectionStep2Desc: 'Design trust, foundation, and holding structures.',
    assetProtectionStep3Title: 'Structure Implementation',
    assetProtectionStep3Desc: 'Establish entities and implement governance frameworks.',
    assetProtectionStep4Title: 'Ongoing Management',
    assetProtectionStep4Desc: 'Handle filings, renewals, and compliance monitoring.',
    assetProtectionJurisdictions: 'Premier Asset Protection Jurisdictions',
    assetProtectionJurisdictionsDesc: 'Countries offering the strongest asset protection laws',
    assetProtectionFAQ: 'Frequently Asked Questions',
    assetProtectionFAQDesc: 'Common questions about asset protection strategies',
    assetProtectionCTA: 'Ready to Protect Your Assets?',
    assetProtectionCTADesc: 'Get started with comprehensive asset protection strategies.',

    // Banking Solutions Service Page
    bankingSolutionsHeroTitle: 'Global Banking Solutions',
    bankingSolutionsHeroDesc: 'Access premium corporate and personal banking worldwide.',
    bankingSolutionsWhatWeOffer: 'What We Offer',
    bankingSolutionsWhatWeOfferDesc: 'Complete banking solutions for international businesses',
    bankingSolutionsService1Title: 'Corporate Account Opening',
    bankingSolutionsService1Desc: 'Professional corporate account opening services worldwide.',
    bankingSolutionsService2Title: 'Multi-Currency Accounts',
    bankingSolutionsService2Desc: 'Advanced multi-currency banking solutions for global operations.',
    bankingSolutionsService3Title: 'Private Banking',
    bankingSolutionsService3Desc: 'Exclusive private banking services for high-net-worth individuals.',
    bankingSolutionsService4Title: 'Trade Finance',
    bankingSolutionsService4Desc: 'Comprehensive trade finance solutions including letters of credit.',
    bankingSolutionsService5Title: 'Digital Banking Solutions',
    bankingSolutionsService5Desc: 'Cutting-edge digital banking solutions for modern businesses.',
    bankingSolutionsService6Title: 'Investment Banking',
    bankingSolutionsService6Desc: 'Professional investment banking services including capital raising.',
    bankingSolutionsProcess: 'Our Banking Process',
    bankingSolutionsProcessDesc: 'Streamlined process to open accounts in leading banks',
    bankingSolutionsStep1Title: 'Banking Requirements Analysis',
    bankingSolutionsStep1Desc: 'Identify your business needs and compliance obligations.',
    bankingSolutionsStep2Title: 'Bank Selection',
    bankingSolutionsStep2Desc: 'Choose the optimal bank based on your operational model.',
    bankingSolutionsStep3Title: 'Account Opening',
    bankingSolutionsStep3Desc: 'Streamline documentation and due diligence processes.',
    bankingSolutionsStep4Title: 'Banking Setup',
    bankingSolutionsStep4Desc: 'Enable online banking and payment systems.',
    bankingSolutionsJurisdictions: 'Premier Banking Jurisdictions',
    bankingSolutionsJurisdictionsDesc: 'Access world-class banking services in leading financial centers',
    bankingSolutionsCTA: 'Ready to Access Global Banking?',
    bankingSolutionsCTADesc: 'Get started with comprehensive banking solutions.',

    // Legal Compliance Service Page
    legalComplianceHeroTitle: 'Legal Compliance Services',
    legalComplianceHeroDesc: 'Ensure full legal compliance across all jurisdictions.',
    legalComplianceWhatWeOffer: 'What We Offer',
    legalComplianceWhatWeOfferDesc: 'Comprehensive legal compliance services for international businesses',
    legalComplianceService1Title: 'Corporate Governance',
    legalComplianceService1Desc: 'Establish robust corporate governance frameworks.',
    legalComplianceService2Title: 'Regulatory Compliance',
    legalComplianceService2Desc: 'Navigate industry-specific regulatory requirements.',
    legalComplianceService3Title: 'Data Protection Compliance',
    legalComplianceService3Desc: 'Achieve full GDPR compliance and data privacy regulation.',
    legalComplianceService4Title: 'Anti-Money Laundering (AML/KYC)',
    legalComplianceService4Desc: 'Implement comprehensive AML KYC procedures.',
    legalComplianceService5Title: 'Contract Management',
    legalComplianceService5Desc: 'Professional legal contract drafting and management.',
    legalComplianceService6Title: 'Intellectual Property Protection',
    legalComplianceService6Desc: 'Comprehensive intellectual property protection strategies.',
    legalComplianceProcess: 'Our Legal Compliance Process',
    legalComplianceProcessDesc: 'Systematic approach to ensuring comprehensive legal compliance',
    legalComplianceStep1Title: 'Compliance Assessment',
    legalComplianceStep1Desc: 'Evaluate your current status and risks across jurisdictions.',
    legalComplianceStep2Title: 'Regulatory Mapping',
    legalComplianceStep2Desc: 'Identify all applicable laws and obligations.',
    legalComplianceStep3Title: 'Implementation',
    legalComplianceStep3Desc: 'Deploy policies, procedures, and documentation systems.',
    legalComplianceStep4Title: 'Ongoing Monitoring',
    legalComplianceStep4Desc: 'Track regulatory changes and renewals.',
    legalComplianceJurisdictions: 'Leading Legal Jurisdictions',
    legalComplianceJurisdictionsDesc: 'Countries offering robust and business-friendly legal frameworks',
    legalComplianceCTA: 'Ready to Ensure Compliance?',
    legalComplianceCTADesc: 'Get started with comprehensive legal compliance services.',

    // Investment Advisory Service Page
    investmentAdvisoryHeroTitle: 'Investment Advisory Services',
    investmentAdvisoryHeroDesc: 'Maximize long-term returns with disciplined, globally diversified strategies.',
    investmentAdvisoryWhatWeOffer: 'What We Offer',
    investmentAdvisoryWhatWeOfferDesc: 'Professional investment advisory services for sophisticated investors',
    investmentAdvisoryService1Title: 'Portfolio Management',
    investmentAdvisoryService1Desc: 'Professional portfolio management with global diversification.',
    investmentAdvisoryService2Title: 'Alternative Investments',
    investmentAdvisoryService2Desc: 'Exclusive access to alternative investments including private equity.',
    investmentAdvisoryService3Title: 'Real Estate Investment',
    investmentAdvisoryService3Desc: 'International real estate investment opportunities.',
    investmentAdvisoryService4Title: 'Cryptocurrency Advisory',
    investmentAdvisoryService4Desc: 'Professional cryptocurrency advisory with regulatory compliance.',
    investmentAdvisoryService5Title: 'ESG Investing',
    investmentAdvisoryService5Desc: 'Environmental, social, and governance focused investment strategies.',
    investmentAdvisoryService6Title: 'Wealth Planning',
    investmentAdvisoryService6Desc: 'Comprehensive wealth planning including estate planning.',
    investmentAdvisoryProcess: 'Our Investment Process',
    investmentAdvisoryProcessDesc: 'Systematic approach to building and managing your portfolio',
    investmentAdvisoryStep1Title: 'Portfolio Analysis',
    investmentAdvisoryStep1Desc: 'Assess objectives, constraints, and current exposures.',
    investmentAdvisoryStep2Title: 'Strategy Development',
    investmentAdvisoryStep2Desc: 'Design a policy portfolio with risk budgets.',
    investmentAdvisoryStep3Title: 'Implementation',
    investmentAdvisoryStep3Desc: 'Execute across vetted managers and platforms.',
    investmentAdvisoryStep4Title: 'Performance Monitoring',
    investmentAdvisoryStep4Desc: 'Ongoing reporting and quarterly reviews.',
    investmentAdvisoryJurisdictions: 'Premier Investment Jurisdictions',
    investmentAdvisoryJurisdictionsDesc: 'Leading financial centers for investment management',
    investmentAdvisoryFAQ: 'Frequently Asked Questions',
    investmentAdvisoryFAQDesc: 'Common questions about investment advisory services',
    investmentAdvisoryCTA: 'Ready to Grow Your Wealth?',
    investmentAdvisoryCTADesc: 'Get started with professional investment advisory services.',

    // Visa & Residency Service Page
    visaResidencyHeroTitle: 'Visa & Residency Services',
    visaResidencyHeroDesc: 'Secure residency or citizenship in your preferred country.',
    visaResidencyWhatWeOffer: 'What We Offer',
    visaResidencyWhatWeOfferDesc: 'Comprehensive visa and residency services for global mobility',
    visaResidencyService1Title: 'Golden Visa Programs',
    visaResidencyService1Desc: 'Investment-based residency programs offering pathways to EU mobility.',
    visaResidencyService2Title: 'Investor Visas',
    visaResidencyService2Desc: 'Entrepreneur and business investor visa routes.',
    visaResidencyService3Title: 'Citizenship by Investment',
    visaResidencyService3Desc: 'Fast-track citizenship programs through approved investment routes.',
    visaResidencyService4Title: 'Skilled Worker Visas',
    visaResidencyService4Desc: 'Employment-based visa programs for professionals.',
    visaResidencyService5Title: 'Family Reunification',
    visaResidencyService5Desc: 'Comprehensive family visa services for relatives.',
    visaResidencyService6Title: 'Permanent Residency',
    visaResidencyService6Desc: 'Long-term settlement pathways leading to permanent residency.',
    visaResidencyProcess: 'Our Visa & Residency Process',
    visaResidencyProcessDesc: 'Step-by-step guidance through visa applications',
    visaResidencyStep1Title: 'Eligibility Assessment',
    visaResidencyStep1Desc: 'Assess your profile against program criteria.',
    visaResidencyStep2Title: 'Program Selection',
    visaResidencyStep2Desc: 'Compare countries and routes for your goals.',
    visaResidencyStep3Title: 'Application Preparation',
    visaResidencyStep3Desc: 'Gather documents and compliant investment proofs.',
    visaResidencyStep4Title: 'Approval & Settlement',
    visaResidencyStep4Desc: 'Liaise with authorities and assist with landing.',
    visaResidencyDestinations: 'Popular Residency Destinations',
    visaResidencyDestinationsDesc: 'Countries offering attractive visa and residency programs',
    visaResidencyFAQ: 'Frequently Asked Questions',
    visaResidencyFAQDesc: 'Common questions about visa services and residency programs',
    visaResidencyCTA: 'Ready to Secure Your Residency?',
    visaResidencyCTADesc: 'Get started with comprehensive visa and residency services.',

    // Market Research Service Page
    marketResearchService1Title: 'Market Entry Analysis',
    marketResearchService1Desc: 'Comprehensive market entry strategies with demand sizing.',
    marketResearchService2Title: 'Competitor Intelligence',
    marketResearchService2Desc: 'Strategic competitor analysis covering competitive strategy.',
    marketResearchService3Title: 'Consumer Research',
    marketResearchService3Desc: 'Advanced consumer insights using quantitative research methods.',
    marketResearchService4Title: 'Industry Reports',
    marketResearchService4Desc: 'Comprehensive industry analysis including TAM and SAM calculations.',
    marketResearchService5Title: 'Regulatory Research',
    marketResearchService5Desc: 'Detailed regulatory landscape analysis covering compliance requirements.',
    marketResearchService6Title: 'Partnership Opportunities',
    marketResearchService6Desc: 'Strategic partnership identification services.',
    marketResearchStep1Title: 'Market Analysis',
    marketResearchStep1Desc: 'Define objectives and collect primary/secondary data.',
    marketResearchStep2Title: 'Competitive Research',
    marketResearchStep2Desc: 'Map players, offerings, and positioning.',
    marketResearchStep3Title: 'Strategy Development',
    marketResearchStep3Desc: 'Translate findings into entry strategy.',
    marketResearchStep4Title: 'Implementation Support',
    marketResearchStep4Desc: 'Assist with partner outreach and pilots.',
    visaResidencyTitle: 'Visa & Residency',
    visaResidencyDesc: 'Immigration and residency solutions worldwide',
    marketResearchTitle: 'Market Research',
    marketResearchDesc: 'Market analysis and business intelligence services',
    
    // Countries page
    countriesHeroTitle: 'Explore Business-Friendly Countries',
    countriesHeroDescription: 'Discover the best jurisdictions for your international business expansion with expert local guidance.',
    availableDestinations: 'Available Destinations',
    noCountriesFoundTitle: 'No Countries Found',
    noCountriesFoundDesc: 'Try adjusting your search or filter criteria.',
    searchPlaceholder: 'Search countries...',
    allRegions: 'All Regions',
    regionEurope: 'Europe',
    regionAsia: 'Asia',
    regionMiddleEast: 'Middle East',
    regionAmericas: 'Americas',
    featuredBadge: 'Featured',
    corporateTax: 'Corporate Tax',
    learnMoreBtn: 'Learn More',
    
    // Countries
    unitedArabEmirates: 'United Arab Emirates',
    estonia: 'Estonia',
    georgia: 'Georgia',
    malta: 'Malta',
    panama: 'Panama',
    portugal: 'Portugal',
    unitedStates: 'United States',
    switzerland: 'Switzerland',
    
    // Country highlights
    uaeHighlight: '0% corporate tax for 50 years in free zones',
    estoniaHighlight: '100% online e-Residency program',
    georgiaHighlight: 'Small Business Status - 1% tax',
    maltaHighlight: 'EU membership with 5% effective tax rate',
    panamaHighlight: 'Territorial tax system',
    portugalHighlight: 'Golden Visa program with EU residency',
    usaHighlight: 'World\'s largest economy and market',
    switzerlandHighlight: 'Political stability and banking excellence',
    
    // Country advantages
    noPersonalIncomeTax: 'No personal income tax',
    strategicLocation: 'Strategic location',
    modernInfrastructure: 'Modern infrastructure',
    businessFriendlyRegulations: 'Business-friendly regulations',
    digitalFirstApproach: 'Digital-first approach',
    euMarketAccess: 'EU market access',
    lowBureaucracy: 'Low bureaucracy',
    innovationFriendly: 'Innovation-friendly',
    simpleIncorporation: 'Simple incorporation',
    veryLowTaxes: 'Very low taxes',
    fastSetup: 'Fast setup',
    blockchainFriendly: 'Blockchain-friendly',
    englishSpeaking: 'English-speaking',
    strategicMediterraneanLocation: 'Strategic Mediterranean location',
    territorialTaxation: 'Territorial taxation',
    strongBankingPrivacy: 'Strong banking privacy',
    usDollarEconomy: 'US dollar economy',
    internationalBusinessHub: 'International business hub',
    nhrTaxProgram: 'NHR tax program',
    investmentImmigration: 'Investment immigration',
    strategicAtlanticLocation: 'Strategic Atlantic location',
    largestConsumerMarket: 'Largest consumer market',
    advancedInfrastructure: 'Advanced infrastructure',
    innovationHub: 'Innovation hub',
    strongLegalSystem: 'Strong legal system',
    politicalStability: 'Political stability',
    worldClassBanking: 'World-class banking',
    strategicEuLocation: 'Strategic EU location',
    
    // Regions
    allRegions: 'All Regions',
    regionEurope: 'Europe',
    regionAsia: 'Asia',
    regionMiddleEast: 'Middle East',
    regionAmericas: 'Americas',
    
    // Common
    learnMore: 'Learn More',
    getStarted: 'Get Started',
    viewAllServices: 'View All Services',
    viewAllCountries: 'View All Countries',
    scheduleConsultation: 'Schedule Consultation',
    corporateTax: 'Corporate Tax',
    featuredBadge: 'Featured',
    searchPlaceholder: 'Search countries...',
    availableDestinations: 'Available Destinations',
    noCountriesFoundTitle: 'No countries found',
    noCountriesFoundDesc: 'Try adjusting your search criteria',
    learnMoreBtn: 'Learn More',
    
    // How It Works
    step1Title: 'Discover Your Needs',
    step1Description: 'Our AI Oracle analyzes your business goals and recommends optimal jurisdictions',
    step2Title: 'AI-Powered Matching',
    step2Description: 'Get matched with expert advisors who specialize in your target countries',
    step3Title: 'Expert Consultation',
    step3Description: 'Work directly with local specialists for personalized guidance and support',
    step4Title: 'Global Expansion',
    step4Description: 'Launch your international business with complete legal and operational support',
    
    // AI Promotion
    aiPromotionTitle: 'Experience the Future of International Business Consulting',
    aiPromotionDescription: 'Our AI Oracle provides instant jurisdiction recommendations and expert matching.',
    instantJurisdictionRecommendations: 'Instant jurisdiction recommendations',
    aiPoweredExpertMatching: 'AI-powered expert matching',
    personalizedBusinessStrategies: 'Personalized business strategies',
    tryAiAssistantFree: 'Try AI Assistant Free',
    startConsultation: 'Start Consultation',
    
    // Real-time Analytics
    activeConsultations: 'Active Consultations',
    strategicJurisdictions: 'Strategic Jurisdictions',
    successRate: 'Success Rate',
    avgResponseTime: 'Avg Response Time',
    aiPoweredMatching: 'AI-Powered Matching',
    aiMatchingDescription: 'Smart consultant-client matching',
    legalCompliance: 'Legal Compliance',
    legalComplianceDescription: 'Automated compliance monitoring',
    successOptimization: 'Success Optimization',
    successOptimizationDescription: 'Data-driven success strategies',
    globalIntelligenceNetwork: 'Global Intelligence Network',
    realTimeAnalyticsTitle: 'Real-Time Global Business Intelligence',
    realTimeAnalyticsDescription: 'Live insights from our global network of business advisors and AI-powered analytics.',
    joinThousandsTitle: 'Join Thousands of Successful Entrepreneurs',
    joinThousandsDescription: 'Start your international expansion journey today with expert guidance.',
    startYourJourney: 'Start Your Journey',
    
    // Services Overview
    endToEndSolutions: 'End-to-End Solutions',
    servicesOverviewTitle: 'Comprehensive International Business Services',
    servicesOverviewDescription: 'From company formation to ongoing compliance, we provide complete support for your global expansion.',
    viewAllServicesBtn: 'View All Services',
    
    // Featured Countries
    businessFriendlyJurisdictions: 'Business-Friendly Jurisdictions',
    featuredCountriesTitle: 'Premier Business Destinations',
    featuredCountriesDescription: 'Discover the world\'s most attractive jurisdictions for international business expansion.',
    exploreAllCountriesBtn: 'Explore All Countries',
    
    // How It Works
    aiPoweredProcess: 'AI-Powered Process',
    howItWorksTitle: 'How Our AI-Powered Platform Works',
    howItWorksDescription: 'Streamlined process combining artificial intelligence with expert human guidance.',
    experienceAiConsulting: 'Experience AI-Powered Consulting',
    
    // Blog
    blogNewsTitle: 'Latest Business Insights',
    viewAllPosts: 'View All Posts',
    
    // Footer
    copyright: '© 2025 Consulting19. All rights reserved.',
    powered: 'Powered by AI Oracle technology',
    
    // Company Formation CTA
    companyTitle: 'Company Formation',
    companySubtitle: 'Fast, compliant business setup worldwide',
    companyFeature1: 'AI-powered jurisdiction analysis',
    companyFeature2: 'Expert local guidance',
    companyFeature3: 'Complete banking integration',
    companyFeature4: 'Ongoing compliance support',
    companyCta: 'Start Company Formation',
    
    // Wealth Management CTA
    wealthTitle: 'Matrix — Private Wealth Platform',
    wealthSubtitle: 'AI-assisted global allocation for UHNW clients. Minimum: $5M.',
    wealthFeature1: 'AI-driven portfolio analysis',
    wealthFeature2: 'Global investment opportunities',
    wealthFeature3: 'Strict confidentiality protocols',
    wealthStat1: '$2.5B+ AUM',
    wealthStat2: '98% success',
    wealthCta: 'Explore Matrix Wealth',
    
    // AI Assistant Page
    aiAssistantPageTitle: 'AI Oracle Assistant',
    aiAssistantPageSubtitle: 'Get instant recommendations for your international business expansion',
    aiAssistantReadyTitle: 'Ready to Get Started?',
    aiAssistantReadyDesc: 'Create a free account to access our full platform and connect with expert advisors.',
    createFreeAccount: 'Create Free Account',
    
    // Common actions
    backToServices: 'Back to Services',
    chooseCountry: 'Choose Country',
    viewServices: 'View Services',
    
    // Company Formation Service Page
    companyFormationHeroTitle: 'Global Company Formation Services',
    companyFormationHeroDesc: 'Establish your business in 19+ countries with expert legal guidance and AI-powered process automation.',
    companyFormationWhatWeOffer: 'Comprehensive Company Formation Services',
    companyFormationWhatWeOfferDesc: 'End-to-end business setup solutions with AI-powered jurisdiction analysis and local expert support',
    companyFormationService1Title: 'LLC & Corporation Formation',
    companyFormationService1Desc: 'Professional LLC and corporation formation services across multiple jurisdictions.',
    companyFormationService2Title: 'Offshore Company Registration',
    companyFormationService2Desc: 'Strategic offshore incorporation in business-friendly jurisdictions.',
    companyFormationService3Title: 'Jurisdiction Analysis',
    companyFormationService3Desc: 'Advanced AI-powered jurisdiction analysis for optimal business setup.',
    companyFormationService4Title: 'Digital Identity & e-Residency',
    companyFormationService4Desc: 'Complete digital identity solutions including Estonia e-Residency program.',
    companyFormationService5Title: 'Banking & Payment Solutions',
    companyFormationService5Desc: 'Comprehensive corporate banking solutions and payment processing setup.',
    companyFormationService6Title: 'Holding Company Structures',
    companyFormationService6Desc: 'Sophisticated holding company structures for asset protection and tax optimization.',
    companyFormationService7Title: 'Compliance Monitoring',
    companyFormationService7Desc: 'Automated compliance monitoring services for ongoing regulatory requirements.',
    companyFormationService8Title: 'AI-Assistant Integration',
    companyFormationService8Desc: 'Intelligent AI assistant integration for automated document management.',
    companyFormationWhyChoose: 'Why Choose Consulting19 for Company Formation?',
    companyFormationWhyChooseDesc: 'Combining global expertise with local knowledge and AI automation',
    companyFormationProcessStep1Title: 'Global + Local Expertise',
    companyFormationProcessStep1Desc: 'Local specialists in 19+ countries combined with AI-powered global insights.',
    companyFormationProcessStep2Title: '500+ Successful Setups',
    companyFormationProcessStep2Desc: '98% success rate with over 500 companies formed across multiple jurisdictions.',
    companyFormationProcessStep3Title: 'AI-Powered Automation',
    companyFormationProcessStep3Desc: 'Smart document tracking, compliance deadlines, and automated progress updates.',
    companyFormationProcessStep4Title: 'Transparent & Cost-Effective',
    companyFormationProcessStep4Desc: 'Clear pricing with no hidden fees and competitive rates for premium services.',
    companyFormationHowItWorks: 'How Our Global Company Formation Works',
    companyFormationHowItWorksDesc: 'Simple 4-step process from jurisdiction selection to operational business setup',
    companyFormationBestJurisdictions: 'Best Jurisdictions for Fast Company Registration',
    companyFormationBestJurisdictionsDesc: 'Fast company registration in business-friendly jurisdictions',
    companyFormationFAQ: 'Frequently Asked Questions',
    companyFormationFAQDesc: 'Common questions about offshore incorporation and global business setup',
    companyFormationFAQ1Question: 'Is offshore company formation legal?',
    companyFormationFAQ1Answer: 'Yes, offshore incorporation is fully legal when structured within international compliance standards.',
    companyFormationFAQ2Question: 'What are the annual reporting requirements?',
    companyFormationFAQ2Answer: 'Annual reporting requirements vary significantly by jurisdiction and business structure.',
    companyFormationFAQ3Question: 'What banking options are available?',
    companyFormationFAQ3Answer: 'We provide access to corporate banking in major financial centers worldwide.',
    companyFormationFAQ4Question: 'What are the total costs for company formation?',
    companyFormationFAQ4Answer: 'Company formation costs vary by jurisdiction and services required.',
    companyFormationFAQ5Question: 'How long does the entire process take?',
    companyFormationFAQ5Answer: 'Fast company registration timelines depend on jurisdiction complexity.',
    companyFormationCTA: 'Ready to Start Your Company?',
    companyFormationCTADesc: 'Get started with expert guidance and AI-powered automation.',
    
    // Tax Optimization Service Page
    taxOptimizationHeroTitle: 'Tax Optimization Services',
    taxOptimizationHeroDesc: 'Leverage 19+ jurisdictions and AI-powered analysis to reduce tax burdens legally and transparently.',
    taxOptimizationWhatWeOffer: 'Comprehensive Tax Optimization Services',
    taxOptimizationWhatWeOfferDesc: 'Strategic international tax planning and cross-border compliance',
    taxOptimizationService1Title: 'International Tax Planning',
    taxOptimizationService1Desc: 'Strategic international tax planning that leverages global jurisdictions.',
    taxOptimizationService2Title: 'Transfer Pricing Strategies',
    taxOptimizationService2Desc: 'Advanced transfer pricing strategies for multinational enterprises.',
    taxOptimizationService3Title: 'Cross-Border Compliance',
    taxOptimizationService3Desc: 'Comprehensive cross-border taxation compliance services.',
    taxOptimizationService4Title: 'Holding & Group Structuring',
    taxOptimizationService4Desc: 'Sophisticated holding company structures for tax optimization.',
    taxOptimizationService5Title: 'IP & Royalty Planning',
    taxOptimizationService5Desc: 'Intellectual property and royalty planning strategies.',
    taxOptimizationService6Title: 'VAT/GST & Indirect Tax',
    taxOptimizationService6Desc: 'Comprehensive VAT/GST and indirect tax compliance services.',
    taxOptimizationService7Title: 'Permanent Establishment Review',
    taxOptimizationService7Desc: 'Professional permanent establishment risk assessment.',
    taxOptimizationService8Title: 'Residency & Treaty Benefits',
    taxOptimizationService8Desc: 'Strategic tax residency planning and treaty optimization.',
    taxOptimizationHowItWorks: 'How It Works',
    taxOptimizationHowItWorksDesc: 'Systematic approach to international tax planning',
    taxOptimizationStep1Title: 'Discovery & Risk Assessment',
    taxOptimizationStep1Desc: 'Map your business model, revenue flows, and exposure points.',
    taxOptimizationStep2Title: 'Jurisdiction & Treaty Analysis',
    taxOptimizationStep2Desc: 'Evaluate double tax treaties and substance requirements.',
    taxOptimizationStep3Title: 'Implementation & Documentation',
    taxOptimizationStep3Desc: 'Set up compliant structures and transfer pricing policies.',
    taxOptimizationStep4Title: 'Monitoring & Reporting',
    taxOptimizationStep4Desc: 'Track rule changes and prepare audit-ready reports.',
    taxOptimizationJurisdictions: 'Premier Tax-Efficient Jurisdictions',
    taxOptimizationJurisdictionsDesc: 'Leading jurisdictions offering attractive tax optimization opportunities',
    taxOptimizationFAQ: 'Frequently Asked Questions',
    taxOptimizationFAQDesc: 'Common questions about international tax planning',
    taxOptimizationCTA: 'Ready to Optimize Your Taxes?',
    taxOptimizationCTADesc: 'Get started with strategic tax planning today.',
    
    // Asset Protection Service Page
    assetProtectionHeroTitle: 'Asset Protection Services',
    assetProtectionHeroDesc: 'Protect your wealth from legal risks, creditors, and political instability.',
    assetProtectionWhatWeOffer: 'Comprehensive Asset Protection Services',
    assetProtectionWhatWeOfferDesc: 'Sophisticated asset protection strategies for high-net-worth individuals',
    assetProtectionService1Title: 'Offshore Trusts',
    assetProtectionService1Desc: 'Establish sophisticated offshore trust structures in premier jurisdictions.',
    assetProtectionService2Title: 'Private Foundations',
    assetProtectionService2Desc: 'Create private foundation structures for wealth preservation.',
    assetProtectionService3Title: 'Holding Companies',
    assetProtectionService3Desc: 'Design multi-layered holding company structures for asset isolation.',
    assetProtectionService4Title: 'Family Offices',
    assetProtectionService4Desc: 'Establish comprehensive family office structures for wealth management.',
    assetProtectionService5Title: 'Succession Planning',
    assetProtectionService5Desc: 'Develop comprehensive succession planning strategies.',
    assetProtectionService6Title: 'Privacy Solutions',
    assetProtectionService6Desc: 'Implement advanced privacy solutions and confidentiality structures.',
    assetProtectionProcess: 'Our Asset Protection Process',
    assetProtectionProcessDesc: 'Comprehensive approach to protecting your wealth and assets',
    assetProtectionStep1Title: 'Asset Assessment',
    assetProtectionStep1Desc: 'Map your asset portfolio, legal risks, and exposure points.',
    assetProtectionStep2Title: 'Protection Strategy',
    assetProtectionStep2Desc: 'Design trust, foundation, and holding structures.',
    assetProtectionStep3Title: 'Structure Implementation',
    assetProtectionStep3Desc: 'Establish entities and implement governance frameworks.',
    assetProtectionStep4Title: 'Ongoing Management',
    assetProtectionStep4Desc: 'Handle filings, renewals, and compliance monitoring.',
    assetProtectionJurisdictions: 'Premier Asset Protection Jurisdictions',
    assetProtectionJurisdictionsDesc: 'Countries offering the strongest asset protection laws',
    assetProtectionFAQ: 'Frequently Asked Questions',
    assetProtectionFAQDesc: 'Common questions about asset protection strategies',
    assetProtectionCTA: 'Ready to Protect Your Assets?',
    assetProtectionCTADesc: 'Get started with professional asset protection today.',
    
    // Banking Solutions Service Page
    bankingSolutionsHeroTitle: 'Global Banking Solutions',
    bankingSolutionsHeroDesc: 'Access premium corporate and personal banking worldwide.',
    bankingSolutionsWhatWeOffer: 'Comprehensive Banking Services',
    bankingSolutionsWhatWeOfferDesc: 'Complete banking solutions for international businesses',
    bankingSolutionsService1Title: 'Corporate Account Opening',
    bankingSolutionsService1Desc: 'Professional corporate account opening services worldwide.',
    bankingSolutionsService2Title: 'Multi-Currency Accounts',
    bankingSolutionsService2Desc: 'Advanced multi-currency banking solutions.',
    bankingSolutionsService3Title: 'Private Banking',
    bankingSolutionsService3Desc: 'Exclusive private banking services for high-net-worth individuals.',
    bankingSolutionsService4Title: 'Trade Finance',
    bankingSolutionsService4Desc: 'Comprehensive trade finance solutions.',
    bankingSolutionsService5Title: 'Digital Banking Solutions',
    bankingSolutionsService5Desc: 'Cutting-edge digital banking solutions.',
    bankingSolutionsService6Title: 'Investment Banking',
    bankingSolutionsService6Desc: 'Professional investment banking services.',
    bankingSolutionsProcess: 'Our Banking Process',
    bankingSolutionsProcessDesc: 'Streamlined process to open accounts in leading banks',
    bankingSolutionsStep1Title: 'Banking Requirements Analysis',
    bankingSolutionsStep1Desc: 'Identify your business needs and compliance obligations.',
    bankingSolutionsStep2Title: 'Bank Selection',
    bankingSolutionsStep2Desc: 'Choose the optimal bank based on your requirements.',
    bankingSolutionsStep3Title: 'Account Opening',
    bankingSolutionsStep3Desc: 'Streamline documentation and due diligence processes.',
    bankingSolutionsStep4Title: 'Banking Setup',
    bankingSolutionsStep4Desc: 'Enable online banking and payment systems.',
    bankingSolutionsJurisdictions: 'Premier Banking Jurisdictions',
    bankingSolutionsJurisdictionsDesc: 'Access world-class banking services in leading financial centers',
    bankingSolutionsCTA: 'Ready to Access Global Banking?',
    bankingSolutionsCTADesc: 'Get started with professional banking solutions today.',
    
    // Legal Compliance Service Page
    legalComplianceHeroTitle: 'Legal Compliance Services',
    legalComplianceHeroDesc: 'Ensure full legal compliance across all jurisdictions.',
    legalComplianceWhatWeOffer: 'Comprehensive Legal Compliance Services',
    legalComplianceWhatWeOfferDesc: 'Complete legal compliance solutions for international businesses',
    legalComplianceService1Title: 'Corporate Governance',
    legalComplianceService1Desc: 'Establish robust corporate governance frameworks.',
    legalComplianceService2Title: 'Regulatory Compliance',
    legalComplianceService2Desc: 'Navigate industry-specific regulatory requirements.',
    legalComplianceService3Title: 'Data Protection Compliance',
    legalComplianceService3Desc: 'Achieve full GDPR compliance and data privacy regulation.',
    legalComplianceService4Title: 'Anti-Money Laundering (AML/KYC)',
    legalComplianceService4Desc: 'Implement comprehensive AML KYC procedures.',
    legalComplianceService5Title: 'Contract Management',
    legalComplianceService5Desc: 'Professional legal contract drafting and management.',
    legalComplianceService6Title: 'Intellectual Property Protection',
    legalComplianceService6Desc: 'Comprehensive intellectual property protection strategies.',
    legalComplianceProcess: 'Our Legal Compliance Process',
    legalComplianceProcessDesc: 'Systematic approach to ensuring comprehensive legal compliance',
    legalComplianceStep1Title: 'Compliance Assessment',
    legalComplianceStep1Desc: 'Evaluate your current status, risks, and gaps.',
    legalComplianceStep2Title: 'Regulatory Mapping',
    legalComplianceStep2Desc: 'Identify all applicable laws and obligations.',
    legalComplianceStep3Title: 'Implementation',
    legalComplianceStep3Desc: 'Deploy policies, procedures, and documentation systems.',
    legalComplianceStep4Title: 'Ongoing Monitoring',
    legalComplianceStep4Desc: 'Track regulatory changes and renewals.',
    legalComplianceJurisdictions: 'Leading Legal Jurisdictions',
    legalComplianceJurisdictionsDesc: 'Countries offering robust and business-friendly legal frameworks',
    legalComplianceCTA: 'Ready to Ensure Compliance?',
    legalComplianceCTADesc: 'Get started with comprehensive legal compliance today.',
    
    // Investment Advisory Service Page
    investmentAdvisoryHeroTitle: 'Investment Advisory Services',
    investmentAdvisoryHeroDesc: 'Maximize long-term returns with disciplined, globally diversified strategies.',
    investmentAdvisoryWhatWeOffer: 'Professional Investment Advisory Services',
    investmentAdvisoryWhatWeOfferDesc: 'Comprehensive investment advisory services for sophisticated investors',
    investmentAdvisoryService1Title: 'Portfolio Management',
    investmentAdvisoryService1Desc: 'Professional portfolio management services with global diversification.',
    investmentAdvisoryService2Title: 'Alternative Investments',
    investmentAdvisoryService2Desc: 'Exclusive access to alternative investments and institutional opportunities.',
    investmentAdvisoryService3Title: 'Real Estate Investment',
    investmentAdvisoryService3Desc: 'International real estate investment opportunities.',
    investmentAdvisoryService4Title: 'Cryptocurrency Advisory',
    investmentAdvisoryService4Desc: 'Professional cryptocurrency advisory services.',
    investmentAdvisoryService5Title: 'ESG Investing',
    investmentAdvisoryService5Desc: 'Environmental, social, and governance focused investment strategies.',
    investmentAdvisoryService6Title: 'Wealth Planning',
    investmentAdvisoryService6Desc: 'Comprehensive wealth planning and estate planning services.',
    investmentAdvisoryProcess: 'Our Investment Advisory Process',
    investmentAdvisoryProcessDesc: 'Systematic approach to building and managing your investment portfolio',
    investmentAdvisoryStep1Title: 'Portfolio Analysis',
    investmentAdvisoryStep1Desc: 'Assess objectives, constraints, and current exposures.',
    investmentAdvisoryStep2Title: 'Strategy Development',
    investmentAdvisoryStep2Desc: 'Design a policy portfolio with risk budgets and benchmarks.',
    investmentAdvisoryStep3Title: 'Implementation',
    investmentAdvisoryStep3Desc: 'Execute across vetted managers and platforms.',
    investmentAdvisoryStep4Title: 'Performance Monitoring',
    investmentAdvisoryStep4Desc: 'Ongoing reporting and quarterly reviews.',
    investmentAdvisoryJurisdictions: 'Premier Investment Jurisdictions',
    investmentAdvisoryJurisdictionsDesc: 'Leading financial centers for investment management',
    investmentAdvisoryFAQ: 'Frequently Asked Questions',
    investmentAdvisoryFAQDesc: 'Common questions about investment advisory services',
    investmentAdvisoryCTA: 'Ready to Grow Your Wealth?',
    investmentAdvisoryCTADesc: 'Get started with professional investment advisory today.',
    
    // Visa & Residency Service Page
    visaResidencyHeroTitle: 'Visa & Residency Services',
    visaResidencyHeroDesc: 'Secure residency or citizenship in your preferred country.',
    visaResidencyWhatWeOffer: 'Comprehensive Visa & Residency Services',
    visaResidencyWhatWeOfferDesc: 'Complete visa and residency solutions for global mobility',
    visaResidencyService1Title: 'Golden Visa Programs',
    visaResidencyService1Desc: 'Investment-based residency programs offering pathways to EU mobility.',
    visaResidencyService2Title: 'Investor Visas',
    visaResidencyService2Desc: 'Entrepreneur and business investor visa routes.',
    visaResidencyService3Title: 'Citizenship by Investment',
    visaResidencyService3Desc: 'Fast-track citizenship programs through approved investment routes.',
    visaResidencyService4Title: 'Skilled Worker Visas',
    visaResidencyService4Desc: 'Employment-based visa programs for professionals.',
    visaResidencyService5Title: 'Family Reunification',
    visaResidencyService5Desc: 'Comprehensive family visa services.',
    visaResidencyService6Title: 'Permanent Residency',
    visaResidencyService6Desc: 'Long-term settlement pathways to permanent residency.',
    visaResidencyProcess: 'Our Visa & Residency Process',
    visaResidencyProcessDesc: 'Step-by-step guidance through visa applications',
    visaResidencyStep1Title: 'Eligibility Assessment',
    visaResidencyStep1Desc: 'Assess your profile against program criteria.',
    visaResidencyStep2Title: 'Program Selection',
    visaResidencyStep2Desc: 'Compare countries and routes for your goals.',
    visaResidencyStep3Title: 'Application Preparation',
    visaResidencyStep3Desc: 'Gather documents and compliant investment proofs.',
    visaResidencyStep4Title: 'Approval & Settlement',
    visaResidencyStep4Desc: 'Liaise with authorities and assist with landing.',
    visaResidencyDestinations: 'Popular Residency Destinations',
    visaResidencyDestinationsDesc: 'Countries offering attractive visa and residency programs',
    visaResidencyFAQ: 'Frequently Asked Questions',
    visaResidencyFAQDesc: 'Common questions about visa services and residency programs',
    visaResidencyCTA: 'Ready to Secure Your Residency?',
    visaResidencyCTADesc: 'Get started with professional visa services today.',
    
    // Market Research Service Page
    marketResearchHeroTitle: 'Market Research Services',
    marketResearchHeroDesc: 'Make informed decisions with data-driven market intelligence.',
    marketResearchWhatWeOffer: 'Comprehensive Market Research Services',
    marketResearchWhatWeOfferDesc: 'Data-driven market research and business intelligence',
    marketResearchService1Title: 'Market Entry Analysis',
    marketResearchService1Desc: 'Comprehensive market entry strategies and analysis.',
    marketResearchService2Title: 'Competitor Intelligence',
    marketResearchService2Desc: 'Strategic competitor analysis and positioning.',
    marketResearchService3Title: 'Consumer Research',
    marketResearchService3Desc: 'Advanced consumer insights using research methods.',
    marketResearchService4Title: 'Industry Reports',
    marketResearchService4Desc: 'Comprehensive industry analysis and market sizing.',
    marketResearchService5Title: 'Regulatory Research',
    marketResearchService5Desc: 'Detailed regulatory landscape analysis.',
    marketResearchService6Title: 'Partnership Opportunities',
    marketResearchService6Desc: 'Strategic partnership identification services.',
    marketResearchProcess: 'Our Market Research Process',
    marketResearchProcessDesc: 'Systematic approach to understanding markets',
    marketResearchStep1Title: 'Market Analysis',
    marketResearchStep1Desc: 'Define objectives and collect market data.',
    marketResearchStep2Title: 'Competitive Research',
    marketResearchStep2Desc: 'Map players, offerings, and positioning.',
    marketResearchStep3Title: 'Strategy Development',
    marketResearchStep3Desc: 'Translate findings into entry strategy.',
    marketResearchStep4Title: 'Implementation Support',
    marketResearchStep4Desc: 'Assist with partner outreach and pilots.',
    marketResearchJurisdictions: 'Key Market Research Destinations',
    marketResearchJurisdictionsDesc: 'Leading markets with comprehensive research capabilities',
    marketResearchFAQ: 'Frequently Asked Questions',
    marketResearchFAQDesc: 'Common questions about market research services',
    marketResearchCTA: 'Ready to Research Your Market?',
    marketResearchCTADesc: 'Get comprehensive market intelligence today.',
  },
  tr: {
    // Navigation
    home: 'Ana Sayfa',
    services: 'Hizmetler',
    countries: 'Ülkeler',
    about: 'Hakkımızda',
    blog: 'Blog',
    contact: 'İletişim',
    login: 'Giriş',
    register: 'Kayıt',
    logout: 'Çıkış',
    dashboard: 'Panel',
    
    // Hero Section
    heroTitle1: 'AI Destekli Küresel İş Danışmanlığı',
    heroSubtitle1: 'Dünya Çapında Uzman Rehberlik',
    heroDescription1: '19+ ülkede uzman danışmanlarla sorunsuz uluslararası iş genişleme, vergi optimizasyonu ve yasal uyumluluk için bağlantı kurun.',
    heroPrimaryCTA1: 'Genişlemenizi Başlatın',
    heroSecondaryCTA1: 'Hizmetleri Keşfedin',
    
    heroTitle2: 'İşinizi Küresel',
    heroSubtitle2: 'Olarak Genişletin',
    heroDescription2: 'AI Oracle\'ımız sizi uluslararası iş hedefleriniz için mükemmel yargı yetkisi ve uzman danışmanla eşleştirir.',
    heroPrimaryCTA2: 'Bugün Başlayın',
    heroSecondaryCTA2: 'Ülkeleri Görüntüle',
    
    heroTitle3: 'Akıllı Uluslararası',
    heroSubtitle3: 'İş Çözümleri',
    heroDescription3: 'Şirket kuruluşundan bankacılık çözümlerine kadar küresel iş yolculuğunuz için kapsamlı destek sağlıyoruz.',
    heroPrimaryCTA3: 'Çözümleri Keşfet',
    heroSecondaryCTA3: 'Daha Fazla Öğren',
    
    heroTitle4: 'Küresel Pazarlara',
    heroSubtitle4: 'Açılan Kapınız',
    heroDescription4: 'Dünya çapında uygun vergi yapıları ve işletme dostu düzenlemelerle premium yargı yetkilerine erişin.',
    heroPrimaryCTA4: 'Yolculuğa Başla',
    heroSecondaryCTA4: 'Hizmetleri Görüntüle',
    
    heroTitle5: 'Profesyonel İş',
    heroSubtitle5: 'Kuruluş Hizmetleri',
    heroDescription5: 'Birden fazla yargı yetkisinde şirket kuruluşu, vergi planlaması ve uluslararası uyumluluk için uzman rehberlik.',
    heroPrimaryCTA5: 'Uzman Yardımı Al',
    heroSecondaryCTA5: 'Seçenekleri Keşfet',
    
    // AI Assistant
    aiPoweredIntelligence: 'AI Destekli Zeka',
    aiOracleAssistant: 'AI Oracle Asistan',
    online: 'Çevrimiçi',
    aiAssistantGreeting: 'Merhaba! Ben AI Oracle asistanınızım. Uluslararası iş genişlemeniz için size yardımcı olabilirim. Hangi tür bir iş kurmak istiyorsunuz?',
    aiAssistantQuick1: 'Teknoloji şirketi kurmak istiyorum',
    aiAssistantQuick2: 'Vergi optimizasyonu arıyorum',
    aiAssistantQuick3: 'AB pazarına erişim istiyorum',
    aiAssistantQuick4: 'Kripto işi yapmak istiyorum',
    aiAssistantQuickStart: 'Hızlı başlangıç:',
    aiAssistantPlaceholder: 'Mesajınızı yazın...',
    send: 'Gönder',
    
    // Services
    companyFormation: 'Şirket Kuruluşu',
    taxOptimization: 'Vergi Optimizasyonu',
    bankingSolutions: 'Bankacılık Çözümleri',
    legalCompliance: 'Yasal Uyumluluk',
    assetProtection: 'Varlık Koruması',
    investmentAdvisory: 'Yatırım Danışmanlığı',
    visaResidency: 'Vize ve İkamet',
    marketResearch: 'Pazar Araştırması',
    
    // Service Titles and Descriptions
    companyFormationTitle: 'Şirket Kuruluşu',
    companyFormationDesc: 'Uçtan uca şirket kayıt ve kuruluş hizmetleri',
    taxOptimizationTitle: 'Vergi Optimizasyonu',
    taxOptimizationDesc: 'Stratejik uluslararası vergi planlaması ve uyumluluk',
    bankingSolutionsTitle: 'Bankacılık Çözümleri',
    bankingSolutionsDesc: 'Küresel bankacılık ve ödeme işleme çözümleri',
    legalComplianceTitle: 'Yasal Uyumluluk',
    legalComplianceDesc: 'Sürekli yasal ve düzenleyici uyumluluk desteği',
    assetProtectionTitle: 'Varlık Koruması',
    assetProtectionDesc: 'Servet koruması ve risk azaltma stratejileri',
    investmentAdvisoryTitle: 'Yatırım Danışmanlığı',
    investmentAdvisoryDesc: 'Profesyonel yatırım yönetimi ve danışmanlık',
    visaResidencyTitle: 'Vize ve İkamet',
    visaResidencyDesc: 'Dünya çapında göçmenlik ve ikamet çözümleri',
    marketResearchTitle: 'Pazar Araştırması',
    marketResearchDesc: 'Pazar analizi ve iş zekası hizmetleri',
    
    // Countries page
    countriesHeroTitle: 'İş Dostu Ülkeleri Keşfedin',
    countriesHeroDescription: 'Uzman yerel rehberlik ile uluslararası iş genişlemeniz için en iyi yargı alanlarını keşfedin.',
    availableDestinations: 'Mevcut Destinasyonlar',
    noCountriesFoundTitle: 'Ülke Bulunamadı',
    noCountriesFoundDesc: 'Arama veya filtre kriterlerinizi ayarlamayı deneyin.',
    searchPlaceholder: 'Ülke ara...',
    allRegions: 'Tüm Bölgeler',
    regionEurope: 'Avrupa',
    regionAsia: 'Asya',
    regionMiddleEast: 'Orta Doğu',
    regionAmericas: 'Amerika',
    featuredBadge: 'Öne Çıkan',
    corporateTax: 'Kurumlar Vergisi',
    learnMoreBtn: 'Daha Fazla Bilgi',
    
    // Countries
    unitedArabEmirates: 'Birleşik Arap Emirlikleri',
    estonia: 'Estonya',
    georgia: 'Gürcistan',
    malta: 'Malta',
    panama: 'Panama',
    portugal: 'Portekiz',
    unitedStates: 'Amerika Birleşik Devletleri',
    switzerland: 'İsviçre',
    
    // Country highlights
    uaeHighlight: 'Serbest bölgelerde 50 yıl boyunca %0 kurumlar vergisi',
    estoniaHighlight: '%100 çevrimiçi e-Residency programı',
    georgiaHighlight: 'Küçük İşletme Statüsü - %1 vergi',
    maltaHighlight: '%5 efektif vergi oranıyla AB üyeliği',
    panamaHighlight: 'Bölgesel vergi sistemi',
    portugalHighlight: 'AB ikametiyle Altın Vize programı',
    usaHighlight: 'Dünyanın en büyük ekonomisi ve pazarı',
    switzerlandHighlight: 'Siyasi istikrar ve bankacılık mükemmelliği',
    
    // Country advantages
    noPersonalIncomeTax: 'Kişisel gelir vergisi yok',
    strategicLocation: 'Stratejik konum',
    modernInfrastructure: 'Modern altyapı',
    businessFriendlyRegulations: 'İş dostu düzenlemeler',
    digitalFirstApproach: 'Dijital öncelikli yaklaşım',
    euMarketAccess: 'AB pazar erişimi',
    lowBureaucracy: 'Düşük bürokrasi',
    innovationFriendly: 'İnovasyon dostu',
    simpleIncorporation: 'Basit kuruluş',
    veryLowTaxes: 'Çok düşük vergiler',
    fastSetup: 'Hızlı kurulum',
    blockchainFriendly: 'Blockchain dostu',
    englishSpeaking: 'İngilizce konuşulan',
    strategicMediterraneanLocation: 'Stratejik Akdeniz konumu',
    territorialTaxation: 'Bölgesel vergilendirme',
    strongBankingPrivacy: 'Güçlü bankacılık gizliliği',
    usDollarEconomy: 'ABD doları ekonomisi',
    internationalBusinessHub: 'Uluslararası iş merkezi',
    nhrTaxProgram: 'NHR vergi programı',
    investmentImmigration: 'Yatırım göçmenliği',
    strategicAtlanticLocation: 'Stratejik Atlantik konumu',
    largestConsumerMarket: 'En büyük tüketici pazarı',
    advancedInfrastructure: 'Gelişmiş altyapı',
    innovationHub: 'İnovasyon merkezi',
    strongLegalSystem: 'Güçlü hukuk sistemi',
    politicalStability: 'Siyasi istikrar',
    worldClassBanking: 'Dünya standartlarında bankacılık',
    strategicEuLocation: 'Stratejik AB konumu',
    
    // Regions
    allRegions: 'Tüm Bölgeler',
    regionEurope: 'Avrupa',
    regionAsia: 'Asya',
    regionMiddleEast: 'Orta Doğu',
    regionAmericas: 'Amerika',
    
    // Common
    learnMore: 'Daha Fazla Öğren',
    getStarted: 'Başlayın',
    viewAllServices: 'Tüm Hizmetleri Görüntüle',
    viewAllCountries: 'Tüm Ülkeleri Görüntüle',
    scheduleConsultation: 'Danışmanlık Planlayın',
    corporateTax: 'Kurumlar Vergisi',
    featuredBadge: 'Öne Çıkan',
    searchPlaceholder: 'Ülke ara...',
    availableDestinations: 'Mevcut Destinasyonlar',
    noCountriesFoundTitle: 'Ülke bulunamadı',
    noCountriesFoundDesc: 'Arama kriterlerinizi ayarlamayı deneyin',
    learnMoreBtn: 'Daha Fazla Öğren',
    
    // How It Works
    step1Title: 'İhtiyaçlarınızı Keşfedin',
    step1Description: 'AI Oracle\'ımız iş hedeflerinizi analiz eder ve optimal yargı yetkilerini önerir',
    step2Title: 'AI Destekli Eşleştirme',
    step2Description: 'Hedef ülkelerinizde uzmanlaşmış uzman danışmanlarla eşleşin',
    step3Title: 'Uzman Danışmanlığı',
    step3Description: 'Kişiselleştirilmiş rehberlik ve destek için yerel uzmanlarla doğrudan çalışın',
    step4Title: 'Küresel Genişleme',
    step4Description: 'Tam yasal ve operasyonel destekle uluslararası işinizi başlatın',
    
    // AI Promotion
    aiPromotionTitle: 'Uluslararası İş Danışmanlığının Geleceğini Deneyimleyin',
    aiPromotionDescription: 'AI Oracle\'ımız anında yargı yetkisi önerileri ve uzman eşleştirmesi sağlar.',
    instantJurisdictionRecommendations: 'Anında yargı yetkisi önerileri',
    aiPoweredExpertMatching: 'AI destekli uzman eşleştirmesi',
    personalizedBusinessStrategies: 'Kişiselleştirilmiş iş stratejileri',
    tryAiAssistantFree: 'AI Asistanı Ücretsiz Deneyin',
    startConsultation: 'Danışmanlığa Başla',
    
    // Real-time Analytics
    activeConsultations: 'Aktif Danışmanlıklar',
    strategicJurisdictions: 'Stratejik Yargı Yetkileri',
    successRate: 'Başarı Oranı',
    avgResponseTime: 'Ort. Yanıt Süresi',
    aiPoweredMatching: 'AI Destekli Eşleştirme',
    aiMatchingDescription: 'Akıllı danışman-müşteri eşleştirmesi',
    legalCompliance: 'Yasal Uyumluluk',
    legalComplianceDescription: 'Otomatik uyumluluk izleme',
    successOptimization: 'Başarı Optimizasyonu',
    successOptimizationDescription: 'Veri odaklı başarı stratejileri',
    globalIntelligenceNetwork: 'Küresel İstihbarat Ağı',
    realTimeAnalyticsTitle: 'Gerçek Zamanlı Küresel İş Zekası',
    realTimeAnalyticsDescription: 'Küresel iş danışmanları ağımızdan ve AI destekli analizlerden canlı içgörüler.',
    joinThousandsTitle: 'Binlerce Başarılı Girişimciye Katılın',
    joinThousandsDescription: 'Uzman rehberliğiyle uluslararası genişleme yolculuğunuza bugün başlayın.',
    startYourJourney: 'Yolculuğunuza Başlayın',
    
    // Services Overview
    endToEndSolutions: 'Uçtan Uca Çözümler',
    servicesOverviewTitle: 'Kapsamlı Uluslararası İş Hizmetleri',
    servicesOverviewDescription: 'Şirket kuruluşundan sürekli uyumluluğa kadar küresel genişlemeniz için tam destek sağlıyoruz.',
    viewAllServicesBtn: 'Tüm Hizmetleri Görüntüle',
    
    // Featured Countries
    businessFriendlyJurisdictions: 'İş Dostu Yargı Yetkileri',
    featuredCountriesTitle: 'Premier İş Destinasyonları',
    featuredCountriesDescription: 'Uluslararası iş genişlemesi için dünyanın en çekici yargı yetkilerini keşfedin.',
    exploreAllCountriesBtn: 'Tüm Ülkeleri Keşfet',
    
    // How It Works
    aiPoweredProcess: 'AI Destekli Süreç',
    howItWorksTitle: 'AI Destekli Platformumuz Nasıl Çalışır',
    howItWorksDescription: 'Yapay zeka ile uzman insan rehberliğini birleştiren akıcı süreç.',
    experienceAiConsulting: 'AI Destekli Danışmanlığı Deneyimleyin',
    
    // Blog
    blogNewsTitle: 'En Son İş İçgörüleri',
    viewAllPosts: 'Tüm Yazıları Görüntüle',
    
    // Footer
    copyright: '© 2025 Consulting19. Tüm hakları saklıdır.',
    powered: 'AI Oracle teknolojisi ile güçlendirilmiştir',
    
    // Company Formation CTA
    companyTitle: 'Şirket Kuruluşu',
    companySubtitle: 'Dünya çapında hızlı, uyumlu iş kurulumu',
    companyFeature1: 'AI destekli yargı yetkisi analizi',
    companyFeature2: 'Uzman yerel rehberlik',
    companyFeature3: 'Tam bankacılık entegrasyonu',
    companyFeature4: 'Sürekli uyumluluk desteği',
    companyCta: 'Şirket Kuruluşunu Başlat',
    
    // Wealth Management CTA
    wealthTitle: 'Matrix — Özel Servet Platformu',
    wealthSubtitle: 'Ultra yüksek net değerli müşteriler için gizlilik odaklı platform. Yapay zeka destekli küresel tahsis ve gizli çoklu yargı alanı bankacılığı.',
    wealthFeature1: 'Yapay zeka destekli analiz',
    wealthFeature2: 'Küresel fırsatlar',
    wealthFeature3: 'Sıkı gizlilik',
    wealthStat1: '$2.5B+ AUM',
    wealthStat2: '%98 başarı',
    wealthCta: 'Matrix Wealth\'i Keşfet',