import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'tr' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    home: 'Home',
    services: 'Services',
    countries: 'Countries',
    about: 'About',
    blog: 'Blog',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    dashboard: 'Dashboard',
    viewAllServices: 'View All Services',
    viewAllCountries: 'View All Countries',

    // Hero Section (HomePage)
    heroTitle: 'AI-Enhanced Global Intelligence',
    heroSubtitle: 'at Your Service',
    heroDescription: 'Next-level regulatory guidance with intelligent automation. Our AI-powered platform connects you with expert consultants across the world\'s most business-friendly jurisdictions.',
    getStarted: 'Get Started Today',
    exploreServices: 'Explore Services',

    // Company Formation CTA (HomePage)
    companyTitle: 'Company Formation',
    companySubtitle: 'Fast & reliable business setup worldwide',
    companyFeature1: 'Expert guidance',
    companyFeature2: 'Global network',
    companyFeature3: 'Compliance assured',
    companyFeature4: 'Professional support',
    companyCta: 'Start Company Formation',

    // Wealth Management CTA (HomePage)
    wealthTitle: 'Wealth Management',
    wealthSubtitle: 'AI-powered investment strategies for global wealth optimization',
    wealthFeature1: 'AI-driven analysis',
    wealthFeature2: 'Global opportunities',
    wealthFeature3: 'Unlimited potential',
    wealthStat1: '$2.5B+ Managed',
    wealthStat2: '98% Success Rate',
    wealthCta: 'Explore Wealth Solutions',

    // Footer
    copyright: '© 2025 Consulting19. All rights reserved',
    powered: 'Powered by AI Oracle',

    // Services Page
    servicesHeroTitle: 'Comprehensive International Business Services',
    servicesHeroDescription: 'From company formation to ongoing compliance, we provide end-to-end support delivered by expert consultants in over 19 countries worldwide.',
    
    // About Page - New Content
    aboutHeroTitle: 'About Consulting19',
    aboutHeroDescription: 'Since 2016, we\'ve been simplifying international expansion by combining AI-powered intelligence with a global network of expert advisors. We help founders and investors launch, bank, optimize taxes, and stay compliant across 19+ countries.',
    startYourExpansion: 'Start Your Expansion',
    exploreCountries: 'Explore Countries',
    
    missionTitle: 'Our Mission',
    missionDescription: 'To democratize international expansion by making expert guidance accessible, fast, and fairly priced. We deliver enterprise-grade outcomes for companies of all sizes through the practical blend of automation and local expertise.',
    
    valuesTitle: 'Our Values',
    valuesDescription: 'The principles that guide everything we do at Consulting19.',
    globalExpertise: 'Global Expertise',
    globalExpertiseDesc: 'On-the-ground knowledge across 19+ jurisdictions.',
    aiEfficiency: 'AI-Powered Efficiency',
    aiEfficiencyDesc: 'Faster analysis, fewer errors, better decisions.',
    trustSecurity: 'Trust & Security',
    trustSecurityDesc: 'Enterprise-grade security and data privacy.',
    resultsDriven: 'Results-Driven',
    resultsDrivenDesc: 'Measurable outcomes and clear accountability.',
    
    foundedTitle: 'Founded in 2016',
    founded2016: 'Founded',
    founded2016Desc: 'First cross-border formation projects completed.',
    founded2019: '10+ Countries',
    founded2019Desc: 'Scaled expert network; added banking & compliance.',
    founded2022: 'AI Assistant',
    founded2022Desc: 'Automated workflows for KYC, filings, and tax routing.',
    founded2025: 'Flagship Platforms',
    founded2025Desc: 'Matrix (UHNW) and FidelKey (Secured Title Investment) launched.',
    
    flagshipPlatformsTitle: 'Flagship Platforms',
    flagshipPlatformsDescription: 'Premium solutions for sophisticated clients and unique investment opportunities.',
    
    matrixBadge: 'Premium',
    matrixTitle: 'Matrix — Private Wealth Platform',
    matrixDescription: 'A privacy-first platform for ultra-high-net-worth clients. AI-assisted global allocation, multi-jurisdiction banking, and discreet execution. Minimum investment: $5M.',
    matrixFeature1: 'AI-driven analysis',
    matrixFeature2: 'Global opportunities',
    matrixFeature3: 'Strict confidentiality',
    matrixCTA: 'Explore Matrix Wealth',
    matrixNote: 'For qualified investors only.',
    
    fidelkeyBadge: 'Innovation',
    fidelkeyTitle: 'FidelKey — Secured Title Investment System',
    fidelkeyDescription: 'The world\'s first secured-title investment gateway combining real-estate ownership, financial returns, and international visa pathways under a collateralized title model.',
    fidelkeyFeature1: 'Secured title structure',
    fidelkeyFeature2: 'Residency options',
    fidelkeyFeature3: 'Rental/dividend yield potential',
    fidelkeyCTA: 'Explore FidelKey',
    
    storyTitle: 'Our Story',
    storyDescription: 'Consulting19 began in 2016 with a simple observation: cross-border expansion was harder than it needed to be. By pairing cutting-edge AI with a curated network of local experts, we deliver enterprise-level results—company formation, banking, tax optimization, and compliance—faster and more predictably than traditional models.',
    
    impactMetricsTitle: 'Impact Metrics',
    countriesSupported: 'Countries supported',
    companiesFormed: 'Companies formed & supported',
    successRate: 'Success rate (company setup)',
    avgSetupTime: 'Days average setup (selected jurisdictions)',
    
    finalCtaTitle: 'Ready to Join Our Mission?',
    finalCtaDescription: 'Whether you\'re expanding globally or advising clients, we\'d love to collaborate.',
    becomeConsultant: 'Become a Consultant',
    
    // Service Categories
    companyFormation: 'Company Formation',
    companyFormationDesc: 'Complete assistance in company registration and incorporation across business-friendly jurisdictions.',
    companyFormationService1: 'Company registration and incorporation',
    companyFormationService2: 'Business license applications',
    companyFormationService3: 'Corporate structure optimization',
    companyFormationService4: 'Registered agent services',
    companyFormationService5: 'Virtual office solutions',

    taxOptimization: 'Tax Optimization',
    taxOptimizationDesc: 'Strategic tax planning and optimization to minimize your international tax burden legally.',
    taxOptimizationService1: 'International tax planning',
    taxOptimizationService2: 'Double taxation treaty optimization',
    taxOptimizationService3: 'Tax residence strategies',
    taxOptimizationService4: 'Transfer pricing guidance',
    taxOptimizationService5: 'Annual tax compliance',

    bankingSolutions: 'Banking Solutions',
    bankingSolutionsDesc: 'Comprehensive banking support for international business operations.',
    bankingSolutionsService1: 'International bank account opening',
    bankingSolutionsService2: 'Multi-currency account setup',
    bankingSolutionsService3: 'Payment gateway integration',
    bankingSolutionsService4: 'Banking relationship management',
    bankingSolutionsService5: 'Trade finance solutions',

    legalCompliance: 'Legal Compliance',
    legalComplianceDesc: 'Ongoing legal and regulatory compliance support to keep your business compliant.',
    legalComplianceService1: 'Regulatory compliance monitoring',
    legalComplianceService2: 'Contract reviews and drafting',
    legalComplianceService3: 'Legal structure optimization',
    legalComplianceService4: 'Intellectual property protection',
    legalComplianceService5: 'Data protection compliance',

    assetProtection: 'Asset Protection',
    assetProtectionDesc: 'Advanced strategies to protect your assets and minimize risks in international operations.',
    assetProtectionService1: 'Asset protection strategies',
    assetProtectionService2: 'Trust and foundation setup',
    assetProtectionService3: 'Risk assessment and mitigation',
    assetProtectionService4: 'Estate planning for international assets',
    assetProtectionService5: 'Insurance optimization',

    investmentAdvisory: 'Investment Advisory',
    investmentAdvisoryDesc: 'Commercial investment consulting and growth strategies for international markets.',
    investmentAdvisoryService1: 'Market entry strategies',
    investmentAdvisoryService2: 'Investment structure optimization',
    investmentAdvisoryService3: 'Due diligence support',
    investmentAdvisoryService4: 'Exit strategy planning',
    investmentAdvisoryService5: 'Cross-border M&A advisory',

    exploreCategory: 'Explore',
    servicesCtaTitle: 'Need a Custom Solution?',
    servicesCtaDescription: 'Our expert advisors can create a tailored strategy for your unique business needs.',
    consultExpertBtn: 'Consult with Expert',
    exploreCountriesBtn: 'Explore Countries',

    // Countries Page
    countriesHeroTitle: 'Global Business Destinations',
    countriesHeroDescription: 'Explore the world\'s most business-friendly jurisdictions. Each location offers unique advantages for international expansion and tax optimization.',
    searchPlaceholder: 'Search countries...',
    allRegions: 'All Regions',
    regionEurope: 'Europe',
    regionAsia: 'Asia',
    regionMiddleEast: 'Middle East',
    regionAmericas: 'Americas',
    availableDestinations: 'Available Destinations',
    noCountriesFoundTitle: 'No countries found',
    noCountriesFoundDesc: 'Try adjusting your search or filter criteria.',
    corporateTax: 'Corporate Tax',
    featuredBadge: 'FEATURED',
    learnMoreBtn: 'Learn More',

    // About Page
    aboutHeroTitle: 'About Consulting19',
    aboutHeroDescription: 'We\'re revolutionizing international business consulting by combining AI-powered intelligence with a global network of expert advisors.',
    missionTitle: 'Our Mission',
    missionDesc1: 'To democratize international business expansion by making expert advice accessible, affordable, and instant through the power of artificial intelligence.',
    missionDesc2: 'We believe that every entrepreneur should have access to world-class international business guidance, regardless of their location or business size.',
    valuesTitle: 'Our Values',
    valuesDescription: 'The principles that guide everything we do at Consulting19.',
    globalExpertise: 'Global Expertise',
    globalExpertiseDesc: 'Deep knowledge of international business landscapes across 19+ countries.',
    aiEfficiency: 'AI-Powered Efficiency',
    aiEfficiencyDesc: 'Cutting-edge AI technology combined with human expertise for optimal results.',
    trustSecurity: 'Trust & Security',
    trustSecurityDesc: 'Enterprise-grade security protecting your sensitive business information.',
    resultsDriven: 'Results-Driven',
    resultsDrivenDesc: 'Focused on delivering measurable outcomes for your international expansion.',
    teamTitle: 'Meet Our Team',
    teamDescription: 'Experienced professionals from leading consulting firms and technology companies.',
    teamMemberRoleErdal: 'SEO & Digital Marketing Specialist',
    teamMemberBioErdal: 'Expert in search engine optimization and digital marketing strategies for international business expansion.',
    linkedinProfile: 'LinkedIn Profile',
    storyTitle: 'Our Story',
    storyDesc1: 'Consulting19 was born from a simple observation: international business expansion is unnecessarily complex and expensive. Traditional consulting firms charge premium rates while entrepreneurs struggle to navigate foreign regulations alone.',
    storyDesc2: 'By combining cutting-edge AI technology with a carefully curated network of expert advisors in business-friendly jurisdictions, we\'ve created a platform that delivers enterprise-level consulting at a fraction of traditional costs.',
    storyDesc3: 'Today, we\'re proud to serve hundreds of entrepreneurs worldwide, helping them save millions in taxes while expanding their businesses across borders with confidence.',
    ctaTitle: 'Ready to Join Our Mission?',
    ctaDescription: 'Whether you\'re an entrepreneur looking to expand globally or an expert advisor wanting to help others, we\'d love to have you on board.',
    startExpansionBtn: 'Start Your Expansion',
    becomeConsultantBtn: 'Become a Consultant',

    // Hero Section
    heroTitle1: 'AI-Enhanced Global Intelligence',
    heroSubtitle1: 'at Your Service',
    heroDescription1: 'Next-level regulatory guidance with intelligent automation. Our AI-powered platform connects you with expert consultants across the world\'s most business-friendly jurisdictions.',
    heroTitle2: 'Global Network of Experts',
    heroSubtitle2: 'in 19+ Countries',
    heroDescription2: 'Connect with certified business advisors and legal experts across strategic jurisdictions. From UAE to Estonia, our network ensures you get local expertise with global reach.',
    heroTitle3: 'Instant AI-Powered Matching',
    heroSubtitle3: 'Smart Matching for Your Needs',

    // Pricing Page
    pricingHeroTitle: 'Simple, Transparent Pricing',
    pricingHeroDescription: 'Choose the plan that fits your business needs. No hidden fees, no surprises.',
    pricingBasicPlan: 'Basic',
    pricingBasicPrice: 'Pay per service',
    pricingBasicDesc: 'Perfect for individual projects',
    pricingBasicFeature1: 'AI consultation',
    pricingBasicFeature2: 'Expert matching',
    pricingBasicFeature3: 'Basic support',
    pricingBasicFeature4: 'Document templates',
    pricingProfessionalPlan: 'Professional',
    pricingProfessionalPrice: '$299/month',
    pricingProfessionalDesc: 'For growing businesses',
    pricingProfessionalFeature1: 'Everything in Basic',
    pricingProfessionalFeature2: 'Priority support',
    pricingProfessionalFeature3: 'Multiple projects',
    pricingProfessionalFeature4: 'Advanced analytics',
    pricingProfessionalFeature5: 'Compliance monitoring',
    pricingEnterprisePlan: 'Enterprise',
    pricingEnterprisePrice: 'Custom',
    pricingEnterpriseDesc: 'For large organizations',
    pricingEnterpriseFeature1: 'Everything in Professional',
    pricingEnterpriseFeature2: 'Dedicated account manager',
    pricingEnterpriseFeature3: 'Custom integrations',
    pricingEnterpriseFeature4: 'SLA guarantees',
    pricingEnterpriseFeature5: 'White-label options',
    pricingPopularBadge: 'Most Popular',
    pricingGetStarted: 'Get Started',

    // Partners Page
    partnersHeroTitle: 'Partner with Consulting19',
    partnersHeroDescription: 'Join our global network of experts and help entrepreneurs expand internationally.',
    partnersTypesTitle: 'Partnership Opportunities',
    partnersTypesDescription: 'Multiple ways to collaborate and grow together',
    partnersConsultantTitle: 'Expert Consultants',
    partnersConsultantDesc: 'Join our network of business advisors',
    partnersConsultantBenefit1: 'Access to global client base',
    partnersConsultantBenefit2: '65% revenue share',
    partnersConsultantBenefit3: 'Marketing support',
    partnersConsultantBenefit4: 'Professional development',
    partnersReferralTitle: 'Referral Partners',
    partnersReferralDesc: 'Earn commissions by referring clients',
    partnersReferralBenefit1: 'Competitive commissions',
    partnersReferralBenefit2: 'Marketing materials',
    partnersReferralBenefit3: 'Tracking dashboard',
    partnersReferralBenefit4: 'Ongoing support',
    partnersIntegrationTitle: 'Technology Partners',
    partnersIntegrationDesc: 'Integrate with our platform',
    partnersIntegrationBenefit1: 'API access',
    partnersIntegrationBenefit2: 'Co-marketing opportunities',
    partnersIntegrationBenefit3: 'Technical support',
    partnersIntegrationBenefit4: 'Revenue sharing',
    partnersApplyNow: 'Apply Now',
    partnersFeaturedTitle: 'Featured Partners',
    partnersFeaturedDescription: 'Trusted partners helping us deliver exceptional service',
    partnersLawFirmDesc: 'International legal services',
    partnersBankingDesc: 'Corporate banking solutions',
    partnersTaxDesc: 'Tax optimization strategies',
    partnersCtaTitle: 'Ready to Partner with Us?',
    partnersCtaDescription: 'Join our mission to democratize international business expansion.',
    partnersJoinNetwork: 'Join Our Network',
    partnersLearnMore: 'Learn More',

    // Documentation Page
    docsHeroTitle: 'Documentation',
    docsHeroDescription: 'Everything you need to know about using Consulting19 platform and services.',
    docsSearchPlaceholder: 'Search documentation...',
    docsGettingStartedTitle: 'Getting Started',
    docsGettingStartedDesc: 'Quick start guides and tutorials',
    docsQuickStartTitle: 'Quick Start Guide',
    docsAccountSetupTitle: 'Account Setup',
    docsFirstProjectTitle: 'Your First Project',
    docsAPITitle: 'API Reference',
    docsAPIDesc: 'Complete API documentation',
    docsAPIReferenceTitle: 'API Reference',
    docsWebhooksTitle: 'Webhooks',
    docsSDKsTitle: 'SDKs & Libraries',
    docsGuidesTitle: 'Guides',
    docsGuidesDesc: 'Step-by-step guides',
    docsCompanyFormationTitle: 'Company Formation Guide',
    docsBankingTitle: 'Banking Setup Guide',
    docsTaxPlanningTitle: 'Tax Planning Guide',

    // Status Page
    statusHeroTitle: 'System Status',
    statusHeroDescription: 'Real-time status of all Consulting19 services and systems.',
    statusAllSystemsOperational: 'All Systems Operational',
    statusLastUpdated: 'Last updated',
    statusServicesTitle: 'Service Status',
    statusAPITitle: 'API Services',
    statusWebsiteTitle: 'Website',
    statusDatabaseTitle: 'Database',
    statusPaymentsTitle: 'Payment Processing',
    statusUptime: 'Uptime',
    statusResponseTime: 'Response Time',
    statusOperational: 'Operational',
    statusDegraded: 'Degraded',
    statusDown: 'Down',
    statusIncidentsTitle: 'Recent Incidents',
    statusIncident1Title: 'Brief API slowdown',
    statusIncident1Desc: 'Temporary performance degradation resolved',
    statusIncident2Title: 'Scheduled maintenance',
    statusIncident2Desc: 'Planned system updates completed',
    statusResolved: 'Resolved',
    statusDuration: 'Duration',
    statusNoIncidents: 'No recent incidents to report',

    // Cookie Policy Page
    cookiesHeroTitle: 'Cookie Policy',
    cookiesHeroDescription: 'Learn how we use cookies to improve your experience on our platform.',
    cookiesLastUpdated: 'Last updated',
    cookiesUpdateDate: 'January 2025',
    cookiesEssentialTitle: 'Essential Cookies',
    cookiesEssentialDesc: 'Required for basic functionality',
    cookiesEssentialExamples: 'Authentication, security, preferences',
    cookiesAnalyticsTitle: 'Analytics Cookies',
    cookiesAnalyticsDesc: 'Help us understand usage patterns',
    cookiesAnalyticsExamples: 'Google Analytics, performance metrics',
    cookiesSecurityTitle: 'Security Cookies',
    cookiesSecurityDesc: 'Protect against fraud and abuse',
    cookiesSecurityExamples: 'CSRF protection, session security',
    cookiesWhatAreTitle: 'What Are Cookies?',
    cookiesWhatAreDesc: 'Cookies are small text files stored on your device when you visit our website. They help us provide you with a better experience by remembering your preferences and analyzing how you use our services.',
    cookiesHowWeUseTitle: 'How We Use Cookies',
    cookiesHowWeUseDesc: 'We use cookies for several purposes:',
    cookiesUse1: 'Essential website functionality and security',
    cookiesUse2: 'Remembering your preferences and settings',
    cookiesUse3: 'Analyzing website performance and usage',
    cookiesUse4: 'Improving our services and user experience',
    cookiesTypesTitle: 'Types of Cookies We Use',
    cookiesEssentialFullDesc: 'These cookies are necessary for the website to function properly. They enable core functionality such as security, network management, and accessibility.',
    cookiesAnalyticsFullDesc: 'These cookies help us understand how visitors interact with our website by collecting and reporting information anonymously.',
    cookiesMarketingTitle: 'Marketing Cookies',
    cookiesMarketingFullDesc: 'These cookies are used to deliver relevant advertisements and track the effectiveness of our marketing campaigns.',
    cookiesControlTitle: 'Managing Your Cookie Preferences',
    cookiesControlDesc: 'You can control and manage cookies through your browser settings. However, disabling certain cookies may affect the functionality of our website.',
    cookiesContactTitle: 'Contact Us',
    cookiesContactDesc: 'If you have questions about our cookie policy, please contact us:',
    cookiesContactEmail: 'Email',

    // Compliance Page
    complianceHeroTitle: 'Compliance & Security',
    complianceHeroDescription: 'We maintain the highest standards of compliance and security to protect your business and data.',
    complianceAreasTitle: 'Compliance Areas',
    complianceAreasDescription: 'We adhere to international standards and regulations',
    complianceDataProtectionTitle: 'Data Protection',
    complianceDataProtectionDesc: 'Protecting your personal and business data',
    complianceFinancialTitle: 'Financial Compliance',
    complianceFinancialDesc: 'Meeting financial industry standards',
    complianceInternationalTitle: 'International Standards',
    complianceInternationalDesc: 'Global compliance frameworks',
    complianceGDPR: 'GDPR Compliance',
    complianceCCPA: 'CCPA Compliance',
    complianceSOC2: 'SOC 2 Type II',
    complianceISO27001: 'ISO 27001',
    complianceAML: 'Anti-Money Laundering',
    complianceKYC: 'Know Your Customer',
    compliancePCI: 'PCI DSS',
    complianceSOX: 'Sarbanes-Oxley',
    complianceOECD: 'OECD Guidelines',
    complianceFATCA: 'FATCA Compliance',
    complianceCRS: 'CRS Reporting',
    complianceBEPS: 'BEPS Framework',
    complianceCertificationsTitle: 'Certifications & Audits',
    complianceCertISO: 'ISO 27001 Certified',
    complianceCertISODesc: 'Information security management',
    complianceCertSOC: 'SOC 2 Type II',
    complianceCertSOCDesc: 'Security and availability controls',
    complianceCertGDPR: 'GDPR Compliant',
    complianceCertGDPRDesc: 'European data protection standards',
    complianceStatusCertified: 'Certified',
    complianceStatusCompliant: 'Compliant',
  tr: {
    // Navigation
    home: 'Ana Sayfa',
    services: 'Hizmetler',
    countries: 'Ülkeler',
    about: 'Hakkımızda',
    blog: 'Blog',
    contact: 'İletişim',
    login: 'Giriş',
    register: 'Kayıt Ol',
    logout: 'Çıkış',
    dashboard: 'Panel',
    viewAllServices: 'Tüm Hizmetleri Gör',
    viewAllCountries: 'Tüm Ülkeleri Gör',

    // Pricing Page
    pricingHeroTitle: 'Basit, Şeffaf Fiyatlandırma',
    pricingHeroDescription: 'İşletmenizin ihtiyaçlarına uygun planı seçin. Gizli ücret yok, sürpriz yok.',
    pricingBasicPlan: 'Temel',
    pricingBasicPrice: 'Hizmet başına ödeme',
    pricingBasicDesc: 'Bireysel projeler için mükemmel',
    pricingBasicFeature1: 'AI danışmanlığı',
    pricingBasicFeature2: 'Uzman eşleştirme',
    pricingBasicFeature3: 'Temel destek',
    pricingBasicFeature4: 'Belge şablonları',
    pricingProfessionalPlan: 'Profesyonel',
    pricingProfessionalPrice: '299$/ay',
    pricingProfessionalDesc: 'Büyüyen işletmeler için',
    pricingProfessionalFeature1: 'Temel plandaki her şey',
    pricingProfessionalFeature2: 'Öncelikli destek',
    pricingProfessionalFeature3: 'Çoklu projeler',
    pricingProfessionalFeature4: 'Gelişmiş analitik',
    pricingProfessionalFeature5: 'Uyumluluk izleme',
    pricingEnterprisePlan: 'Kurumsal',
    pricingEnterprisePrice: 'Özel',
    pricingEnterpriseDesc: 'Büyük organizasyonlar için',
    pricingEnterpriseFeature1: 'Profesyonel plandaki her şey',
    pricingEnterpriseFeature2: 'Özel hesap yöneticisi',
    pricingEnterpriseFeature3: 'Özel entegrasyonlar',
    pricingEnterpriseFeature4: 'SLA garantileri',
    pricingEnterpriseFeature5: 'Beyaz etiket seçenekleri',
    pricingPopularBadge: 'En Popüler',
    pricingGetStarted: 'Başlayın',

    // Partners Page
    partnersHeroTitle: 'Consulting19 ile Ortaklık',
    partnersHeroDescription: 'Küresel uzman ağımıza katılın ve girişimcilerin uluslararası genişlemesine yardım edin.',
    partnersTypesTitle: 'Ortaklık Fırsatları',
    partnersTypesDescription: 'İşbirliği yapmanın ve birlikte büyümenin çeşitli yolları',
    partnersConsultantTitle: 'Uzman Danışmanlar',
    partnersConsultantDesc: 'İş danışmanları ağımıza katılın',
    partnersConsultantBenefit1: 'Küresel müşteri tabanına erişim',
    partnersConsultantBenefit2: '%65 gelir paylaşımı',
    partnersConsultantBenefit3: 'Pazarlama desteği',
    partnersConsultantBenefit4: 'Mesleki gelişim',
    partnersReferralTitle: 'Yönlendirme Ortakları',
    partnersReferralDesc: 'Müşteri yönlendirerek komisyon kazanın',
    partnersReferralBenefit1: 'Rekabetçi komisyonlar',
    partnersReferralBenefit2: 'Pazarlama materyalleri',
    partnersReferralBenefit3: 'İzleme paneli',
    partnersReferralBenefit4: 'Sürekli destek',
    partnersIntegrationTitle: 'Teknoloji Ortakları',
    partnersIntegrationDesc: 'Platformumuzla entegre olun',
    partnersIntegrationBenefit1: 'API erişimi',
    partnersIntegrationBenefit2: 'Ortak pazarlama fırsatları',
    partnersIntegrationBenefit3: 'Teknik destek',
    partnersIntegrationBenefit4: 'Gelir paylaşımı',
    partnersApplyNow: 'Şimdi Başvur',
    partnersFeaturedTitle: 'Öne Çıkan Ortaklar',
    partnersFeaturedDescription: 'Olağanüstü hizmet sunmamıza yardımcı olan güvenilir ortaklar',
    partnersLawFirmDesc: 'Uluslararası hukuk hizmetleri',
    partnersBankingDesc: 'Kurumsal bankacılık çözümleri',
    partnersTaxDesc: 'Vergi optimizasyon stratejileri',
    partnersCtaTitle: 'Bizimle Ortaklık Yapmaya Hazır mısınız?',
    partnersCtaDescription: 'Uluslararası iş genişlemesini demokratikleştirme misyonumuza katılın.',
    partnersJoinNetwork: 'Ağımıza Katılın',
    partnersLearnMore: 'Daha Fazla Bilgi',

    // Documentation Page
    docsHeroTitle: 'Dokümantasyon',
    docsHeroDescription: 'Consulting19 platformu ve hizmetlerini kullanmak için bilmeniz gereken her şey.',
    docsSearchPlaceholder: 'Dokümantasyonda ara...',
    docsGettingStartedTitle: 'Başlangıç',
    docsGettingStartedDesc: 'Hızlı başlangıç kılavuzları ve öğreticiler',
    docsQuickStartTitle: 'Hızlı Başlangıç Kılavuzu',
    docsAccountSetupTitle: 'Hesap Kurulumu',
    docsFirstProjectTitle: 'İlk Projeniz',
    docsAPITitle: 'API Referansı',
    docsAPIDesc: 'Tam API dokümantasyonu',
    docsAPIReferenceTitle: 'API Referansı',
    docsWebhooksTitle: 'Webhook\'lar',
    docsSDKsTitle: 'SDK\'lar ve Kütüphaneler',
    docsGuidesTitle: 'Kılavuzlar',
    docsGuidesDesc: 'Adım adım kılavuzlar',
    docsCompanyFormationTitle: 'Şirket Kurma Kılavuzu',
    docsBankingTitle: 'Bankacılık Kurulum Kılavuzu',
    docsTaxPlanningTitle: 'Vergi Planlama Kılavuzu',

    // Status Page
    statusHeroTitle: 'Sistem Durumu',
    statusHeroDescription: 'Tüm Consulting19 hizmetleri ve sistemlerinin gerçek zamanlı durumu.',
    statusAllSystemsOperational: 'Tüm Sistemler Çalışıyor',
    statusLastUpdated: 'Son güncelleme',
    statusServicesTitle: 'Hizmet Durumu',
    statusAPITitle: 'API Hizmetleri',
    statusWebsiteTitle: 'Web Sitesi',
    statusDatabaseTitle: 'Veritabanı',
    statusPaymentsTitle: 'Ödeme İşleme',
    statusUptime: 'Çalışma Süresi',
    statusResponseTime: 'Yanıt Süresi',
    statusOperational: 'Çalışıyor',
    statusDegraded: 'Yavaşlamış',
    statusDown: 'Çalışmıyor',
    statusIncidentsTitle: 'Son Olaylar',
    statusIncident1Title: 'Kısa API yavaşlaması',
    statusIncident1Desc: 'Geçici performans düşüşü çözüldü',
    statusIncident2Title: 'Planlı bakım',
    statusIncident2Desc: 'Planlanan sistem güncellemeleri tamamlandı',
    statusResolved: 'Çözüldü',
    statusDuration: 'Süre',
    statusNoIncidents: 'Rapor edilecek son olay yok',

    // Cookie Policy Page
    cookiesHeroTitle: 'Çerez Politikası',
    cookiesHeroDescription: 'Platformumuzdaki deneyiminizi geliştirmek için çerezleri nasıl kullandığımızı öğrenin.',
    cookiesLastUpdated: 'Son güncelleme',
    cookiesUpdateDate: 'Ocak 2025',
    cookiesEssentialTitle: 'Gerekli Çerezler',
    cookiesEssentialDesc: 'Temel işlevsellik için gerekli',
    cookiesEssentialExamples: 'Kimlik doğrulama, güvenlik, tercihler',
    cookiesAnalyticsTitle: 'Analitik Çerezler',
    cookiesAnalyticsDesc: 'Kullanım kalıplarını anlamamıza yardımcı olur',
    cookiesAnalyticsExamples: 'Google Analytics, performans metrikleri',
    cookiesSecurityTitle: 'Güvenlik Çerezleri',
    cookiesSecurityDesc: 'Dolandırıcılık ve kötüye kullanıma karşı koruma',
    cookiesSecurityExamples: 'CSRF koruması, oturum güvenliği',
    cookiesWhatAreTitle: 'Çerezler Nedir?',
    cookiesWhatAreDesc: 'Çerezler, web sitemizi ziyaret ettiğinizde cihazınızda saklanan küçük metin dosyalarıdır. Tercihlerinizi hatırlayarak ve hizmetlerimizi nasıl kullandığınızı analiz ederek size daha iyi bir deneyim sunmamıza yardımcı olurlar.',
    cookiesHowWeUseTitle: 'Çerezleri Nasıl Kullanıyoruz',
    cookiesHowWeUseDesc: 'Çerezleri çeşitli amaçlar için kullanıyoruz:',
    cookiesUse1: 'Temel web sitesi işlevselliği ve güvenlik',
    cookiesUse2: 'Tercihlerinizi ve ayarlarınızı hatırlama',
    cookiesUse3: 'Web sitesi performansını ve kullanımını analiz etme',
    cookiesUse4: 'Hizmetlerimizi ve kullanıcı deneyimini geliştirme',
    cookiesTypesTitle: 'Kullandığımız Çerez Türleri',
    cookiesEssentialFullDesc: 'Bu çerezler web sitesinin düzgün çalışması için gereklidir. Güvenlik, ağ yönetimi ve erişilebilirlik gibi temel işlevleri etkinleştirirler.',
    cookiesAnalyticsFullDesc: 'Bu çerezler, ziyaretçilerin web sitemizle nasıl etkileşimde bulunduğunu anonim olarak bilgi toplayıp raporlayarak anlamamıza yardımcı olur.',
    cookiesMarketingTitle: 'Pazarlama Çerezleri',
    cookiesMarketingFullDesc: 'Bu çerezler ilgili reklamları sunmak ve pazarlama kampanyalarımızın etkinliğini takip etmek için kullanılır.',
    cookiesControlTitle: 'Çerez Tercihlerinizi Yönetme',
    cookiesControlDesc: 'Tarayıcı ayarlarınız aracılığıyla çerezleri kontrol edebilir ve yönetebilirsiniz. Ancak, belirli çerezleri devre dışı bırakmak web sitemizin işlevselliğini etkileyebilir.',
    cookiesContactTitle: 'Bize Ulaşın',
    cookiesContactDesc: 'Çerez politikamız hakkında sorularınız varsa, lütfen bize ulaşın:',
    cookiesContactEmail: 'E-posta',

    // Compliance Page
    complianceHeroTitle: 'Uyumluluk ve Güvenlik',
    complianceHeroDescription: 'İşinizi ve verilerinizi korumak için en yüksek uyumluluk ve güvenlik standartlarını sürdürüyoruz.',
    complianceAreasTitle: 'Uyumluluk Alanları',
    complianceAreasDescription: 'Uluslararası standartlara ve düzenlemelere uyuyoruz',
    complianceDataProtectionTitle: 'Veri Koruma',
    complianceDataProtectionDesc: 'Kişisel ve iş verilerinizi koruma',
    complianceFinancialTitle: 'Mali Uyumluluk',
    complianceFinancialDesc: 'Finansal sektör standartlarını karşılama',
    complianceInternationalTitle: 'Uluslararası Standartlar',
    complianceInternationalDesc: 'Küresel uyumluluk çerçeveleri',
    complianceGDPR: 'GDPR Uyumluluğu',
    complianceCCPA: 'CCPA Uyumluluğu',
    complianceSOC2: 'SOC 2 Type II',
    complianceISO27001: 'ISO 27001',
    complianceAML: 'Kara Para Aklamayla Mücadele',
    complianceKYC: 'Müşteriyi Tanı',
    compliancePCI: 'PCI DSS',
    complianceSOX: 'Sarbanes-Oxley',
    complianceOECD: 'OECD Kılavuzları',
    complianceFATCA: 'FATCA Uyumluluğu',
    complianceCRS: 'CRS Raporlama',
    complianceBEPS: 'BEPS Çerçevesi',
    complianceCertificationsTitle: 'Sertifikalar ve Denetimler',
    complianceCertISO: 'ISO 27001 Sertifikalı',
    complianceCertISODesc: 'Bilgi güvenliği yönetimi',
    complianceCertSOC: 'SOC 2 Type II',
    complianceCertSOCDesc: 'Güvenlik ve kullanılabilirlik kontrolleri',
    complianceCertGDPR: 'GDPR Uyumlu',
    complianceCertGDPRDesc: 'Avrupa veri koruma standartları',
    complianceStatusCertified: 'Sertifikalı',
    complianceStatusCompliant: 'Uyumlu',
  },
  pt: {
    // Navigation
    home: 'Início',
    services: 'Serviços',
    countries: 'Países',
    about: 'Sobre',
    blog: 'Blog',
    contact: 'Contato',
    login: 'Entrar',
    register: 'Registrar',
    logout: 'Sair',
    dashboard: 'Painel',
    viewAllServices: 'Ver Todos os Serviços',
    viewAllCountries: 'Ver Todos os Países',

    // Pricing Page
    pricingHeroTitle: 'Preços Simples e Transparentes',
    pricingHeroDescription: 'Escolha o plano que se adapta às necessidades do seu negócio. Sem taxas ocultas, sem surpresas.',
    pricingBasicPlan: 'Básico',
    pricingBasicPrice: 'Pagamento por serviço',
    pricingBasicDesc: 'Perfeito para projetos individuais',
    pricingBasicFeature1: 'Consultoria AI',
    pricingBasicFeature2: 'Correspondência de especialistas',
    pricingBasicFeature3: 'Suporte básico',
    pricingBasicFeature4: 'Modelos de documentos',
    pricingProfessionalPlan: 'Profissional',
    pricingProfessionalPrice: '$299/mês',
    pricingProfessionalDesc: 'Para empresas em crescimento',
    pricingProfessionalFeature1: 'Tudo no Básico',
    pricingProfessionalFeature2: 'Suporte prioritário',
    pricingProfessionalFeature3: 'Múltiplos projetos',
    pricingProfessionalFeature4: 'Análises avançadas',
    pricingProfessionalFeature5: 'Monitoramento de conformidade',
    pricingEnterprisePlan: 'Empresarial',
    pricingEnterprisePrice: 'Personalizado',
    pricingEnterpriseDesc: 'Para grandes organizações',
    pricingEnterpriseFeature1: 'Tudo no Profissional',
    pricingEnterpriseFeature2: 'Gerente de conta dedicado',
    pricingEnterpriseFeature3: 'Integrações personalizadas',
    pricingEnterpriseFeature4: 'Garantias SLA',
    pricingEnterpriseFeature5: 'Opções de marca branca',
    pricingPopularBadge: 'Mais Popular',
    pricingGetStarted: 'Começar',

    // Partners Page
    partnersHeroTitle: 'Parceria com Consulting19',
    partnersHeroDescription: 'Junte-se à nossa rede global de especialistas e ajude empreendedores a expandir internacionalmente.',
    partnersTypesTitle: 'Oportunidades de Parceria',
    partnersTypesDescription: 'Múltiplas formas de colaborar e crescer juntos',
    partnersConsultantTitle: 'Consultores Especialistas',
    partnersConsultantDesc: 'Junte-se à nossa rede de consultores de negócios',
    partnersConsultantBenefit1: 'Acesso à base global de clientes',
    partnersConsultantBenefit2: '65% de participação na receita',
    partnersConsultantBenefit3: 'Suporte de marketing',
    partnersConsultantBenefit4: 'Desenvolvimento profissional',
    partnersReferralTitle: 'Parceiros de Indicação',
    partnersReferralDesc: 'Ganhe comissões indicando clientes',
    partnersReferralBenefit1: 'Comissões competitivas',
    partnersReferralBenefit2: 'Materiais de marketing',
    partnersReferralBenefit3: 'Painel de acompanhamento',
    partnersReferralBenefit4: 'Suporte contínuo',
    partnersIntegrationTitle: 'Parceiros de Tecnologia',
    partnersIntegrationDesc: 'Integre com nossa plataforma',
    partnersIntegrationBenefit1: 'Acesso à API',
    partnersIntegrationBenefit2: 'Oportunidades de co-marketing',
    partnersIntegrationBenefit3: 'Suporte técnico',
    partnersIntegrationBenefit4: 'Compartilhamento de receita',
    partnersApplyNow: 'Candidatar-se Agora',
    partnersFeaturedTitle: 'Parceiros em Destaque',
    partnersFeaturedDescription: 'Parceiros confiáveis que nos ajudam a oferecer serviços excepcionais',
    partnersLawFirmDesc: 'Serviços jurídicos internacionais',
    partnersBankingDesc: 'Soluções bancárias corporativas',
    partnersTaxDesc: 'Estratégias de otimização fiscal',
    partnersCtaTitle: 'Pronto para Fazer Parceria Conosco?',
    partnersCtaDescription: 'Junte-se à nossa missão de democratizar a expansão internacional de negócios.',
    partnersJoinNetwork: 'Junte-se à Nossa Rede',
    partnersLearnMore: 'Saiba Mais',

    // Documentation Page
    docsHeroTitle: 'Documentação',
    docsHeroDescription: 'Tudo que você precisa saber sobre como usar a plataforma e serviços da Consulting19.',
    docsSearchPlaceholder: 'Pesquisar documentação...',
    docsGettingStartedTitle: 'Primeiros Passos',
    docsGettingStartedDesc: 'Guias de início rápido e tutoriais',
    docsQuickStartTitle: 'Guia de Início Rápido',
    docsAccountSetupTitle: 'Configuração da Conta',
    docsFirstProjectTitle: 'Seu Primeiro Projeto',
    docsAPITitle: 'Referência da API',
    docsAPIDesc: 'Documentação completa da API',
    docsAPIReferenceTitle: 'Referência da API',
    docsWebhooksTitle: 'Webhooks',
    docsSDKsTitle: 'SDKs e Bibliotecas',
    docsGuidesTitle: 'Guias',
    docsGuidesDesc: 'Guias passo a passo',
    docsCompanyFormationTitle: 'Guia de Formação de Empresa',
    docsBankingTitle: 'Guia de Configuração Bancária',
    docsTaxPlanningTitle: 'Guia de Planejamento Fiscal',

    // Status Page
    statusHeroTitle: 'Status do Sistema',
    statusHeroDescription: 'Status em tempo real de todos os serviços e sistemas da Consulting19.',
    statusAllSystemsOperational: 'Todos os Sistemas Operacionais',
    statusLastUpdated: 'Última atualização',
    statusServicesTitle: 'Status dos Serviços',
    statusAPITitle: 'Serviços de API',
    statusWebsiteTitle: 'Site',
    statusDatabaseTitle: 'Banco de Dados',
    statusPaymentsTitle: 'Processamento de Pagamentos',
    statusUptime: 'Tempo de Atividade',
    statusResponseTime: 'Tempo de Resposta',
    statusOperational: 'Operacional',
    statusDegraded: 'Degradado',
    statusDown: 'Inativo',
    statusIncidentsTitle: 'Incidentes Recentes',
    statusIncident1Title: 'Lentidão breve da API',
    statusIncident1Desc: 'Degradação temporária de performance resolvida',
    statusIncident2Title: 'Manutenção programada',
    statusIncident2Desc: 'Atualizações planejadas do sistema concluídas',
    statusResolved: 'Resolvido',
    statusDuration: 'Duração',
    statusNoIncidents: 'Nenhum incidente recente para relatar',

    // Cookie Policy Page
    cookiesHeroTitle: 'Política de Cookies',
    cookiesHeroDescription: 'Saiba como usamos cookies para melhorar sua experiência em nossa plataforma.',
    cookiesLastUpdated: 'Última atualização',
    cookiesUpdateDate: 'Janeiro 2025',
    cookiesEssentialTitle: 'Cookies Essenciais',
    cookiesEssentialDesc: 'Necessários para funcionalidade básica',
    cookiesEssentialExamples: 'Autenticação, segurança, preferências',
    cookiesAnalyticsTitle: 'Cookies de Análise',
    cookiesAnalyticsDesc: 'Nos ajudam a entender padrões de uso',
    cookiesAnalyticsExamples: 'Google Analytics, métricas de performance',
    cookiesSecurityTitle: 'Cookies de Segurança',
    cookiesSecurityDesc: 'Protegem contra fraude e abuso',
    cookiesSecurityExamples: 'Proteção CSRF, segurança de sessão',
    cookiesWhatAreTitle: 'O que são Cookies?',
    cookiesWhatAreDesc: 'Cookies são pequenos arquivos de texto armazenados em seu dispositivo quando você visita nosso site. Eles nos ajudam a fornecer uma melhor experiência lembrando suas preferências e analisando como você usa nossos serviços.',
    cookiesHowWeUseTitle: 'Como Usamos Cookies',
    cookiesHowWeUseDesc: 'Usamos cookies para vários propósitos:',
    cookiesUse1: 'Funcionalidade essencial do site e segurança',
    cookiesUse2: 'Lembrar suas preferências e configurações',
    cookiesUse3: 'Analisar performance e uso do site',
    cookiesUse4: 'Melhorar nossos serviços e experiência do usuário',
    cookiesTypesTitle: 'Tipos de Cookies que Usamos',
    cookiesEssentialFullDesc: 'Estes cookies são necessários para o funcionamento adequado do site. Eles habilitam funcionalidades essenciais como segurança, gerenciamento de rede e acessibilidade.',
    cookiesAnalyticsFullDesc: 'Estes cookies nos ajudam a entender como os visitantes interagem com nosso site coletando e relatando informações anonimamente.',
    cookiesMarketingTitle: 'Cookies de Marketing',
    cookiesMarketingFullDesc: 'Estes cookies são usados para entregar anúncios relevantes e rastrear a eficácia de nossas campanhas de marketing.',
    cookiesControlTitle: 'Gerenciando suas Preferências de Cookies',
    cookiesControlDesc: 'Você pode controlar e gerenciar cookies através das configurações do seu navegador. No entanto, desabilitar certos cookies pode afetar a funcionalidade do nosso site.',
    cookiesContactTitle: 'Entre em Contato',
    cookiesContactDesc: 'Se você tem dúvidas sobre nossa política de cookies, entre em contato:',
    cookiesContactEmail: 'Email',

    // Compliance Page
    complianceHeroTitle: 'Conformidade e Segurança',
    complianceHeroDescription: 'Mantemos os mais altos padrões de conformidade e segurança para proteger seu negócio e dados.',
    complianceAreasTitle: 'Áreas de Conformidade',
    complianceAreasDescription: 'Aderimos a padrões e regulamentações internacionais',
    complianceDataProtectionTitle: 'Proteção de Dados',
    complianceDataProtectionDesc: 'Protegendo seus dados pessoais e empresariais',
    complianceFinancialTitle: 'Conformidade Financeira',
    complianceFinancialDesc: 'Atendendo padrões da indústria financeira',
    complianceInternationalTitle: 'Padrões Internacionais',
    complianceInternationalDesc: 'Estruturas de conformidade global',
    complianceGDPR: 'Conformidade GDPR',
    complianceCCPA: 'Conformidade CCPA',
    complianceSOC2: 'SOC 2 Type II',
    complianceISO27001: 'ISO 27001',
    complianceAML: 'Anti-Lavagem de Dinheiro',
    complianceKYC: 'Conheça Seu Cliente',
    compliancePCI: 'PCI DSS',
    complianceSOX: 'Sarbanes-Oxley',
    complianceOECD: 'Diretrizes OCDE',
    complianceFATCA: 'Conformidade FATCA',
    complianceCRS: 'Relatórios CRS',
    complianceBEPS: 'Estrutura BEPS',
    complianceCertificationsTitle: 'Certificações e Auditorias',
    complianceCertISO: 'Certificado ISO 27001',
    complianceCertISODesc: 'Gestão de segurança da informação',
    complianceCertSOC: 'SOC 2 Type II',
    complianceCertSOCDesc: 'Controles de segurança e disponibilidade',
    complianceCertGDPR: 'Conforme GDPR',
    complianceCertGDPRDesc: 'Padrões europeus de proteção de dados',
    complianceStatusCertified: 'Certificado',
    complianceStatusCompliant: 'Conforme',
  },
  }
}
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'tr', 'pt'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}