```sql
    -- Add countries data
    INSERT INTO public.countries (id, name, code, flag_emoji, description, tax_rate, business_advantages, is_active, featured, image_url)
    VALUES
    ('1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d', 'United Arab Emirates', 'uae', '🇦🇪', 'The UAE is a premier destination for international business, offering zero corporate tax in many free zones, strategic location, and world-class infrastructure.', 0.00, ARRAY['0% corporate tax for 50 years in free zones', '100% foreign ownership allowed', 'No personal income tax', 'Strategic location between East and West', 'World-class infrastructure', 'Political and economic stability'], TRUE, TRUE, 'https://images.pexels.com/photos/1769606/pexels-photo-1769606.jpeg?auto=compress&cs=tinysrgb&w=800'),
    ('2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'Estonia', 'estonia', '🇪🇪', 'Estonia is a digital-first nation, offering the e-Residency program for 100% online business management and EU market access.', 20.00, ARRAY['Digital-first approach', 'EU market access', 'Low bureaucracy', 'Innovation-friendly', '100% online e-Residency program'], TRUE, TRUE, 'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=800'),
    ('3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'Georgia', 'georgia', '🇬🇪', 'Georgia offers one of the world''s most attractive tax regimes for small businesses with a 1% tax rate on turnover.', 1.00, ARRAY['Simple incorporation', 'Very low taxes (1% for small business)', 'Strategic location', 'Fast setup', 'Minimal bureaucracy'], TRUE, FALSE, 'https://images.pexels.com/photos/5137987/pexels-photo-5137987.jpeg?auto=compress&cs=tinysrgb&w=800'),
    ('4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'Malta', 'malta', '🇲🇹', 'Malta is an EU member state with an attractive tax system and a growing hub for blockchain and fintech industries.', 5.00, ARRAY['EU market access', 'Blockchain-friendly', 'English-speaking', 'Strategic Mediterranean location', 'Effective 5% corporate tax rate'], TRUE, FALSE, 'https://images.pexels.com/photos/1006965/pexels-photo-1006965.jpeg?auto=compress&cs=tinysrgb&w=800'),
    ('5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b', 'Panama', 'panama', '🇵🇦', 'Panama offers a territorial tax system, strong banking privacy, and a strategic location for international trade.', 25.00, ARRAY['Territorial taxation', 'Strong banking privacy', 'US dollar economy', 'International business hub', 'No tax on foreign-sourced income'], TRUE, FALSE, 'https://images.pexels.com/photos/1029604/pexels-photo-1029604.jpeg?auto=compress&cs=tinysrgb&w=800'),
    ('6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c', 'Portugal', 'portugal', '🇵🇹', 'Portugal offers attractive residency-by-investment programs and a favorable tax regime for new residents.', 21.00, ARRAY['EU market access', 'NHR tax program', 'Investment immigration', 'Strategic Atlantic location', 'Path to EU residency'], TRUE, FALSE, 'https://images.pexels.com/photos/2166559/pexels-photo-2166559.jpeg?auto=compress&cs=tinysrgb&w=800'),
    ('7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d', 'United States', 'usa', '🇺🇸', 'The United States offers the world''s largest economy and a diverse range of business opportunities.', 21.00, ARRAY['Largest consumer market', 'Advanced infrastructure', 'Innovation hub', 'Strong legal system', 'Flexible LLC formation'], TRUE, FALSE, 'https://images.pexels.com/photos/1975844/pexels-photo-1975844.jpeg?auto=compress&cs=tinysrgb&w=800'),
    ('8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e', 'Switzerland', 'switzerland', '🇨🇭', 'Switzerland is known for its political stability, world-class banking, and high-quality workforce.', 11.00, ARRAY['Political stability', 'World-class banking', 'Innovation hub', 'Strategic EU location', 'Favorable corporate tax rates'], TRUE, FALSE, 'https://images.pexels.com/photos/1906658/pexels-photo-1906658.jpeg?auto=compress&cs=tinysrgb&w=800'),
    ('9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f', 'Montenegro', 'montenegro', '🇲🇪', 'Montenegro is an EU candidate country offering a citizenship by investment program and low corporate taxes.', 9.00, ARRAY['EU candidate status', 'Citizenship by investment', 'Low corporate tax', 'Beautiful location', 'Visa-free travel to Schengen area'], TRUE, FALSE, 'https://images.pexels.com/photos/1659438/pexels-photo-1659438.jpeg?auto=compress&cs=tinysrgb&w=800');
    ```