@@ .. @@
-```sql
 /*
   # Insert Sample Services Data
 
@@ .. @@
 INSERT INTO services (id, consultant_id, country_id, title, description, price, is_recurring, billing_period, is_public, is_active, image_url) VALUES
 ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', (SELECT consultant_id FROM countries WHERE code = 'uae' LIMIT 1), (SELECT id FROM countries WHERE code = 'uae' LIMIT 1), 'UAE Company Formation', 'Complete business setup in Dubai International Financial Centre (DIFC) free zone with full banking support and compliance assistance.', 2500.00, false, null, true, true, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800'),
 ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', (SELECT consultant_id FROM countries WHERE code = 'uae' LIMIT 1), (SELECT id FROM countries WHERE code = 'uae' LIMIT 1), 'UAE Banking Solutions', 'Professional corporate banking assistance for opening business accounts in UAE banks with multi-currency support.', 800.00, false, null, true, true, 'https://images.pexels.com/photos/259200/pexels-photo-259200.jpeg?auto=compress&cs=tinysrgb&w=800'),
 ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', (SELECT consultant_id FROM countries WHERE code = 'estonia' LIMIT 1), (SELECT id FROM countries WHERE code = 'estonia' LIMIT 1), 'Estonia e-Residency', 'Complete e-Residency application and digital company formation in Estonia with EU market access.', 1200.00, false, null, true, true, 'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=800'),
 ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', (SELECT consultant_id FROM countries WHERE code = 'georgia' LIMIT 1), (SELECT id FROM countries WHERE code = 'georgia' LIMIT 1), 'Georgia Small Business Setup', 'Establish your business in Georgia with 1% small business tax status and minimal compliance requirements.', 600.00, false, null, true, true, 'https://images.pexels.com/photos/5137987/pexels-photo-5137987.jpeg?auto=compress&cs=tinysrgb&w=800'),
 ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a15', (SELECT consultant_id FROM countries WHERE code = 'malta' LIMIT 1), (SELECT id FROM countries WHERE code = 'malta' LIMIT 1), 'Malta EU Company Formation', 'Establish your EU company in Malta with 5% effective corporate tax rate and full European market access.', 1800.00, false, null, true, true, 'https://images.pexels.com/photos/1006965/pexels-photo-1006965.jpeg?auto=compress&cs=tinysrgb&w=800'),
 ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a16', (SELECT consultant_id FROM countries WHERE code = 'panama' LIMIT 1), (SELECT id FROM countries WHERE code = 'panama' LIMIT 1), 'Panama Territorial Tax Setup', 'Benefit from Panama territorial tax system with no tax on foreign-sourced income and strong banking privacy.', 1500.00, false, null, true, true, 'https://images.pexels.com/photos/1029604/pexels-photo-1029604.jpeg?auto=compress&cs=tinysrgb&w=800');
-```