/*
  # Insert Test Data

  This migration creates test users and sample data for development.
  
  Test Users:
  1. Admin: admin@consulting19.com / Admin123!
  2. Consultant (Georgia): giorgi.meskhi@consulting19.com / Consultant123!
  3. Client: client@consulting19.com / Client123!

  Note: These users will be created through the application signup process
  This file contains the data that will be inserted after user creation.
*/

-- This will be populated after users are created through the auth system
-- The user IDs will be generated by Supabase Auth

-- Sample services for Georgia consultant (will be inserted after consultant user is created)
-- Sample project data (will be inserted after users are created)

-- For now, this file serves as a placeholder for the test data structure
-- The actual data insertion will happen through the application interface

-- Update Georgia country with consultant (will be done after consultant user creation)
-- UPDATE countries SET consultant_id = 'consultant-uuid-here' WHERE code = 'GE';